# HTML5 Notification

- platform: html5
  name: HTML5
  vapid_pub_key: !secret html5_vapid_public_key
  vapid_prv_key: !secret html5_vapid_private_key
  vapid_email: !secret html5_email
  # gcm_api_key: !secret html5_key
  # gcm_sender_id: !secret html5_project_number
