- id: '1689084919801'
  alias: Guest Room Lutron Pico Remote - Actions
  description: ''
  use_blueprint:
    path: gregtakacs/lutron_pico_5_button_actions.yaml
    input:
      pico_id: f55558e66b8f403aed6dc6acc7450363
      short_click_action_on:
      - service: light.turn_on
        data:
          brightness_pct: 100
        target:
          entity_id: light.guest_bedroom_ceiling_fan_light
      delay_click: 100
      long_click_action_stop:
      - choose:
        - conditions:
          - condition: device
            device_id: 20ccbd965e7ecffa2c3f6aa986c8066b
            domain: climate
            entity_id: 3168ca97d3fcaef6881da8dde095d3f6
            type: is_hvac_mode
            hvac_mode: cool
            alias: If the AC is on...
          sequence:
          - service: climate.set_hvac_mode
            data:
              hvac_mode: 'off'
            target:
              entity_id: climate.corbans_office_ac
            alias: Turn off the AC
        default:
        - device_id: 20ccbd965e7ecffa2c3f6aa986c8066b
          domain: climate
          entity_id: 3168ca97d3fcaef6881da8dde095d3f6
          type: set_hvac_mode
          hvac_mode: cool
          enabled: true
          alias: Turn on the AC
        - delay:
            hours: 0
            minutes: 0
            seconds: 0
            milliseconds: 250
        - service: climate.set_preset_mode
          data:
            preset_mode: none
          target:
            entity_id: climate.corbans_office_ac
          alias: Set preset mode to off (not Eco)
        - delay:
            hours: 0
            minutes: 0
            seconds: 0
            milliseconds: 100
        - service: climate.set_temperature
          data:
            temperature: 73
          target:
            entity_id: climate.corbans_office_ac
          alias: Set temperature to 73
        - delay:
            hours: 0
            minutes: 0
            seconds: 0
            milliseconds: 100
        - service: climate.set_fan_mode
          data:
            fan_mode: LOW
          target:
            entity_id: climate.corbans_office_ac
          alias: Set fan to low
        enabled: false
      long_click_action_up: []
      short_click_action_up:
      - service: fan.increase_speed
        data:
          percentage_step: 25
        target:
          entity_id: fan.guest_bedroom_ceiling_fan
      short_click_action_down:
      - service: fan.decrease_speed
        data:
          percentage_step: 25
        target:
          entity_id: fan.guest_bedroom_ceiling_fan
      short_click_action_off:
      - service: light.turn_off
        data:
          transition: 1
        target:
          entity_id: light.guest_bedroom_ceiling_fan_light
      short_click_action_stop:
      - service: fan.toggle
        data: {}
        target:
          entity_id: fan.guest_bedroom_ceiling_fan
- id: '1703638107345'
  alias: Office Closet Light - Door Trigger
  description: ''
  use_blueprint:
    path: mkosmo/closet-light-from-door-sensor.yaml
    input:
      door_sensor: binary_sensor.office_closet_door_sensor_contact
      light_switch:
        entity_id: light.office_closet_light
      light_timeout: 1800
- id: '1705870296732'
  alias: Hall Aux Switch - Pause Living Room TV
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: f6a3f0606ae31f561f4c700f5917deed
    type: action
    subtype: aux_config_single
    discovery_id: 0xb43a31fffe34e475 action_aux_config_single
  condition: []
  action:
  - service: media_player.media_play_pause
    metadata: {}
    data: {}
    target:
      device_id: 0e47eccd7765e50037be8ffc24099a13
  mode: single
- id: '1710728057701'
  alias: Utility Closet Light - Door Trigger
  description: ''
  use_blueprint:
    path: mkosmo/closet-light-from-door-sensor.yaml
    input:
      door_sensor: binary_sensor.linen_closet_door_sensor_contact
      light_switch:
        entity_id: light.utility_closet_switch
      light_timeout: 1800
- id: '1710728130096'
  alias: Coat Closet Light - Door Trigger
  description: ''
  use_blueprint:
    path: mkosmo/closet-light-from-door-sensor.yaml
    input:
      door_sensor: binary_sensor.coat_closet_door_sensor_contact
      light_switch:
        entity_id: light.coat_closet_light
      light_timeout: 1800
- id: '1710814441742'
  alias: Hold Kitchen Light Switches to Control Area Lights
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 9f61f3f1b573c3799a54ee705f98034f
    type: action
    subtype: up_held
    id: 'on'
  - platform: device
    domain: mqtt
    device_id: 9f61f3f1b573c3799a54ee705f98034f
    type: action
    subtype: down_held
    id: 'off'
  - platform: device
    domain: mqtt
    device_id: f6a3f0606ae31f561f4c700f5917deed
    type: action
    subtype: up_held
    id: 'on'
  - platform: device
    domain: mqtt
    device_id: f6a3f0606ae31f561f4c700f5917deed
    type: action
    subtype: down_held
    id: 'off'
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - 'on'
      sequence:
      - service: light.turn_on
        metadata: {}
        data: {}
        target:
          area_id: 4872200594374640b069eaeee79e9ec6
    - conditions:
      - condition: trigger
        id:
        - 'off'
      sequence:
      - service: light.turn_off
        metadata: {}
        data: {}
        target:
          area_id: 4872200594374640b069eaeee79e9ec6
  mode: single
- id: '1710989410744'
  alias: Display Garage Door Status on Kitchen Bar Light LED Strip
  description: ''
  trigger:
  - platform: state
    entity_id:
    - cover.ratgdo_left_garage_door_door
    - cover.ratgdo_right_garage_door_door
    - binary_sensor.garage_side_person_door_contact
  condition: []
  action:
  - choose:
    - conditions:
      - condition: or
        conditions:
        - condition: state
          entity_id: cover.ratgdo_right_garage_door_door
          state: open
        - condition: state
          entity_id: cover.ratgdo_left_garage_door_door
          state: open
        - condition: state
          entity_id: binary_sensor.garage_side_person_door_contact
          state: 'on'
      sequence:
      - service: script.inovelli_led_control
        metadata: {}
        data:
          led: All
          color: Purple
          level: 62
          duration: Indefinitely
          target:
            device_id: 9f61f3f1b573c3799a54ee705f98034f
          effect: Solid
        alias: Set LED strip to purple
      alias: If any door is open
    default:
    - service: script.inovelli_led_control
      metadata: {}
      data:
        led: All
        target:
          device_id: 9f61f3f1b573c3799a54ee705f98034f
        effect: Clear
      alias: Clear LED Strip
  mode: single
- id: '1711145973507'
  alias: Pantry Door Light
  description: ''
  use_blueprint:
    path: mkosmo/closet-light-from-door-sensor.yaml
    input:
      door_sensor: binary_sensor.pantry_door_sensor_contact
      light_switch:
        entity_id: light.pantry_lights
      light_timeout: 1200
