- id: '1689084919801'
  alias: Office Lutron Pico Remote - Actions
  description: ''
  use_blueprint:
    path: gregtakacs/lutron_pico_5_button_actions.yaml
    input:
      pico_id: f55558e66b8f403aed6dc6acc7450363
      short_click_action_on:
      - service: light.turn_on
        data: {}
        target:
          entity_id: light.corban_s_office_lamp
      delay_click: 175
      long_click_action_stop:
      - choose:
        - conditions:
          - condition: device
            device_id: 20ccbd965e7ecffa2c3f6aa986c8066b
            domain: climate
            entity_id: 3168ca97d3fcaef6881da8dde095d3f6
            type: is_hvac_mode
            hvac_mode: cool
            alias: If the AC is on...
          sequence:
          - service: climate.set_hvac_mode
            data:
              hvac_mode: 'off'
            target:
              entity_id: climate.corbans_office_ac
            alias: Turn off the AC
        default:
        - device_id: 20ccbd965e7ecffa2c3f6aa986c8066b
          domain: climate
          entity_id: 3168ca97d3fcaef6881da8dde095d3f6
          type: set_hvac_mode
          hvac_mode: cool
          enabled: true
          alias: Turn on the AC
        - delay:
            hours: 0
            minutes: 0
            seconds: 0
            milliseconds: 250
        - service: climate.set_preset_mode
          data:
            preset_mode: none
          target:
            entity_id: climate.corbans_office_ac
          alias: Set preset mode to off (not Eco)
        - delay:
            hours: 0
            minutes: 0
            seconds: 0
            milliseconds: 100
        - service: climate.set_temperature
          data:
            temperature: 73
          target:
            entity_id: climate.corbans_office_ac
          alias: Set temperature to 73
        - delay:
            hours: 0
            minutes: 0
            seconds: 0
            milliseconds: 100
        - service: climate.set_fan_mode
          data:
            fan_mode: LOW
          target:
            entity_id: climate.corbans_office_ac
          alias: Set fan to low
      long_click_action_up: []
