homeassistant:
  name: !secret home_name
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  # See: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York

  customize: !include_dir_merge_named customize

  packages: !include_dir_named packages

http:
  api_password: !secret http_api_password
  base_url: !secret http_base_url

# Checks for available updates
updater:
  include_used_components: true

config:

hassio:

recorder:
  purge_interval: 2
  purge_keep_days: 60
  exclude:
    domains:
      - weblink
      - automation
      - group
      - updater
      - camera
      - script
    entities:
      - sun.sun
      - sensor.time
      - sensor.outbound_busses_from_station # Changes often, and no value in tracking
      - sensor.busses_at_stop
      - sensor.bus_1_time
      - sensor.bus_1_route
      - sensor.bus_2_time
      - sensor.bus_2_route

history:
  exclude:
    domains:
      - weblink
      - automation
      - group
      - updater
      - camera
      - script
    entities:
      - sun.sun
      - sensor.time
      - sensor.outbound_busses_from_station # Changes often, and no value in tracking
      - sensor.busses_at_stop
      - sensor.bus_1_time
      - sensor.bus_1_route
      - sensor.bus_2_time
      - sensor.bus_2_route

history_graph:
  temperatures:
    name: Temperatures
    entities:
      - sensor.living_room_temperature
      - sensor.dark_sky_temperature
    hours_to_show: 72
  humidities:
    name: Humidities
    entities:
      - sensor.living_room_humidity
      - sensor.dark_sky_humidity
    hours_to_show: 72

frontend:
  themes: !include themes.yaml

# Discover some devices automatically
discovery:

# Allows sending a magic packet directly.
wake_on_lan:

# Track the sun
sun:

# View all events in a logbook
logbook:

logger:
  default: warn
  logs:
    # Spits out errors because I don't leave OctoPrint running.
    homeassistant.components.octoprint: critical
    # The server is often sleeping when HASS restarts. I should force it to wake up on reboots, but not today.
    homeassistant.components.media_player.plex: critical
    # The TV is often sleeping when HASS restarts. I should force it to wake up on reboots or use standby mode, but it works for now.
    homeassistant.components.media_player.roku: critical

mqtt:
  broker: core-mosquitto # Addon
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true

device_tracker:
  - platform: mqtt
    devices:
      edith_wifi: !secret edith_wifi_mqtt_topic
      jackie_wifi: !secret jackie_wifi_mqtt_topic
  - platform: google_maps
    username: !secret google_maps_username
    password: !secret google_maps_password
  # - platform: bluetooth_tracker
  #   track_new_devices: False
  #   consider_home: 60

map:

tradfri:
  host: !secret tradfri_host
  allow_tradfri_groups: false

# usps:
#   username: !secret usps_username
#   password: !secret usps_password

# TODO: Set up the Nest in the new apartment.
# nest:
#   client_id: !secret nest_client_id
#   client_secret: !secret nest_client_secret

octoprint:
  - host: !secret octoprint_host
    api_key: !secret octoprint_api_key
    bed: true
    number_of_tools: 1

ifttt:
  key: !secret ifttt_key

ffmpeg:

camera:
  - platform: generic
    still_image_url: !secret radar_image_url
    name: Radar

panel_iframe:
  google_calendar:
    title: 'Calendar'
    icon: mdi:calendar
    url: !secret google_calendar_url

alexa:

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

# google_domains:
#   domain: !secret google_domains_url
#   username: !secret google_domains_username
#   password: !secret google_domains_password

google_assistant:
  project_id: !secret google_assistant_project_id
  api_key: !secret google_assistant_api_key
  expose_by_default: false
  entity_config: !include google_assistant_entities.yaml

tts:
  - platform: google

weblink:
  entities:
    - name: 'Node-RED Flows'
      url: 'http://hassio.local:1880'
      icon: mdi:nodejs
    - name: 'TasmoAdmin'
      url: 'http://hassio.local:9541/devices'
      icon: mdi:lightbulb-on

# automation: !include_dir_merge_list automation
group: !include_dir_merge_named group
input_boolean: !include_dir_merge_named input_boolean
input_select: !include_dir_merge_named input_select
intent_script: !include_dir_merge_named intent_script
# light: !include_dir_merge_list light
media_player: !include_dir_merge_list media_player
notify: !include_dir_merge_list notify
scene: !include_dir_merge_list scene
script: !include_dir_merge_named script
sensor: !include_dir_merge_list sensor
shell_command: !include_dir_merge_named shell_command
switch: !include_dir_merge_list switch
zone: !include_dir_merge_list zone
