homeassistant:
  name: !secret home_name
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  # See: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York

  customize: !include_dir_merge_named customize

  packages: !include_dir_named packages

http:
  api_password: !secret http_api_password
  base_url: !secret http_base_url
#  ip_ban_enabled: True
#  login_attempts_threshold: 3 # Three strikes

# Checks for available updates
updater:
  include_used_components: true

# Trying out the HASS Cloud
cloud:
  alexa: !include cloud_alexa.yaml
  google_actions: !include cloud_google.yaml

config:

hassio:

recorder:
  purge_interval: 2
  purge_keep_days: 60
  exclude:
    domains:
      - weblink
      - automation
      - group
      - updater
      - camera
      - script
    entities:
      - sun.sun   # Don't record sun data
      - sensor.yi_most_recent_recording # It changes each minute
      - sensor.time

# Enables support for tracking state changes over time.
history:
  exclude:
    domains:
      - weblink
      - automation
      - group
      - updater
      - camera
      - script
    entities:
      - sun.sun   # Don't record sun data
      - sensor.yi_most_recent_recording # It changes each minute
      - sensor.time

history_graph:
  temperatures:
    name: Temperatures
    entities:
      - sensor.living_room_thermostat_temperature
      - sensor.bedroom_temperature
      - sensor.dark_sky_temperature
    hours_to_show: 72

# Enables the frontend
frontend:
  themes:
    darkcyan:
      # Main colors that can be changed
      primary-color: "#00bcd4"
      disabled-text-color: "#545454"
      divider-color: "rgba(255, 255, 255, 0.12)"
      paper-card-background-color: "#4e4e4e"
      paper-grey-200: "#191919"
      paper-item-icon-color: "#d3d3d3"
      paper-listbox-background-color: "#202020"
      paper-listbox-color: "#FFFFFF"
      primary-background-color: "#303030"
      primary-text-color: "#cfcfcf"
      secondary-background-color: "#2b2b2b"
      secondary-text-color: "#04a7bc"
      # Colors based on variables, see above
      label-badge-background-color: "var(--secondary-background-color)"
      label-badge-text-color: "var(--text-primary-color)"
      paper-card-header-color: "#var(--paper-item-icon-color)"
      paper-grey-50: "var(--primary-text-color)"
      paper-item-icon-active-color: "var(--primary-color)"
      paper-item-icon_-_color: "var(--primary-text-color)"
      paper-slider-active-color: "var(--primary-color)"
      paper-slider-knob-color: "var(--primary-color)"
      paper-slider-knob-start-color: "var(--primary-color)"
      paper-slider-pin-color: "var(--primary-color)"
      paper-slider-secondary-color: "var(--light-primary-color)"
      paper-toggle-button-checked-ink-color: "var(--dark-primary-color)"
      paper-toggle-button-checked-button-color: "var(--primary-color)"
      paper-toggle-button-checked-bar-color: "var(--light-primary-color)"
      paper-toggle-button-unchecked-bar-color: "var(--primary-text-color)"
    dark_theme:
      # Main colors
      primary-color: '#5294E2'                                                        # Header
      accent-color: '#E45E65'                                                         # Accent color
      dark-primary-color: 'var(--accent-color)'                                       # Hyperlinks
      light-primary-color: 'var(--accent-color)'                                      # Horizontal line in about
      # Text colors
      primary-text-color: '#FFFFFF'                                                   # Primary text colour, here is referencing dark-primary-color
      text-primary-color: 'var(--primary-text-color)'                                 # Primary text colour
      secondary-text-color: '#5294E2'                                                 # For secondary titles in more info boxes etc.
      disabled-text-color: '#7F848E'                                                  # Disabled text colour
      label-badge-border-color: 'green'                                               # Label badge border, just a reference value
      # Background colors
      primary-background-color: '#383C45'                                             # Settings background
      secondary-background-color: '#383C45'                                           # Main card UI background
      divider-color: 'rgba(0, 0, 0, .12)'                                             # Divider
      # Table rows
      table-row-background-color: '#353840'                                           # Table row
      table-row-alternative-background-color: '#3E424B'                               # Table row alternative
      # Nav Menu
      paper-listbox-color: 'var(--primary-color)'                                     # Navigation menu selection hoover
      paper-listbox-background-color: '#2E333A'                                       # Navigation menu background
      paper-grey-50: 'var(--primary-text-color)'
      paper-grey-200: '#414A59'                                                       # Navigation menu selection
      # Paper card
      paper-card-header-color: 'var(--accent-color)'                                  # Card header text colour
      paper-card-background-color: '#434954'                                          # Card background colour
      paper-dialog-background-color: '#434954'                                        # Card dialog background colour
      paper-item-icon-color: 'var(--primary-text-color)'                              # Icon color
      paper-item-icon-active-color: '#F9C536'                                         # Icon color active
      paper-item-icon_-_color: 'green'
      paper-item-selected_-_background-color: '#434954'                               # Popup item select
      paper-tabs-selection-bar-color: 'green'
      # Labels
      label-badge-red: 'var(--accent-color)'                                          # References the brand colour label badge border
      label-badge-text-color: 'var(--primary-text-color)'                             # Now same as label badge border but that's a matter of taste
      label-badge-background-color: '#2E333A'                                         # Same, but can also be set to transparent here
      # Switches
      paper-toggle-button-checked-button-color: 'var(--accent-color)'
      paper-toggle-button-checked-bar-color: 'var(--accent-color)'
      paper-toggle-button-checked-ink-color: 'var(--accent-color)'
      paper-toggle-button-unchecked-button-color: 'var(--disabled-text-color)'
      paper-toggle-button-unchecked-bar-color: 'var(--disabled-text-color)'
      paper-toggle-button-unchecked-ink-color: 'var(--disabled-text-color)'
      # Sliders
      paper-slider-knob-color: 'var(--accent-color)'
      paper-slider-knob-start-color: 'var(--accent-color)'
      paper-slider-pin-color: 'var(--accent-color)'
      paper-slider-active-color: 'var(--accent-color)'
      paper-slider-container-color: 'linear-gradient(var(--primary-background-color), var(--secondary-background-color)) no-repeat'
      paper-slider-secondary-color: 'var(--secondary-background-color)'
      paper-slider-disabled-active-color: 'var(--disabled-text-color)'
      paper-slider-disabled-secondary-color: 'var(--disabled-text-color)'
      # Google colors
      google-red-500: '#E45E65'
      google-green-500: '#39E949'

# Discover some devices automatically
# discovery:

# Allows you to issue voice commands from the frontend
# conversation:

# Track the sun
sun:

# View all events in a logbook
logbook:

logger:
  # default: info
  default: warn
  # logs:
    # homeassistant.components.device_tracker.netgear: critical
    # homeassistant.components.device_tracker: critical

mqtt:
  broker: core-mosquitto # Addon
  username: !secret mqtt_username
  password: !secret mqtt_password

device_tracker:
  - platform: mqtt
    devices:
      edith_wifi: /devices/location/edith_wifi
      jackie_wifi: /devices/location/jackie_wifi
  - platform: google_maps
    username: !secret google_maps_username
    password: !secret google_maps_password
  # - platform: bluetooth_tracker
  #   track_new_devices: False
  #   consider_home: 60

map:

# usps:
#   username: !secret usps_username
#   password: !secret usps_password

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

octoprint:
  host: !secret octoprint_host
  api_key: !secret octoprint_api_key
  bed: true
  number_of_tools: 1

ifttt:
  key: !secret ifttt_key

ffmpeg:

camera:
  - platform: generic
    still_image_url: !secret radar_image_url
    name: Radar

panel_iframe:
  google_calendar:
    title: 'Calendar'
    icon: mdi:calendar
    url: !secret google_calendar_url
  nodered_flows:
    title: 'Node-RED Flows'
    url: 'http://hassio.local:1880'
    icon: mdi:nodejs
  sonweb:
    title: 'SonWEB'
    url: 'http://hassio.local:9541/devices'
    icon: mdi:lightbulb-on

alexa:

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

# google_domains:
#   domain: !secret google_domains_url
#   username: !secret google_domains_username
#   password: !secret google_domains_password

tts:
  - platform: google

# emulated_hue:
#   host_ip: !secret hass_ip_address
#   expose_by_default: false

automation: !include_dir_merge_list automation
group: !include_dir_merge_named group
input_boolean: !include_dir_merge_named input_boolean
input_select: !include_dir_merge_named input_select
intent_script: !include_dir_merge_named intent_script
light: !include_dir_merge_list light
media_player: !include_dir_merge_list media_player
notify: !include_dir_merge_list notify
scene: !include_dir_merge_list scene
script: !include_dir_merge_named script
sensor: !include_dir_merge_list sensor
shell_command: !include_dir_merge_named shell_command
switch: !include_dir_merge_list switch
zone: !include_dir_merge_list zone
