homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret home_name
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data
  elevation: !secret home_elevation
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  customize: !include_dir_merge_named customize

http:
  api_password: !secret http_api_password
  # SSL is now being handled by NGINX
  # ssl_certificate: !secret http_ssl_certificate_path
  # ssl_key: !secret http_ssl_key_path

# Checks for available updates
updater:

# Enables support for tracking state changes over time.
history:

# Enables the frontend
frontend:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend
conversation:

# Track the sun
sun:

# View all events in a logbook
logbook:

logger:
  # default: info
  default: warn
  # logs:
    # homeassistant.components.device_tracker.netgear: critical
    # homeassistant.components.device_tracker: critical

mqtt:
  broker: 127.0.0.1
  # port: 1883
  # client_id: home-assistant-1
  username: !secret mqtt_username
  password: !secret mqtt_password

device_tracker:
  # platform: netgear
  # host: !secret router_netgear_host
  # port: !secret router_netgear_port
  # username: !secret router_netgear_username
  # password: !secret router_netgear_password
  platform: nmap_tracker
  hosts: !secret nmap_hosts
  # home_interval: 10
  track_new_devices: no

ifttt:
  key: !secret ifttt_key

# ffmpeg:
#   ffmpeg_bin: /usr/local/bin/ffmpeg/ffmpeg

automation: !include_dir_merge_list automation
group: !include_dir_merge_named group
input_boolean: !include_dir_merge_named input_boolean
light: !include_dir_merge_list light
media_player: !include_dir_merge_list media_player
notify: !include_dir_merge_list notify
scene: !include_dir_merge_list scene
script: !include_dir_merge_named script
sensor: !include_dir_merge_list sensor
shell_command: !include_dir_merge_named shell_command
switch: !include_dir_merge_list switch
