homeassistant:
  customize: !include customize.yaml # Allows adding customizations (mostly icon overrides) in the UI.
  packages: !include_dir_named packages

default_config:

# These are all of the individual things I used to have before switching to default_config.
# updater:
# person:
# config:
# cloud:
# system_health:
# ssdp:
# zeroconf:
# sun:
# logbook:
# map:
# mobile_app:

hassio:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
  ip_ban_enabled: true
  login_attempts_threshold: 5

recorder:
  db_url: !secret mariadb_url
  purge_keep_days: 60
  exclude:
    domains:
      - updater
      - camera
      - script
    entities:
      - sun.sun
      - sensor.time

history:
  exclude:
    domains:
      - updater
      - camera
      - script
    entities:
      - sun.sun
      - sensor.time

frontend:
  themes: !include_dir_merge_named themes

lovelace:

browser_mod:
  prefix: "browser_mod_"
  devices:
    e88176f4-7e67e28b:
      name: browser_mod_kitchen_display
    7093a437-bbd888b8:
      name: browser_mod_wall_display
  disable:
    - all

# Allows sending a magic packet directly.
wake_on_lan:

logger:
  default: warning
  logs:
    # Spits out errors because I don't leave OctoPrint running.
    homeassistant.components.octoprint: critical
    # The TV is often sleeping when HASS restarts. I should force it to wake up on reboots or use standby mode, but it works for now.
    homeassistant.components.media_player.roku: critical
    custom_components.package_concierge.sensor: info # A little extra logging for custom components.

ifttt:
  key: !secret ifttt_key

ffmpeg:

# Google Calendar
google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret
  track_new_calendar: false

# google_assistant:
#   project_id: !secret google_assistant_project_id
#   report_state: true
#   service_account: !include google_cloud_assistant_credentials.json
#   expose_by_default: false
#   entity_config: !include google_assistant_entities.yaml

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

spotcast:
  sp_dc: !secret spotcast_sp_dc
  sp_key: !secret spotcast_sp_key

tts:
  - platform: google_translate
  - platform: google_cloud
    key_file: google_cloud_credentials.json
    voice: en-US-Standard-C

# automation: !include_dir_merge_list automation
automation: !include automations.yaml # For the automation editor
binary_sensor: !include_dir_merge_list binary_sensor
fan: !include fans.yaml
group: !include_dir_merge_named group
# input_boolean: !include_dir_merge_named input_boolean
# input_select: !include_dir_merge_named input_select
light: !include_dir_merge_list light
# media_player: !include_dir_merge_list media_player
notify: !include_dir_merge_list notify
scene: !include scenes.yaml # For the scene editor
# script: !include_dir_merge_named script
sensor: !include_dir_merge_list sensor
# shell_command: !include_dir_merge_named shell_command
switch: !include_dir_merge_list switch
zone: !include_dir_merge_list zone
