homeassistant:
  name: !secret home_name
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  # See: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York

  customize: !include_dir_merge_list customize

  packages: !include_dir_named packages

http:
  api_password: !secret http_api_password
  base_url: !secret http_base_url
  ip_ban_enabled: True
  login_attempts_threshold: 3 # Three strikes
  # SSL is now being handled by NGINX
  # ssl_certificate: !secret http_ssl_certificate_path
  # ssl_key: !secret http_ssl_key_path

# Checks for available updates
updater:

recorder:
  purge_days: 14
  exclude:
    domains:
      - weblink
      - automation
      - group
      - updater
    entities:
      - sun.sun   # Don't record sun data

# Enables support for tracking state changes over time.
history:
  exclude:
    domains:
      - weblink
      - automation
      - group
      - updater
    entities:
      - sun.sun   # Don't record sun data

# Enables the frontend
frontend:

# Discover some devices automatically
# discovery:

# Allows you to issue voice commands from the frontend
# conversation:

# Track the sun
sun:

# View all events in a logbook
logbook:

logger:
  # default: info
  default: warn
  # logs:
    # homeassistant.components.device_tracker.netgear: critical
    # homeassistant.components.device_tracker: critical

mqtt:
  broker: 127.0.0.1
  # port: 1883
  # client_id: home-assistant-1
  username: !secret mqtt_username
  password: !secret mqtt_password

device_tracker:
  - platform: mqtt
    devices:
      ida_ida: /devices/location/ida_ida
      jackie_jackie: /devices/location/jackie_jackie

ifttt:
  key: !secret ifttt_key

ffmpeg:
  ffmpeg_bin: /usr/local/bin/ffmpeg/ffmpeg

camera:
  - platform: ffmpeg
    name: yi
    # input: rtsp://10.0.0.250:554/ch0_0.h264
    input: rtsp://10.0.0.250:554/ch0_1.h264
    extra_arguments: "-pred 1"

panel_iframe:
  google_calendar:
    title: 'Calendar'
    icon: mdi:calendar
    url: !secret google_calendar_url

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

tts:
  - platform: google

emulated_hue:
  host_ip: !secret hass_ip_address
  expose_by_default: false

alexa:
  intents: !include_dir_merge_named alexa_intents
automation: !include_dir_merge_list automation
group: !include_dir_merge_named group
input_boolean: !include_dir_merge_named input_boolean
input_select: !include_dir_merge_named input_select
light: !include_dir_merge_list light
media_player: !include_dir_merge_list media_player
notify: !include_dir_merge_list notify
scene: !include_dir_merge_list scene
script: !include_dir_merge_named script
sensor: !include_dir_merge_list sensor
shell_command: !include_dir_merge_named shell_command
switch: !include_dir_merge_list switch
zone: !include_dir_merge_list zone
