homeassistant:
  name: !secret home_name
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  # See: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York

  customize: !include_dir_merge_named customize

  packages: !include_dir_named packages

http:
  api_password: !secret http_api_password
  base_url: !secret http_base_url
  ip_ban_enabled: True
  login_attempts_threshold: 3 # Three strikes

# Checks for available updates
updater:
  include_used_components: true

recorder:
  db_url: !secret mysql_db_connection
  purge_days: 31
  exclude:
    domains:
      - weblink
      - automation
      - group
      - updater
      - camera
      - script
    entities:
      - sun.sun   # Don't record sun data
      - sensor.yi_most_recent_recording # It changes each minute

# Enables support for tracking state changes over time.
history:
  exclude:
    domains:
      - weblink
      - automation
      - group
      - updater
      - camera
      - script
    entities:
      - sun.sun   # Don't record sun data
      - sensor.yi_most_recent_recording # It changes each minute

# Enables the frontend
frontend:

# Discover some devices automatically
# discovery:

# Allows you to issue voice commands from the frontend
# conversation:

# Track the sun
sun:

# View all events in a logbook
logbook:

logger:
  # default: info
  default: warn
  # logs:
    # homeassistant.components.device_tracker.netgear: critical
    # homeassistant.components.device_tracker: critical

mqtt:
  broker: 127.0.0.1
  # port: 1883
  # client_id: home-assistant-1
  username: !secret mqtt_username
  password: !secret mqtt_password

device_tracker:
  - platform: mqtt
    devices:
      edith_wifi: /devices/location/edith_wifi
      jackie_wifi: /devices/location/jackie_wifi
  # - platform: bluetooth_tracker
  #   track_new_devices: False
  #   consider_home: 60

# usps:
#   username: !secret usps_username
#   password: !secret usps_password

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

octoprint:
  host: !secret octoprint_host
  api_key: !secret octoprint_api_key
  bed: true
  number_of_tools: 1

ifttt:
  key: !secret ifttt_key

ffmpeg:

camera:
  - platform: generic
    still_image_url: !secret radar_image_url
    name: Radar

panel_iframe:
  google_calendar:
    title: 'Calendar'
    icon: mdi:calendar
    url: !secret google_calendar_url

alexa:

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

tts:
  - platform: google

emulated_hue:
  host_ip: !secret hass_ip_address
  expose_by_default: false

automation: !include_dir_merge_list automation
group: !include_dir_merge_named group
input_boolean: !include_dir_merge_named input_boolean
input_select: !include_dir_merge_named input_select
intent_script: !include_dir_merge_named intent_script
light: !include_dir_merge_list light
media_player: !include_dir_merge_list media_player
notify: !include_dir_merge_list notify
scene: !include_dir_merge_list scene
script: !include_dir_merge_named script
sensor: !include_dir_merge_list sensor
shell_command: !include_dir_merge_named shell_command
switch: !include_dir_merge_list switch
zone: !include_dir_merge_list zone
