- platform: template
  fans:
    bedroom_fan:
      # Wrap the bedroom fan switch in a `fan` entity.
      friendly_name: "Bedroom Fan"
      availability_template: >-
        {%- if not is_state("switch.bedroom_fan", "unavailable") %}
          true
        {%- endif %}
      value_template: "{{ states('switch.bedroom_fan') }}"
      turn_on:
        - service: switch.turn_on
          data:
            entity_id: switch.bedroom_fan
      turn_off:
        - service: switch.turn_off
          data:
            entity_id: switch.bedroom_fan
    office_fan:
      # Wrap a power_tail in a `fan` entity
      friendly_name: "Office Fan"
      availability_template: >-
        {%- if not is_state("switch.power_tail_3", "unavailable") %}
          true
        {%- endif %}
      value_template: "{{ states('switch.power_tail_3') }}"
      turn_on:
        - service: switch.turn_on
          data:
            entity_id: switch.power_tail_3
      turn_off:
        - service: switch.turn_off
          data:
            entity_id: switch.power_tail_3
