# Create `light` entities for many `switch`es.

- platform: switch
  name: Ginger Bread Tin Light
  entity_id: switch.power_tail_4

- platform: switch
  name: Christmas Tree Lights
  entity_id: switch.power_tail_5
