# Create `light` entities for many `switch`es.

- platform: switch
  name: Plant Lamp
  entity_id: switch.power_tail_1

- platform: switch
  name: Kallax Lamp
  entity_id: switch.power_tail_2

- platform: switch
  name: Ginger Bread Tin Light
  entity_id: switch.power_tail_3

- platform: switch
  name: Couch Side Table Lamp
  entity_id: switch.power_tail_4

- platform: switch
  name: Office Lamp
  entity_id: switch.power_tail_5

- platform: switch
  name: Christmas Tree Lights
  entity_id: switch.ikea_socket_1
