- platform: mqtt_json
  name: bedroom_headboard_rgb
  state_topic: "home/rgb1"
  command_topic: "home/rgb1/set"
  brightness: true
  rgb: true
  optimistic: false
  retain: true
  qos: 0
- platform: mqtt_json
  name: exit_sign
  state_topic: "home/exit"
  command_topic: "home/exit/set"
  brightness: true
  rgb: false
  optimistic: false
  retain: true
  qos: 0