# MQTT JSON lights

- platform: mqtt_json
  name: living_room_tv_backlight
  state_topic: "home/lrtvbacklight"
  command_topic: "home/lrtvbacklight/set"
  brightness: true
  rgb: true
  optimistic: false
  retain: true
  qos: 0

- platform: mqtt_json
  name: exit_sign
  state_topic: "home/exit"
  command_topic: "home/exit/set"
  brightness: true
  rgb: false
  optimistic: false
  retain: true
  qos: 0
