# MQTT JSON lights

- platform: mqtt_json
  name: living_room_tv_backlight
  state_topic: "home/lrtvbacklight"
  command_topic: "home/lrtvbacklight/set"
  brightness: true
  rgb: true
  optimistic: false
  retain: true
  qos: 0

# - platform: mqtt_json
#   name: fairy_lights
#   state_topic: "home/brfairylights"
#   command_topic: "home/brfairylights/set"
#   brightness: true
#   rgb: false
#   optimistic: false
#   retain: true
#   qos: 0

# - platform: mqtt_json
#   name: test_light
#   state_topic: "home/test_light"
#   command_topic: "home/test_light/set"
#   brightness: true
#   rgb: true
#   white_value: true
#   color_temp: true
#   effect: true
#   effect_list: [colorfade_slow, colorfade_fast, flash]
#   optimistic: false
#   retain: true
#   qos: 0
