- platform: group
  name: Office Lamp
  entities:
    - light.office_lamp_top
    - light.office_lamp_middle
    # - light.office_lamp_bottom # Controlled separately.

- platform: group
  name: Office Lights
  entities:
    - light.plant_lamp
    - light.office_lamp
    - light.office_lamp_bottom
    - light.office_leds
