- platform: group
  name: "Corban's Office Lamp"
  entities:
    - light.corban_s_office_lamp_top
    - light.corban_s_office_lamp_middle
    # - light.corban_s_office_lamp_bottom # Controlled separately.
