esphome:
  name: office-outlet-sensor
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: INFO
api:
ota:

sensor:
  - platform: wifi_signal
    name: "Office Outlet Sensor - WiFi Signal"
    update_interval: 60s

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO5
    name: "Office Outlet Sensor"
    device_class: power

switch:
  - platform: gpio
    pin: GPIO4
    name: "Office Outlet Output"
