esphome:
  name: soundbar-controller
  platform: ESP8266
  board: d1_mini
  arduino_version: recommended

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

# Enable logging
logger:
  level: INFO

ota:

remote_receiver:
  pin:
    number: D7
    inverted: True
  # dump: all

remote_transmitter:
  pin: D1
  carrier_duty_percent: 50%

switch:
  # Soundbar Power
  - platform: template
    name: "Soundbar"
    assumed_state: true
    icon: mdi:surround-sound
    # On this soundbar, volume down is ignored if the soundbar is off, and volume up turns it on.
    # Using this, we can build sequences that will always turn the soundbar on and off, regardless
    # of its starting state, and leave it at its initial volume level.
    turn_on_action:
      - switch.turn_on: sb_vol_down
      - delay: 200ms
      - switch.turn_on: sb_vol_up
    turn_off_action:
      # First, ensure it's on.
      - switch.turn_on: sb_vol_down
      - delay: 200ms
      - switch.turn_on: sb_vol_up
      # It takes a bit after turning on before the soundbar will turn back off.
      - delay: 1200ms
      - switch.turn_on: sb_power

  # Soundbar - Individual Commands
  - platform: template
    id: sb_power
    name: "Soundbar: Power"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xBF40
  - platform: template
    id: sb_vol_up
    name: "Soundbar: Volume Up"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xBE41
  - platform: template
    id: sb_vol_down
    name: "Soundbar: Volume Down"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0xFF00
        command: 0xBA45

binary_sensor:
  - platform: remote_receiver
    name: "Roku Remote: Play/Pause Button"
    internal: true
    nec:
      address: 0xC7EA
      command: 0xB34C
    on_press:
      then:
        - homeassistant.event:
            event: esphome.living_room.play_pause

  - platform: remote_receiver
    name: "Living Room Remote - Source"
    internal: true
    nec:
      # This is the soundbar's play/pause command.
      address: 0xFF00
      command: 0x718E
    on_press:
      then:
        - homeassistant.event:
            event: esphome.living_room.source

  - platform: remote_receiver
    name: "Living Room Remote - Channel Up"
    internal: true
    nec:
      # This is the soundbar's skip forward command.
      address: 0xFF00
      command: 0x748B
    on_press:
      then:
        - homeassistant.event:
            event: esphome.living_room.channel_up

  - platform: remote_receiver
    name: "Living Room Remote - Channel Down"
    internal: true
    nec:
      # This is the soundbar's skip backwards command.
      address: 0xFF00
      command: 0x758A
    on_press:
      then:
        - homeassistant.event:
            event: esphome.living_room.channel_down

#### Reference:

# Captures of the Roku remote application buttons:
# Netflix:
# Received NEC: address=0xC7EA, command=0xAD52
# Received NEC: address=0xC7EA, command=0x2DD2
# Received NEC: address=0xC7EA, command=0x2DD2
# Amazon:
# Received NEC: address=0xC7EA, command=0xB44B
# Received NEC: address=0xC7EA, command=0x34CB
# Received NEC: address=0xC7EA, command=0x34CB
# Hulu:
# Received NEC: address=0xC7EA, command=0xB24D
# Received NEC: address=0xC7EA, command=0x32CD
# Received NEC: address=0xC7EA, command=0x32CD
# YouTube:
# Received NEC: address=0xC7EA, command=0xA956
# Received NEC: address=0xC7EA, command=0x29D6
# Received NEC: address=0xC7EA, command=0x29D6
