# MQTT

# - platform: mqtt
#   name: esp_test_switch_1
#   state_topic: "home/espled"
#   command_topic: "home/espled/set"
#   # payload_on: "ON"
#   # payload_off: "OFF"
#   # optimistic: false
#   qos: 0
#   retain: true
#   # value_template: "{{ value.x }}"

- platform: mqtt
  name: bedroom_fairy_lights
  state_topic: "home/sonoff/power_tail/1/stat"
  command_topic: "home/sonoff/power_tail/1"
  qos: 1
  payload_on: "on"
  payload_off: "off"
  retain: true
