# MQTT

# Power Tails
- platform: mqtt
  name: bedroom_fairy_lights # power_tail_1
  state_topic: "home/sonoff/power_tail/1/stat"
  command_topic: "home/sonoff/power_tail/1"
  qos: 1
  payload_on: "on"
  payload_off: "off"
  retain: true

# - platform: mqtt
#   name: power_tail_2
#   state_topic: "home/sonoff/power_tail/2/stat"
#   command_topic: "home/sonoff/power_tail/2"
#   qos: 1
#   payload_on: "on"
#   payload_off: "off"
#   retain: true

# - platform: mqtt
#   name: power_tail_3
#   state_topic: "home/sonoff/power_tail/3/stat"
#   command_topic: "home/sonoff/power_tail/3"
#   qos: 1
#   payload_on: "on"
#   payload_off: "off"
#   retain: true

# - platform: mqtt
#   name: power_tail_4
#   state_topic: "home/sonoff/power_tail/4/stat"
#   command_topic: "home/sonoff/power_tail/4"
#   qos: 1
#   payload_on: "on"
#   payload_off: "off"
#   retain: true

# - platform: mqtt
#   name: power_tail_5
#   state_topic: "home/sonoff/power_tail/5/stat"
#   command_topic: "home/sonoff/power_tail/5"
#   qos: 1
#   payload_on: "on"
#   payload_off: "off"
#   retain: true
