# MQTT

# Power Tails
# - platform: mqtt
#   name: power_tail_1
#   state_topic: "stat/sonoff_1/POWER"
#   command_topic: "cmnd/sonoff_1/POWER"
#   availability_topic: "tele/sonoff_1/LWT"
#   qos: 1
#   payload_on: "ON"
#   payload_off: "OFF"
#   payload_available: "Online"
#   payload_not_available: "Offline"
#   retain: true

- platform: mqtt
  name: small_fan # power_tail_2
  state_topic: "stat/sonoff_2/POWER"
  command_topic: "cmnd/sonoff_2/POWER"
  availability_topic: "tele/sonoff_2/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true

- platform: mqtt
  name: office_pink_lamp # power_tail_3
  state_topic: "stat/sonoff_3/POWER"
  command_topic: "cmnd/sonoff_3/POWER"
  availability_topic: "tele/sonoff_3/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true

- platform: mqtt
  name: Office Desk Lamp # power_tail_4
  icon: mdi:desk-lamp
  state_topic: "stat/sonoff_4/POWER"
  command_topic: "cmnd/sonoff_4/POWER"
  availability_topic: "tele/sonoff_4/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true

- platform: mqtt
  name: living_room_couch # power_tail_5
  state_topic: "stat/sonoff_5/POWER"
  command_topic: "cmnd/sonoff_5/POWER"
  availability_topic: "tele/sonoff_5/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
