# substitutions:
#   device_name: "garage-parking-sensor-right"
#   friendly_name: Garage Parking Sensor - Right

esphome:
  name: "${device_name}"
  friendly_name: "${friendly_name}"

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf

packages:
  device_base: !include device_base.yaml

# Enable logging
logger:
  level: INFO

# https://github.com/mrtoy-me/esphome-my-components/tree/main/vl53l1x
external_components:
  - source: components

switch:
  - platform: template
    name: "Poll Range Sensor"
    optimistic: true
    icon: mdi:update
    id: poll_range_sensor

interval:
  - interval: 200ms
    then:
      - if:
          condition:
            switch.is_on: poll_range_sensor
          then:
            - component.update: range_sensor

i2c:
  - sda: 16
    scl: 17
    scan: true
    id: bus_a

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

  - platform: vl53l1x
    i2c_id: bus_a
    id: range_sensor
    distance_mode: long
    update_interval: never
    distance:
      name: "Distance"
      accuracy_decimals: 0
      filters:
        - timeout: 1000ms
    range_status:
      name: "Range Status"
      internal: true
