# Environment/Weather/Speedtest

view_environment:
  view: yes
  name: Environment
  icon: mdi:white-balance-sunny
  entities:
    - camera.radar
    - group.environment_outside
    - group.environment_livingroom
    - group.environment_bedroom
    - group.speedtest
    - group.darksky_sensors
    - history_graph.temperatures

environment_outside:
  name: Outside
  entities:
    - sensor.dark_sky_summary
    - sensor.dark_sky_temperature
    - sensor.dark_sky_humidity
    - sun.sun

environment_livingroom:
  name: Living Room
  entities:
    - sensor.living_room_thermostat_temperature
    - sensor.living_room_thermostat_target
    - sensor.living_room_thermostat_humidity
    - binary_sensor.living_room_thermostat_fan
    - binary_sensor.living_room_thermostat_has_leaf
    - sensor.living_room_thermostat_hvac_state
    - sensor.living_room_thermostat_operation_mode
    # - binary_sensor.living_room_thermostat_is_locked
    # - binary_sensor.living_room_thermostat_is_using_emergency_heat
    - binary_sensor.living_room_thermostat_online

environment_bedroom:
  name: Bedroom
  entities:
    - sensor.bedroom_temperature
    - sensor.bedroom_humidity

speedtest:
  name: Internet Speed
  entities:
    - sensor.speedtest_download
    - sensor.speedtest_upload
    - sensor.speedtest_ping

darksky_sensors:
  name: DarkSky Weather Sensors
  entities:
    - sensor.dark_sky_summary
    - sensor.dark_sky_minutely_summary
    - sensor.dark_sky_hourly_summary
    - sensor.dark_sky_temperature
    - sensor.dark_sky_daily_high_temperature
    - sensor.dark_sky_daily_low_temperature
    - sensor.dark_sky_apparent_temperature
    - sensor.dark_sky_daily_high_apparent_temperature
    - sensor.dark_sky_daily_low_apparent_temperature
    - sensor.dark_sky_humidity
    - sensor.dark_sky_precip_probability
    - sensor.dark_sky_precip
    - sensor.dark_sky_precip_intensity
    - sensor.dark_sky_daily_max_precip_intensity
    - sensor.dark_sky_cloud_coverage
