# Environment/Weather/Speedtest

view_environment:
  view: yes
  name: Environment
  entities:
    - camera.radar
    - camera.traffic_camera
    - camera.community_college
    - group.environment_outside
    - group.environment_livingroom
    - group.environment_bedroom
    - group.speedtest
    - group.darksky_sensors

environment_outside:
  name: Outside
  entities:
    - sensor.dark_sky_summary
    - sensor.dark_sky_temperature
    - sensor.dark_sky_humidity
    - sun.sun

environment_livingroom:
  name: Living Room
  entities:
    - sensor.living_room_temperature
    - sensor.living_room_humidity

environment_bedroom:
  name: Bedroom
  entities:
    - sensor.bedroom_temperature
    - sensor.bedroom_humidity

speedtest:
  name: Internet Speed
  entities:
    - sensor.speedtest_download
    - sensor.speedtest_upload
    - sensor.speedtest_ping

darksky_sensors:
  name: DarkSky Weather Sensors
  entities:
    - sensor.dark_sky_summary
    - sensor.dark_sky_minutely_summary
    - sensor.dark_sky_hourly_summary
    - sensor.dark_sky_temperature
    - sensor.dark_sky_daily_high_temperature
    - sensor.dark_sky_daily_low_temperature
    - sensor.dark_sky_apparent_temperature
    - sensor.dark_sky_daily_high_apparent_temperature
    - sensor.dark_sky_daily_low_apparent_temperature
    - sensor.dark_sky_humidity
    - sensor.dark_sky_precip_probability
    - sensor.dark_sky_precip
    - sensor.dark_sky_precip_intensity
    - sensor.dark_sky_daily_max_precip_intensity
    - sensor.dark_sky_cloud_coverage
