# Environment/Weather/Speedtest

view_environment:
  view: yes
  name: Environment
  entities:
    - group.environment_outside
    - group.environment_livingroom
    - group.environment_bedroom
    - group.speedtest

environment_outside:
  name: Outside
  entities:
    - sensor.owm_condition
    - sensor.owm_temperature
    - sensor.owm_humidity
    - sun.sun

environment_livingroom:
  name: Living Room
  entities:
    - sensor.living_room_temperature
    - sensor.living_room_humidity

environment_bedroom:
  name: Bedroom
  entities:
    - sensor.bedroom_temperature
    - sensor.bedroom_humidity

speedtest:
  name: Internet Speed
  entities:
    - sensor.speedtest_download
    - sensor.speedtest_upload
    - sensor.speedtest_ping
