esphome:
  name: door_buzzer
  platform: ESP8266
  board: d1_mini
  arduino_version: recommended
  esphome_core_version: latest
  on_boot:
    then:
      # Set servo to idle position on boot
      - output.set_level:
          id: servo
          level: 7.5%

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

# Enable logging
logger:
  level: INFO

ota:

output:
  - platform: esp8266_pwm
    id: servo
    frequency: 50Hz
    pin: D4
    # Servos operate at 50Hz with pulse width modulated signal
    # Their duty cycle determines the level.
    # Range is from 3% duty cycle to 12% duty cycle
    # 7.5% is idle level (according to arduino docs, also depends on
    # servo motor)

switch:
  - platform: template
    name: "Door Buzzer"
    assumed_state: true
    lambda: !lambda |-
      return false;
    turn_on_action:
      - output.set_level:
          id: servo
          level: 4%
      - delay: 2s # Wait a bit
      # Return to idle position
      - output.set_level:
          id: servo
          level: 7.5%
