esphome:
  name: exit_sign
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# 10.0.0.240

api:

# Enable logging
logger:
  level: INFO

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: 0
      inverted: True
    name: "Exit Sign Button"

output:
  - platform: esp8266_pwm
    pin: 2
    id: light_output

light:
  - platform: monochromatic
    name: "Exit Sign"
    output: light_output
    effects:
      - strobe:
      - strobe:
          name: "Fast Strobe"
          colors:
            - state: True
              brightness: 100%
              duration: 250ms
            - state: True
              brightness: 0%
              duration: 250ms
