esphome:
  name: fairy_lights_32
  platform: ESP32
  board: esp32doit-devkit-v1
  esphome_core_version: latest

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# 10.0.0.242

# Enable logging
logger:
  level: INFO

ota:

api:

output:
  - platform: ledc
    pin: 2
    frequency: 5000
    id: pin_2

light:
  - platform: monochromatic
    name: "Fairy Lights"
    output: pin_2
    effects:
      - strobe:
      - strobe:
          name: Fast Strobe
          colors:
            - state: True
              brightness: 100%
              duration: 250ms
            - state: True
              brightness: 0%
              duration: 250ms
