esphome:
  name: living_room_dht
  platform: ESP8266
  board: esp01_1m
  esphome_core_version: latest

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

# Enable logging
logger:
  level: INFO

ota:

sensor:
  - platform: dht
    pin: GPIO2
    model: DHT22
    temperature:
      name: "Living Room Temperature"
      filters:
        - sliding_window_moving_average:
            window_size: 30 # 5 minute window
            send_every: 6 # 1 minute
            send_first_at: 3
        - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"
    humidity:
      name: "Living Room Humidity"
      filters:
        - sliding_window_moving_average:
            window_size: 30 # 5 minute window
            send_every: 6 # 1 minute
            send_first_at: 3
    update_interval: 10s
