esphomeyaml:
  name: living_room_dht
  platform: ESP8266
  board: esp01_1m
  esphomelib_version: latest

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # manual_ip:
  #   static_ip: 10.0.0.245
  #   gateway: 10.0.0.1
  #   subnet: 255.255.255.0

mqtt:
  broker: !secret mqtt_broker_ip
  username: !secret mqtt_username_esphomelib
  password: !secret mqtt_password_esphomelib

# Enable logging
logger:
  level: INFO

ota:

sensor:
  - platform: dht
    pin: GPIO2
    model: DHT22
    temperature:
      name: "Living Room Temperature"
      expire_after: 30min
      filters:
        - sliding_window_moving_average:
            window_size: 30 # 5 minute window
            send_every: 6 # 1 minute
            send_first_at: 3
        - lambda: return x * (9.0/5.0) + 32.0;
      unit_of_measurement: "°F"
    humidity:
      name: "Living Room Humidity"
      expire_after: 30min
      filters:
        - sliding_window_moving_average:
            window_size: 30 # 5 minute window
            send_every: 6 # 1 minute
            send_first_at: 3
    update_interval: 10s
