esphomeyaml:
  name: tv_backlight
  platform: ESP8266
  board: esp01_1m
  esphomelib_version: latest

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # manual_ip:
  #   static_ip: 10.0.0.245
  #   gateway: 10.0.0.1
  #   subnet: 255.255.255.0

mqtt:
  broker: !secret mqtt_broker_ip
  username: !secret mqtt_username_esphomelib
  password: !secret mqtt_password_esphomelib

# Enable logging
logger:
  level: INFO

ota:

output:
  - platform: esp8266_pwm
    pin: 3 # Also the RX pin
    id: blue_output
  - platform: esp8266_pwm
    pin: 0
    id: red_output
  - platform: esp8266_pwm
    pin: 2
    id: green_output

light:
  - platform: rgb
    name: "Living Room TV Backlight"
    red: red_output
    green: green_output
    blue: blue_output
    effects:
      - random:
      - strobe:
      - flicker:
