esphome:
  name: umbrella
  platform: ESP8266
  board: d1_mini
  arduino_version: recommended
  on_boot:
    then:
      # Set servo to idle position on boot
      - servo.write:
          id: servo_out
          level: 0.0

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# 10.0.0.?

api:
  services:
    - service: control_servo
      variables:
        level: float
      then:
        - servo.write:
            id: servo_out
            level: !lambda 'return level / 100.0;'

# Enable logging
logger:
  level: INFO

ota:

output:
  - platform: esp8266_pwm
    pin: D2
    frequency: 50Hz
    id: servo_pin

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: D1
    num_leds: 16
    rgb_order: GRB
    name: "Umbrella Light"
    effects:
      - addressable_scan:
      - addressable_twinkle:

servo:
  - id: servo_out
    output: servo_pin
