- platform: time_date
  display_options:
    - 'time'

- platform: template
  sensors:
    local_display_time:
      friendly_name: "Time"
      device_class: timestamp
      value_template: >-
        {% set dummy = states("sensor.time") %}
        {{ now().strftime("%-I:%M%p") }}
