# Thermometer

# - platform: dht
#   sensor: DHT11
#   pin: 23
#   name: Bedroom
#   monitored_conditions:
#     - temperature
#     - humidity

# Living room
- platform: mqtt
  name: "Living Room Temperature"
  state_topic: "home/livingroom/temperature"
  qos: 0
  unit_of_measurement: "°F"

- platform: mqtt
  name: "Living Room Humidity"
  state_topic: "home/livingroom/humidity"
  qos: 0
  unit_of_measurement: "%"

# Bedroom
- platform: mqtt
  name: "Bedroom Temperature"
  state_topic: "home/bedroom/temperature"
  qos: 0
  unit_of_measurement: "°F"

- platform: mqtt
  name: "Bedroom Humidity"
  state_topic: "home/bedroom/humidity"
  qos: 0
  unit_of_measurement: "%"
