# Weather sensor

# - platform: openweathermap
#   api_key: !secret open_weather_map_api_key
#   # forecast: 1
#   monitored_conditions:
#     - weather
#     - temperature
#     # - wind_speed
#     - humidity
#     # - pressure
#     # - clouds
#     # - rain
#     # - snow

- platform: darksky
  api_key: !secret darksky_api_key
  update_interval:
    minutes: 5
  forecast:
    - 0
  monitored_conditions:
    - summary
    - icon
    - precip_type
    - precip_intensity
    - precip_intensity_max
    - precip_probability
    - temperature
    - temperature_high
    - temperature_low
    - apparent_temperature
    - apparent_temperature_high
    - apparent_temperature_low
    # - dew_point
    - wind_speed
    - wind_bearing
    - cloud_cover
    - humidity
    - pressure
    # - visibility
    # - ozone
    - minutely_summary
    - hourly_summary
    #- daily_summary
