# Weather sensor

- platform: darksky
  api_key: !secret darksky_api_key
  scan_interval:
    minutes: 5
  forecast:
    - 0
  monitored_conditions:
    - summary
    - icon
    - precip_type
    - precip_intensity
    - precip_intensity_max
    - precip_probability
    - temperature
    - temperature_high
    - temperature_low
    - apparent_temperature
    - apparent_temperature_high
    - apparent_temperature_low
    # - dew_point
    - wind_speed
    - wind_bearing
    - cloud_cover
    - humidity
    - pressure
    # - visibility
    # - ozone
    - minutely_summary
    - hourly_summary
    #- daily_summary
