# Weather sensor

- platform: darksky
  api_key: !secret darksky_api_key
  scan_interval:
    minutes: 5
  forecast:
    - 0
    - 1
  monitored_conditions:
    # Required for HADashboard
    - temperature
    - temperature_high
    - temperature_low
    - apparent_temperature
    - humidity
    - precip_probability
    - precip_intensity
    - precip_type
    - wind_speed
    - wind_bearing
    - pressure
    - icon

    - summary
    - cloud_cover