- alias: "Dash Button 1"
  trigger:
    platform: event
    event_type: dash_button_1
  # action:
  #   service: homeassistant.turn_off
  #   entity_id: group.everything_custom
  action:
    service: switch.toggle
    entity_id: switch.living_room_window
  # action:
  #   service: persistent_notification.create
  #   data:
  #     message: "Maybe you should do something with this..."
  #     title: "Dash Button Pressed"
