# Notification when I forget to turn off lights

- alias: Reminder to turn off the lights
  trigger:
    - platform: state
      entity_id: device_tracker.ida_ida
      from: "home"
      to: "not_home"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: 'device_tracker.maggie_phone'
        state: 'not_home'
      - condition: or
        conditions:
        - condition: state
          entity_id: group.all_switches
          state: 'on'
        - condition: state
          entity_id: group.all_lights
          state: 'on'
  action:
    service: notify.html5_ida
    data:
      title: "Lights are still on."
      message: "You seem to have left some lights on."
      data:
        actions:
          - action: "turn_off_lights"
            title: "Turn off"

- alias: Notification turn off lights clicked
  hide_entity: true
  trigger:
    platform: event
    event_type: html5_notification.clicked
    event_data:
      action: turn_off_lights
  action:
    service: homeassistant.turn_off
    entity_id:
      - group.all_switches
      - group.all_lights
