# Home Assistant Update Notification

- alias: HASS Update Notification
  trigger:
    - platform: state
      entity_id: updater.updater
  action:
    service: notify.html5_ida
    data:
      title: "Home Assistant Update"
      message: "There is a new Home Assistant release available."
