# Home Assistant Update Notification

- alias: HASS Update Notification
  trigger:
    - platform: state
      entity_id: updater.updater
  action:
    service: notify.html5_ida
    data:
      title: "Home Assistant Update"
    data_template:
      message: "Home Assistant version {{ states('updater.updater') }} is now available."
