# Notification to turn on a light when coming home

- alias: Ask to turn on a light when coming home
  trigger:
    - platform: state
      entity_id: device_tracker.ida_ida
      from: "not_home"
      to: "home"
  condition: 
    - condition: state
      entity_id: switch.living_room_lamp_near_tv
      state: "off"
  action:
    service: notify.html5_ida
    data:
      title: "Welcome Home"
      message: "Wanna light?"
      data:
        actions:
          - action: "turn_on_light_next_to_tv"
            title: "Turn on"

- alias: Notification turn on light next to TV clicked
  hide_entity: true
  trigger:
    platform: event
    event_type: html5_notification.clicked
    event_data:
      action: turn_on_light_next_to_tv
  action:
    service: switch.turn_on
    entity_id: switch.living_room_lamp_near_tv
