- alias: "Phone Fairy Toggle"
  trigger:
    - platform: event
      event_type: jackie_fairy_toggle
    - platform: event
      event_type: ida_fairy_toggle
  action:
    - service: light.toggle
      entity_id: light.fairy_lights
