- alias: "Play Pause - Kodi - On"
  hide_entity: true
  trigger:
    - platform: state
      entity_id: input_boolean.play_pause_kodi
      to: "on"
  condition:
    - condition: state
      entity_id: media_player.kodi_obama
      state: "paused"
  action: 
    - service: media_player.media_play
      entity_id: media_player.kodi_obama

- alias: "Play Pause - Kodi - Off"
  hide_entity: true
  trigger:
    - platform: state
      entity_id: input_boolean.play_pause_kodi
      to: "off"
  condition:
    - condition: state
      entity_id: media_player.kodi_obama
      state: "playing"
  action: 
    - service: media_player.media_pause
      entity_id: media_player.kodi_obama


# Set the input_boolean based on the state
- alias: "Kodi stops/pauses - set the boolean"
  hide_entity: true
  trigger:
    - platform: state
      entity_id: media_player.kodi_obama
      from: "playing"
  condition:
    - condition: state
      entity_id: input_boolean.play_pause_kodi
      state: "on"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.play_pause_kodi

- alias: "Kodi stops/pauses - set the boolean"
  hide_entity: true
  trigger:
    - platform: state
      entity_id: media_player.kodi_obama
      to: "playing"
  condition:
    - condition: state
      entity_id: input_boolean.play_pause_kodi
      state: "off"
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.play_pause_kodi
