- alias: "Set TV backlight - Off"
  hide_entity: true
  trigger:
    - platform: state
      entity_id: input_select.tv_backlight_selector
      to: "Off"
  action: 
    - service: light.turn_off
      entity_id: light.living_room_tv_backlight

- alias: "Set TV backlight - Bright White"
  hide_entity: true
  trigger:
    - platform: state
      entity_id: input_select.tv_backlight_selector
      to: "Bright White"
  action: 
    - service: scene.turn_on
      entity_id: scene.tv_bright

- alias: "Set TV backlight - Dim White"
  hide_entity: true
  trigger:
    - platform: state
      entity_id: input_select.tv_backlight_selector
      to: "Dim White"
  action: 
    - service: scene.turn_on
      entity_id: scene.tv_dim

- alias: "Set TV backlight - Kodi Background"
  hide_entity: true
  trigger:
    - platform: state
      entity_id: input_select.tv_backlight_selector
      to: "Kodi Background"
  action: 
    - service: scene.turn_on
      entity_id: scene.tv_kodi_background

- alias: "Set TV backlight - Spotify"
  hide_entity: true
  trigger:
    - platform: state
      entity_id: input_select.tv_backlight_selector
      to: "Spotify"
  action: 
    - service: scene.turn_on
      entity_id: scene.tv_spotify
