# Kodi (Obama) Media Player

- platform: kodi
  name: kodi_obama
  host: !secret obama_kodi_host
  port: !secret obama_kodi_port
  # user: !secret obama_kodi_user
  # password: !secret obama_kodi_password
  # turn_off_action: none
