- platform: universal
  name: Living Room TV
  children:
    - media_player.plex_65_tcl_roku_tv
    # - media_player.kodi_obama
    - media_player.65_tcl_roku_tv

# - platform: cast
#   host: !secret chromecast_host

# - platform: kodi
#   name: kodi_obama
#   host: !secret obama_host
#   port: !secret obama_kodi_port
#   turn_off_action:
#     service: media_player.kodi_call_method
#     data:
#       entity_id: media_player.kodi_obama
#       method: System.Suspend

- platform: universal
  name: Google Homes
  children:
    - media_player.everything
    - media_player.bathroom_speaker
    - media_player.bedroom_speaker
    - media_player.kitchen_speaker
    - media_player.living_room_speaker
    - media_player.office_speaker
