- platform: universal
  name: Living Room
  children:
    - media_player.kodi_obama
    - media_player.corban_and_maggie

- platform: cast
  host: !secret chromecast_host

- platform: kodi
  name: kodi_obama
  host: !secret obama_kodi_host
  port: !secret obama_kodi_port
  turn_off_action:
    service: media_player.kodi_call_method
    data:
      entity_id: media_player.kodi_obama
      method: System.Suspend
