# - platform: cast
#   host: !secret chromecast_host

- platform: universal
  name: Google Homes
  children:
    - media_player.everything
    - media_player.living_room_speaker
    - media_player.bathroom_speaker
    - media_player.bedroom_speaker
    - media_player.kitchen_speaker
    - media_player.office_speaker
