esphome:
  name: bedroom_outlet_sensor
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: INFO
api:
ota:

sensor:
  - platform: wifi_signal
    name: "Bedroom Outlet Sensor - WiFi Signal"
    update_interval: 60s

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO5
    name: "Bedroom Outlet Sensor"
    device_class: power

switch:
  - platform: gpio
    pin: GPIO4
    name: "Bedroom Outlet Output"
