esphome:
  name: blank-slate
  platform: ESP8266
  board: nodemcuv2

# Inspiration: https://esphome.io/cookbook/display_time_temp_oled.html

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  # use_address: blank-slate.local

api:

# Enable logging
logger:
  level: DEBUG

ota:

# Empty waiting for next flash.