esphome:
  name: espcam

esp32:
  board: esp32cam
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# 10.0.0.?

api:

# Enable logging
logger:
  level: WARN

ota:

color:
  - id: color_red
    red: 100%
    green: 0%
    blue: 0%
  - id: color_yellow
    red: 100%
    green: 100%
    blue: 0%
  - id: color_orange
    red: 96%
    green: 63%
    blue: 26%
  - id: color_green
    red: 0%
    green: 100%
    blue: 0%
  - id: color_blue
    red: 0%
    green: 0%
    blue: 100%
  - id: color_gray
    red: 50%
    green: 50%
    blue: 50%
  - id: color_white
    red: 100%
    green: 100%
    blue: 100%

font:
  # Georgia, for normal text
  - file: "resources/fonts/Georgia-Regular.ttf"
    id: georgia_12
    size: 12


spi:
  clk_pin: 0
  mosi_pin: 16
  miso_pin: 2

display:
  - platform: ili9341
    model: TFT 2.4
    cs_pin: 12
    dc_pin: 15
    led_pin: 14
    reset_pin: 13

    pages:
      - id: page_main
        lambda: |-
          int border_padding = 2;
          int mdi_width_offset = 35;
          int second_line_y_offset = 33;

          // Border
          it.rectangle(0,  0, it.get_width(), it.get_height(), id(color_blue));

          // Header Box
          it.rectangle(0, 40, it.get_width(), it.get_height(), id(color_blue));
          it.print(border_padding, border_padding, id(georgia_12), id(color_yellow), TextAlign::TOP_LEFT, "ESPHome");

# esp32_camera:
#   name: ESP Camera
#   external_clock:
#     pin: GPIO0
#     frequency: 20MHz
#   i2c_pins:
#     sda: GPIO26
#     scl: GPIO27
#   data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
#   vsync_pin: GPIO25
#   href_pin: GPIO23
#   pixel_clock_pin: GPIO22
#   power_down_pin: GPIO32
#   # Image settings
#   resolution: 1280x1024
#   max_framerate: 5 fps
#   idle_framerate: 0.1 fps
