esphome:
  name: fairy_lights_32
  platform: ESP32
  board: esp32doit-devkit-v1

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  # If I have problems again, try this:
  # power_save_mode: none

# Enable logging
logger:
  level: INFO

ota:
api:

sensor:
  - platform: wifi_signal
    name: "Fairy Lights - WiFi Signal"
    update_interval: 60s

output:
  - platform: ledc
    pin: 2
    frequency: 5000
    id: pin_2

light:
  - platform: monochromatic
    name: "Fairy Lights"
    output: pin_2
    effects:
      - strobe:
      - strobe:
          name: Fast Strobe
          colors:
            - state: True
              brightness: 100%
              duration: 250ms
            - state: True
              brightness: 0%
              duration: 250ms
