substitutions:
  device_name: "garage-parking-sensor-right"
  friendly_name: Garage Parking Sensor - Right

packages:
  garage_parking_sensor_base: !include common/garage_parking_sensor_base.yaml

# Add a motion sensor
binary_sensor:
  - platform: gpio
    pin: D7
    name: "Garage Right Motion"
    device_class: motion