esphome:
  name: garage-bluetooth-proxy
  friendly_name: Garage Bluetooth Proxy

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

# Enable logging
logger:
  level: INFO

ota:
api:

# BLE Hub
esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true

sensor:
  - platform: wifi_signal
    name: "Garage Bluetooth Proxy - WiFi Signal"
    update_interval: 60s