substitutions:
  device_name: "garage-parking-sign"
  friendly_name: Garage Parking Sign

esphome:
  name: "${device_name}"
  friendly_name: "${friendly_name}"

esp32:
  board: m5stack-atom
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

# Enable logging
logger:
  level: INFO

ota:
api:

switch:
  - platform: template
    name: "Poll Left Range Sensor"
    optimistic: true
    id: poll_left_range_sensor
  - platform: template
    name: "Poll Right Range Sensor"
    optimistic: true
    id: poll_right_range_sensor

interval:
  - interval: 100ms
    then:
      - if:
          condition:
            switch.is_on: poll_left_range_sensor
          then:
            - component.update: range_sensor_left
      - if:
          condition:
            switch.is_on: poll_right_range_sensor
          then:
            - component.update: range_sensor_right

sensor:
  - platform: wifi_signal
    name: "${friendly_name} - WiFi Signal"
    update_interval: 60s

  - platform: ultrasonic
    trigger_pin: 22 # TODO: Set pins
    echo_pin: 19
    name: "Distance - Left"
    id: range_sensor_left
    update_interval: never
    filters:
      - lambda: return round(x * 39.3701);
      - timeout: 1000ms
      # - sliding_window_moving_average:
      #     window_size: 3
      #     send_every: 3
    unit_of_measurement: "inches"
    accuracy_decimals: 0
    on_value:
      then:
        - number.set:
            id: display_number
            value: !lambda >-
              if (isnan(x)) {
                return -10;
              }
              return x;

  - platform: ultrasonic
    trigger_pin: 18 # TODO: Set pins
    echo_pin: 23
    name: "Distance - Right"
    id: range_sensor_right
    update_interval: never
    filters:
      - lambda: return round(x * 39.3701);
      - timeout: 1000ms
      # - sliding_window_moving_average:
      #     window_size: 3
      #     send_every: 3
    unit_of_measurement: "inches"
    accuracy_decimals: 0
    on_value:
      then:
        - number.set:
            id: display_number
            value: !lambda >-
              if (isnan(x)) {
                return -10;
              }
              return x;

light:
  # This is the status LED on the M5Stack.
  # - platform: esp32_rmt_led_strip
  #   rgb_order: GRB
  #   pin: 27
  #   num_leds: 1
  #   rmt_channel: 0
  #   chipset: WS2812
  #   name: "${friendly_name} - Light"
  #   id: status_led

  # One light strip snakes around the unit, covering both number displays.
  # See the `partition` entries below for breaking up the strip into segments.
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: 21 # TODO: Set pins
    num_leds: 14 # 2 digits, 7 segments, 1 LEDs per segment for now.
    rmt_channel: 0
    chipset: WS2812
    id: digit_display_light
    internal: true
    default_transition_length: 0s
    # color_correct: [25%, 25%, 25%] # Dim down all?

  # Definition of the segments:
  # 1 = top
  # 2 = right top
  # 3 = right bottom
  # 4 = bottom
  # 5 = left bottom
  # 6 = left top
  # 7 = center

  - platform: partition
    name: Digit 1 Segment 1
    id: dig_1_seg_1
    internal: true
    default_transition_length: 0s
    segments:
      - id: digit_display_light
        from: 0
        to: 0
  - platform: partition
    name: Digit 1 Segment 2
    id: dig_1_seg_2
    internal: true
    default_transition_length: 0s
    segments:
      - id: digit_display_light
        from: 1
        to: 1
  - platform: partition
    name: Digit 1 Segment 3
    id: dig_1_seg_3
    internal: true
    default_transition_length: 0s
    segments:
      - id: digit_display_light
        from: 2
        to: 2
  - platform: partition
    name: Digit 1 Segment 4
    id: dig_1_seg_4
    internal: true
    default_transition_length: 0s
    segments:
      - id: digit_display_light
        from: 3
        to: 3
  - platform: partition
    name: Digit 1 Segment 5
    id: dig_1_seg_5
    internal: true
    default_transition_length: 0s
    segments:
      - id: digit_display_light
        from: 4
        to: 4
  - platform: partition
    name: Digit 1 Segment 6
    id: dig_1_seg_6
    default_transition_length: 0s
    internal: true
    segments:
      - id: digit_display_light
        from: 5
        to: 5
  - platform: partition
    name: Digit 1 Segment 7
    id: dig_1_seg_7
    default_transition_length: 0s
    internal: true
    segments:
      - id: digit_display_light
        from: 6
        to: 6

  # Digit 2 Segments
  - platform: partition
    name: Digit 2 Segment 1
    id: dig_2_seg_1
    default_transition_length: 0s
    internal: true
    segments:
      - id: digit_display_light
        from: 7
        to: 7
  - platform: partition
    name: Digit 2 Segment 2
    id: dig_2_seg_2
    default_transition_length: 0s
    internal: true
    segments:
      - id: digit_display_light
        from: 8
        to: 8
  - platform: partition
    name: Digit 2 Segment 3
    id: dig_2_seg_3
    default_transition_length: 0s
    internal: true
    segments:
      - id: digit_display_light
        from: 9
        to: 9
  - platform: partition
    name: Digit 2 Segment 4
    id: dig_2_seg_4
    default_transition_length: 0s
    internal: true
    segments:
      - id: digit_display_light
        from: 10
        to: 10
  - platform: partition
    name: Digit 2 Segment 5
    id: dig_2_seg_5
    default_transition_length: 0s
    internal: true
    segments:
      - id: digit_display_light
        from: 11
        to: 11
  - platform: partition
    name: Digit 2 Segment 6
    id: dig_2_seg_6
    default_transition_length: 0s
    internal: true
    segments:
      - id: digit_display_light
        from: 12
        to: 12
  - platform: partition
    name: Digit 2 Segment 7
    id: dig_2_seg_7
    default_transition_length: 0s
    internal: true
    segments:
      - id: digit_display_light
        from: 13
        to: 13

number:
  - platform: template
    name: Display Number
    id: display_number
    optimistic: true
    mode: box
    min_value: -10 # -10 represents a clear display. All other numbers are displayable.
    max_value: 99
    initial_value: -10 # Start blank.
    step: 1
    on_value:
      then:
        - lambda: |-
            auto call_digit_1 = id(digit_1_value).make_call();
            auto call_digit_2 = id(digit_2_value).make_call();

            if (x == -10) {
              call_digit_1.set_value(-2);
              call_digit_2.set_value(-2);
              call_digit_1.perform();
              call_digit_2.perform();
              return; // Clear and return.
            }
            else if (x < 0) {
              // -1 represents a negative sign
              call_digit_1.set_value(-1);
            } else if (x < 10) {
              // -2 represents a blank value
              call_digit_1.set_value(-2);
            } else {
              call_digit_1.set_value(((int) x / 10) % 10);
            }

            call_digit_2.set_value(abs((int) x) % 10);

            call_digit_1.perform();
            call_digit_2.perform();


  # Map the number value to a set of segments.
  # Value meanings:
  #  -2 = blank
  #  -1 = - (minus sign)
  # 0-9 = normal values

  - platform: template
    name: Digit 1 Value
    id: digit_1_value
    optimistic: true
    mode: box
    min_value: -2
    max_value: 9
    step: 1
    on_value_range:
      - above: -2
        below: -2
        # On: none
        # Off: 1,2,3,4,5,6,7
        then:
          - light.turn_off: dig_1_seg_1
          - light.turn_off: dig_1_seg_2
          - light.turn_off: dig_1_seg_3
          - light.turn_off: dig_1_seg_4
          - light.turn_off: dig_1_seg_5
          - light.turn_off: dig_1_seg_6
          - light.turn_off: dig_1_seg_7
      - above: -1
        below: -1
        # On: 7
        # Off: 1,2,3,4,5,6
        then:
          - light.turn_off: dig_1_seg_1
          - light.turn_off: dig_1_seg_2
          - light.turn_off: dig_1_seg_3
          - light.turn_off: dig_1_seg_4
          - light.turn_off: dig_1_seg_5
          - light.turn_off: dig_1_seg_6
          - light.turn_on: dig_1_seg_7
      - above: 0
        below: 0
        # On: 1,2,3,4,5,6
        # Off: 7
        then:
          - light.turn_on: dig_1_seg_1
          - light.turn_on: dig_1_seg_2
          - light.turn_on: dig_1_seg_3
          - light.turn_on: dig_1_seg_4
          - light.turn_on: dig_1_seg_5
          - light.turn_on: dig_1_seg_6
          - light.turn_off: dig_1_seg_7
      - above: 1
        below: 1
        # On: 2,3
        # Off: 1,4,5,6,7
        then:
          - light.turn_off: dig_1_seg_1
          - light.turn_on: dig_1_seg_2
          - light.turn_on: dig_1_seg_3
          - light.turn_off: dig_1_seg_4
          - light.turn_off: dig_1_seg_5
          - light.turn_off: dig_1_seg_6
          - light.turn_off: dig_1_seg_7
      - above: 2
        below: 2
        # On: 1,2,4,5,7
        # Off: 3,6
        then:
          - light.turn_on: dig_1_seg_1
          - light.turn_on: dig_1_seg_2
          - light.turn_off: dig_1_seg_3
          - light.turn_on: dig_1_seg_4
          - light.turn_on: dig_1_seg_5
          - light.turn_off: dig_1_seg_6
          - light.turn_on: dig_1_seg_7
      - above: 3
        below: 3
        # On: 1,2,3,4,7
        # Off: 5,6
        then:
          - light.turn_on: dig_1_seg_1
          - light.turn_on: dig_1_seg_2
          - light.turn_on: dig_1_seg_3
          - light.turn_on: dig_1_seg_4
          - light.turn_off: dig_1_seg_5
          - light.turn_off: dig_1_seg_6
          - light.turn_on: dig_1_seg_7
      - above: 4
        below: 4
        # On: 2,3,6,7
        # Off: 1,4,5
        then:
          - light.turn_off: dig_1_seg_1
          - light.turn_on: dig_1_seg_2
          - light.turn_on: dig_1_seg_3
          - light.turn_off: dig_1_seg_4
          - light.turn_off: dig_1_seg_5
          - light.turn_on: dig_1_seg_6
          - light.turn_on: dig_1_seg_7
      - above: 5
        below: 5
        # On: 1,3,4,6,7
        # Off: 2,5
        then:
          - light.turn_on: dig_1_seg_1
          - light.turn_off: dig_1_seg_2
          - light.turn_on: dig_1_seg_3
          - light.turn_on: dig_1_seg_4
          - light.turn_off: dig_1_seg_5
          - light.turn_on: dig_1_seg_6
          - light.turn_on: dig_1_seg_7
      - above: 6
        below: 6
        # On: 1,3,4,5,6,7
        # Off: 2
        then:
          - light.turn_on: dig_1_seg_1
          - light.turn_off: dig_1_seg_2
          - light.turn_on: dig_1_seg_3
          - light.turn_on: dig_1_seg_4
          - light.turn_on: dig_1_seg_5
          - light.turn_on: dig_1_seg_6
          - light.turn_on: dig_1_seg_7
      - above: 7
        below: 7
        # On: 1,2,3
        # Off: 4,5,6,7
        then:
          - light.turn_on: dig_1_seg_1
          - light.turn_on: dig_1_seg_2
          - light.turn_on: dig_1_seg_3
          - light.turn_off: dig_1_seg_4
          - light.turn_off: dig_1_seg_5
          - light.turn_off: dig_1_seg_6
          - light.turn_off: dig_1_seg_7
      - above: 8
        below: 8
        # On: 1,2,3,4,5,6,7
        # Off: none
        then:
          - light.turn_on: dig_1_seg_1
          - light.turn_on: dig_1_seg_2
          - light.turn_on: dig_1_seg_3
          - light.turn_on: dig_1_seg_4
          - light.turn_on: dig_1_seg_5
          - light.turn_on: dig_1_seg_6
          - light.turn_on: dig_1_seg_7
      - above: 9
        below: 9
        # On: 1,2,3,5,6,7
        # Off: 4
        then:
          - light.turn_on: dig_1_seg_1
          - light.turn_on: dig_1_seg_2
          - light.turn_on: dig_1_seg_3
          - light.turn_off: dig_1_seg_4
          - light.turn_on: dig_1_seg_5
          - light.turn_on: dig_1_seg_6
          - light.turn_on: dig_1_seg_7

  - platform: template
    name: Digit 2 Value
    id: digit_2_value
    optimistic: true
    mode: box
    min_value: -2
    max_value: 9
    step: 1
    on_value_range:
      - above: -2
        below: -2
        # On: none
        # Off: 1,2,3,4,5,6,7
        then:
          - light.turn_off: dig_2_seg_1
          - light.turn_off: dig_2_seg_2
          - light.turn_off: dig_2_seg_3
          - light.turn_off: dig_2_seg_4
          - light.turn_off: dig_2_seg_5
          - light.turn_off: dig_2_seg_6
          - light.turn_off: dig_2_seg_7
      - above: -1
        below: -1
        # On: 7
        # Off: 1,2,3,4,5,6
        then:
          - light.turn_off: dig_2_seg_1
          - light.turn_off: dig_2_seg_2
          - light.turn_off: dig_2_seg_3
          - light.turn_off: dig_2_seg_4
          - light.turn_off: dig_2_seg_5
          - light.turn_off: dig_2_seg_6
          - light.turn_on: dig_2_seg_7
      - above: 0
        below: 0
        # On: 1,2,3,4,5,6
        # Off: 7
        then:
          - light.turn_on: dig_2_seg_1
          - light.turn_on: dig_2_seg_2
          - light.turn_on: dig_2_seg_3
          - light.turn_on: dig_2_seg_4
          - light.turn_on: dig_2_seg_5
          - light.turn_on: dig_2_seg_6
          - light.turn_off: dig_2_seg_7
      - above: 1
        below: 1
        # On: 2,3
        # Off: 1,4,5,6,7
        then:
          - light.turn_off: dig_2_seg_1
          - light.turn_on: dig_2_seg_2
          - light.turn_on: dig_2_seg_3
          - light.turn_off: dig_2_seg_4
          - light.turn_off: dig_2_seg_5
          - light.turn_off: dig_2_seg_6
          - light.turn_off: dig_2_seg_7
      - above: 2
        below: 2
        # On: 1,2,4,5,7
        # Off: 3,6
        then:
          - light.turn_on: dig_2_seg_1
          - light.turn_on: dig_2_seg_2
          - light.turn_off: dig_2_seg_3
          - light.turn_on: dig_2_seg_4
          - light.turn_on: dig_2_seg_5
          - light.turn_off: dig_2_seg_6
          - light.turn_on: dig_2_seg_7
      - above: 3
        below: 3
        # On: 1,2,3,4,7
        # Off: 5,6
        then:
          - light.turn_on: dig_2_seg_1
          - light.turn_on: dig_2_seg_2
          - light.turn_on: dig_2_seg_3
          - light.turn_on: dig_2_seg_4
          - light.turn_off: dig_2_seg_5
          - light.turn_off: dig_2_seg_6
          - light.turn_on: dig_2_seg_7
      - above: 4
        below: 4
        # On: 2,3,6,7
        # Off: 1,4,5
        then:
          - light.turn_off: dig_2_seg_1
          - light.turn_on: dig_2_seg_2
          - light.turn_on: dig_2_seg_3
          - light.turn_off: dig_2_seg_4
          - light.turn_off: dig_2_seg_5
          - light.turn_on: dig_2_seg_6
          - light.turn_on: dig_2_seg_7
      - above: 5
        below: 5
        # On: 1,3,4,6,7
        # Off: 2,5
        then:
          - light.turn_on: dig_2_seg_1
          - light.turn_off: dig_2_seg_2
          - light.turn_on: dig_2_seg_3
          - light.turn_on: dig_2_seg_4
          - light.turn_off: dig_2_seg_5
          - light.turn_on: dig_2_seg_6
          - light.turn_on: dig_2_seg_7
      - above: 6
        below: 6
        # On: 1,3,4,5,6,7
        # Off: 2
        then:
          - light.turn_on: dig_2_seg_1
          - light.turn_off: dig_2_seg_2
          - light.turn_on: dig_2_seg_3
          - light.turn_on: dig_2_seg_4
          - light.turn_on: dig_2_seg_5
          - light.turn_on: dig_2_seg_6
          - light.turn_on: dig_2_seg_7
      - above: 7
        below: 7
        # On: 1,2,3
        # Off: 4,5,6,7
        then:
          - light.turn_on: dig_2_seg_1
          - light.turn_on: dig_2_seg_2
          - light.turn_on: dig_2_seg_3
          - light.turn_off: dig_2_seg_4
          - light.turn_off: dig_2_seg_5
          - light.turn_off: dig_2_seg_6
          - light.turn_off: dig_2_seg_7
      - above: 8
        below: 8
        # On: 1,2,3,4,5,6,7
        # Off: none
        then:
          - light.turn_on: dig_2_seg_1
          - light.turn_on: dig_2_seg_2
          - light.turn_on: dig_2_seg_3
          - light.turn_on: dig_2_seg_4
          - light.turn_on: dig_2_seg_5
          - light.turn_on: dig_2_seg_6
          - light.turn_on: dig_2_seg_7
      - above: 9
        below: 9
        # On: 1,2,3,5,6,7
        # Off: 4
        then:
          - light.turn_on: dig_2_seg_1
          - light.turn_on: dig_2_seg_2
          - light.turn_on: dig_2_seg_3
          - light.turn_off: dig_2_seg_4
          - light.turn_on: dig_2_seg_5
          - light.turn_on: dig_2_seg_6
          - light.turn_on: dig_2_seg_7

binary_sensor:
  # Built-in button on the M5Stack.
  - platform: gpio
    pin:
      number: 39
      inverted: true
    name: "${friendly_name} - Button"
    on_press:
      then:
        # - light.toggle: status_led
        - number.increment: display_number
