esphome:
  name: "living-room-switch-shelly"
  friendly_name: Living Room Switch Shelly
  platform: ESP8266
  board: esp01_1m

packages:
  device_base: !include common/device_base.yaml

logger:
  level: INFO

sensor:
  - platform: wifi_signal
    name: "Living Room Shelly - WiFi Signal"
    update_interval: 60s

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO5
    name: "Living Room Switch Sensor"
    device_class: power

# switch:
#   - platform: gpio
#     pin: GPIO4
#     name: "Living Room Shelly Output"
