esphome:
  name: mini-motion-mmwave
  friendly_name: Office Mini Motion

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  level: INFO

api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

uart:
  tx_pin: 17
  rx_pin: 21
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

ld2410:

number:
  - platform: ld2410
    timeout:
      name: Timeout
    max_move_distance_gate:
      name: Max Move Distance Gate
    max_still_distance_gate:
      name: Max Still Distance Gate

switch:
  - platform: ld2410
    engineering_mode:
      name: "LD2410 Engineering Mode"
    bluetooth:
      name: "LD2410 Bluetooth"

binary_sensor:
  - platform: gpio
    pin:
      number: 16
      mode:
        input: true
        pulldown: true
    name: GPIO Presence
    device_class: presence
    on_press:
      then:
        - light.turn_on:
            id: onboard_led
            brightness: 80%
    on_release:
      then:
        - light.turn_off: onboard_led
  - platform: ld2410
    has_target:
      name: Presence
    # has_moving_target:
    #   name: Moving Target
    # has_still_target:
    #   name: Still Target

sensor:
  - platform: ld2410
    detection_distance:
      name: Detection Distance

light:
  - platform: monochromatic
    id: onboard_led
    name: Onboard LED
    default_transition_length: 0.25s
    # internal: true
    output: onboard_led_output

output:
  - id: onboard_led_output
    platform: ledc
    pin: 2