esphome:
  name: "office-switch-shelly"
  friendly_name: Office Switch Shelly
  platform: ESP8266
  board: esp01_1m

packages:
  device_base: !include common/device_base.yaml

logger:
  level: INFO

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO5
    name: "Office Switch Sensor"
    device_class: power

switch:
  - platform: gpio
    pin: GPIO4
    name: "Office Switch Output"
