esphome:
  name: office-ble-hub
  platform: ESP32
  board: esp32doit-devkit-v1

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

# Enable logging
logger:
  level: INFO

ota:
api:

# BLE Hub
esp32_ble_tracker:

sensor:
  - platform: wifi_signal
    name: "Office BLE Hub - WiFi Signal"
    update_interval: 60s

  # Basil
  - platform: xiaomi_hhccjcy01
    mac_address: 'C4:7C:8D:63:E4:1B'
    temperature:
      name: "Basil Temperature"
    moisture:
      name: "Basil Moisture"
    illuminance:
      name: "Basil Illuminance"
    conductivity:
      name: "Basil Soil Conductivity"

  # Jade
  - platform: xiaomi_hhccjcy01
    mac_address: 'C4:7C:8D:6D:94:B8'
    temperature:
      name: "Jade Temperature"
    moisture:
      name: "Jade Moisture"
    illuminance:
      name: "Jade Illuminance"
    conductivity:
      name: "Jade Soil Conductivity"

# IR Remote Transmitter for the PTZ Camera
remote_transmitter:
  pin: GPIO4
  carrier_duty_percent: 50%

switch:
  - platform: template
    name: "PTZ: Preset 0"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0xBB44
        command: 0xE21D
  - platform: template
    name: "PTZ: Preset 1"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0xBB44
        command: 0xF30C
  - platform: template
    name: "PTZ: Preset 4"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0xBB44
        command: 0xEF10
  - platform: template
    name: "PTZ: Backlight"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0xBB44
        command: 0xE817

#### Reference: Captures of the PTZ remote:
# Power: address=0xBB44, command=0xE41B
# Home: address=0xBB44, command=0xF609
# Up: address=0xBB44, command=0xFA05
# Down: address=0xBB44, command=0xF20D
# Left: address=0xBB44, command=0xF708
# Right: address=0xBB44, command=0xF50A
# Zoom In: address=0xBB44, command=0xFF00
# Zoom Out: address=0xBB44, command=0xFB04
# Preset 1: address=0xBB44, command=0xF30C
# Preset 2: address=0xBB44, command=0xEE11
# Preset 3: address=0xBB44, command=0xF10E
# Preset 4: address=0xBB44, command=0xEF10
# Preset 5: address=0xBB44, command=0xEA15
# Preset 6: address=0xBB44, command=0xED12
# Preset 7: address=0xBB44, command=0xEB14
# Preset 8: address=0xBB44, command=0xE619
# Preset 9: address=0xBB44, command=0xE916
# Preset 0: address=0xBB44, command=0xE21D
# Backlight: address=0xBB44, command=0xE817
# PTZ Reset: address=0xBB44, command=0xE31C
# Preset: address=0xBB44, command=0xF00F
