esphome:
  name: office-status-screen
  platform: ESP8266
  board: d1_mini

# Inspiration: https://esphome.io/cookbook/display_time_temp_oled.html

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

api:

# Enable logging
logger:
  level: DEBUG

ota:

time:
  - platform: homeassistant
    id: esptime

sensor:
  - platform: homeassistant
    id: inside_temperature
    entity_id: sensor.living_room_temperature
    internal: true

  - platform: homeassistant
    id: outside_temperature
    entity_id: sensor.openweathermap_temperature
    internal: true
    
  - platform: wifi_signal
    id: wifi_signal_sensor
    internal: true
    update_interval: 60s

binary_sensor:
  - platform: homeassistant
    id: meeting_active
    entity_id: binary_sensor.corban_on_a_call
    internal: true

  # When the front door is opened, display an animation for a few seconds.
  - platform: homeassistant
    id: front_door_open
    entity_id: binary_sensor.front_door
    internal: true
    on_press:
      then:
        - display.page.show: page_door
        - delay: 6s
        - display.page.show: page_main

  - platform: gpio
    pin:
      number: D3
      mode: INPUT_PULLUP
      inverted: true
    id: button_1
    internal: true
    filters:
      - delayed_off: 10ms # Small debounce
    on_press:
      then:
        - display.page.show_next: display_1

i2c:
  sda: D1
  scl: D2

font:
  - file: "resources/fonts/Georgia-Regular.ttf"
    id: georgia
    size: 20
    # Add the '<' character.
    glyphs: |-
      !"%()+,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz?<
  
  - file: "resources/fonts/Georgia-Regular.ttf"
    id: georgia_small
    size: 16
  - file: 'resources/fonts/BebasNeue-Regular.ttf'
    id: clock_font
    size: 48
  - file: 'resources/fonts/Roboto-Light.ttf'
    id: roboto_small
    size: 16

  # Bring in MDI icons.
  # Ref: https://community.home-assistant.io/t/display-materialdesign-icons-on-esphome-attached-to-screen/199790/14?u=corbanmailloux
  # Reference codepoint list: https://pictogrammers.github.io/@mdi/font/5.3.45/
  - file: 'resources/fonts/materialdesignicons-webfont.ttf'
    id: mdi_font
    size: 20
    glyphs: 
      - "\U000F0567" # mdi-video
      - "\U000F0568" # mdi-video-off

animation:
  - file: "resources/images/door_opening.gif"
    id: door_animation

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    id: display_1
    address: 0x3C
    # Pixel range: x: 0 - 127, y: 0 - 63
    pages:
      - id: page_main
        lambda: |-
          // Top message and icon
          if (id(meeting_active).has_state() && id(meeting_active).state) {
            it.printf(0, 0, id(georgia_small), TextAlign::TOP_LEFT, "In a meeting");
            it.printf(127, 0, id(mdi_font), TextAlign::TOP_RIGHT, "\U000F0567");
          } else {
            it.printf(64, 0, id(georgia_small), TextAlign::TOP_CENTER, "Hello there!");
          }

          // Print time in HH:MM format
          it.strftime(0, 60, id(clock_font), TextAlign::BASELINE_LEFT, "%I:%M", id(esptime).now());

          // Print inside temperature (from homeassistant sensor)
          if (id(inside_temperature).has_state()) {
            it.printf(127, 23, id(roboto_small), TextAlign::TOP_RIGHT , "%.1f°", id(inside_temperature).state);
          }

          // Print outside temperature (from homeassistant sensor)
          if (id(outside_temperature).has_state()) {
            it.printf(127, 60, id(roboto_small), TextAlign::BASELINE_RIGHT , "%.1f°", id(outside_temperature).state);
          }
      # This page has WiFi and button status on it.
      - id: page_debug
        lambda: |-
          it.printf(0, 0, id(georgia_small), "WiFi: %.1f dBm", id(wifi_signal_sensor).state);
          it.printf(0, 20, id(georgia_small), "Button: %s", id(button_1).state ? "ON" : "OFF");
          // it.printf(0, 40, id(georgia_small), "Button: %s", id(button_1).state ? "ON" : "OFF");
      - id: page_door
        lambda: |-
          id(door_animation).next_frame();
          it.image(32, 0, id(door_animation), COLOR_ON, COLOR_OFF);