esphome:
  name: shelly_1
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
api:
ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO5
    name: "Shelly Switch Sensor"
    device_class: power

switch:
  - platform: gpio
    pin: GPIO4
    name: "Shelly Output"
