esphome:
  name: ptz_ir_blaster
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

logger:
  level: INFO

ota:

# Empty for now, so it can be easily flashed OTA later.