esphome:
  name: ptz_ir_blaster
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

logger:
  level: INFO

ota:

remote_transmitter:
  pin: D1
  carrier_duty_percent: 50%

switch:
  - platform: template
    name: "PTZ: Preset 0"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0x22DD
        command: 0xB847
  - platform: template
    name: "PTZ: Preset 1"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0x22DD
        command: 0x30CF
  - platform: template
    name: "PTZ: Preset 4"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0x22DD
        command: 0x08F7

#### Reference: Captures of the PTZ remote:
# Power: address=0x22DD, command=0xD827
# Home: address=0x22DD, command=0x906F
# Up: address=0x22DD, command=0xA05F
# Down: address=0x22DD, command=0xB04F
# Left: address=0x22DD, command=0x10EF
# Right: address=0x22DD, command=0x50AF
# Zoom In: address=0x22DD, command=0x00FF
# Zoom Out: address=0x22DD, command=0x20DF
# Preset 1: address=0x22DD, command=0x30CF
# Preset 2: address=0x22DD, command=0x8877
# Preset 3: address=0x22DD, command=0x708F
# Preset 4: address=0x22DD, command=0x08F7
# Preset 5: address=0x22DD, command=0xA857
# Preset 6: address=0x22DD, command=0x48B7
# Preset 7: address=0x22DD, command=0x28D7
# Preset 8: address=0x22DD, command=0x9867
# Preset 9: address=0x22DD, command=0x6897
# Preset 0: address=0x22DD, command=0xB847
# Backlight: address=0x22DD, command=0xE817
# PTZ Reset: address=0x22DD, command=0x38C7
# Preset: address=0x22DD, command=0xF00F
