substitutions:
  name: ratgdo-left-garage-door
  friendly_name: RATGDO - Left Garage Door

packages:
  ratgdo.esphome: github://ratgdo/esphome-ratgdo/v2board_esp8266_d1_mini_lite.yaml@main

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

api:
  encryption:
    key: !secret api_encryption_key

# Remove the webserver and the webserver OTA path
ota:
  - platform: web_server
    id: !remove ${id_prefix}_ratgdo_ota_ws
web_server: !remove
improv_serial: !remove

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
# Minimal for OTA upgrades

# ota:
#   - platform: esphome

# esp8266:
#   board: d1_mini_lite
