substitutions:
  name: ratgdo-left-garage-door
  friendly_name: RATGDO - Left Garage Door
packages:
  ratgdo.esphome: github://esphome-ratgdo/esphome-ratgdo/v2board_esp8266_d1_mini_lite.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: !secret api_encryption_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
