esphome:
  name: screen_test
  platform: ESP8266
  board: nodemcuv2
  arduino_version: recommended

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

# Enable logging
logger:
  level: DEBUG

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: D3
      mode: INPUT_PULLUP
      inverted: true
    id: button_1
    internal: true
    filters:
      - delayed_off: 10ms # Small debounce
    on_press:
      then:
        - display.page.show_next: display_1
        - component.update: display_1

i2c:
  sda: D1
  scl: D2

font:
  - file: "fonts/Georgia-Regular.ttf"
    id: georgia
    size: 20
    glyphs: |-
      !"%()+,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz?<

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    id: display_1
    address: 0x3C
    # Pixel range: x: 0 - 127, y: 0 - 63
    pages:
      - id: page1
        lambda: |-
          it.print(0, 0, id(georgia), "Welcome! <3");
          it.print(0, 21, id(georgia), "Button:");
          it.printf(0, 42, id(georgia), "State: %s", id(button_1).state ? "ON" : "OFF");
      - id: page2
        lambda: |-
          it.print(0, 0, id(georgia), "Put me back!");
          it.filled_circle(22, 43, 20);
          it.circle(64, 43, 20);
          it.filled_circle(106, 43, 20);

# interval:
#   - interval: 5s
#     then:
#       - display.page.show_next: display_1
#       - component.update: display_1
