esphome:
  name: soundbar_controller
  platform: ESP8266
  board: d1_mini
  arduino_version: recommended

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 10.0.0.245

api:

# Enable logging
logger:
  level: INFO

ota:

remote_receiver:
  pin:
    number: D7
    inverted: True
  # dump:
  #   - nec

remote_transmitter:
  pin: D1
  carrier_duty_percent: 50%

switch:
  # Soundbar
  - platform: template
    id: sb_power
    name: "Soundbar: Power"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0x00FF
        command: 0x02FD
  - platform: template
    id: sb_vol_up
    name: "Soundbar: Volume Up"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0x00FF
        command: 0x827D
  - platform: template
    id: sb_vol_down
    name: "Soundbar: Volume Down"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0x00FF
        command: 0xA25D

binary_sensor:
  - platform: remote_receiver
    name: "Roku Remote: Play/Pause Button"
    nec:
      address: 0x57E3
      command: 0x32CD

  - platform: remote_receiver
    name: "Living Room Remote - Source"
    internal: true
    nec:
      address: 0x00FF
      command: 0x718E
    filters:
      - delayed_off: 100ms
    on_press:
      then:
        - homeassistant.event:
            event: esphome.living_room.source
  - platform: remote_receiver
    name: "Living Room Remote - Channel Up"
    internal: true
    nec:
      address: 0x00FF
      command: 0xD12E
    filters:
      - delayed_off: 100ms
    on_press:
      then:
        - homeassistant.event:
            event: esphome.living_room.channel_up
  - platform: remote_receiver
    name: "Living Room Remote - Channel Down"
    internal: true
    nec:
      address: 0x00FF
      command: 0x51AE
    filters:
      - delayed_off: 100ms
    on_press:
      then:
        - homeassistant.event:
            event: esphome.living_room.channel_down

# Source / Soundbar play/pause
# address=0x00FF, command=0x718E

# Channel up / Soudbar skip forward
# address=0x00FF, command=0xD12E

# Channel down / Soudbar skip backward
# address=0x00FF, command=0x51AE
