esphome:
  name: soundbar_controller
  platform: ESP8266
  board: d1_mini
  arduino_version: recommended

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 10.0.0.245

api:

# Enable logging
logger:
  level: INFO

ota:

remote_receiver:
  pin:
    number: D7
    inverted: True
  # dump:
  #   - nec

remote_transmitter:
  pin: D1
  carrier_duty_percent: 50%

switch:
  # Soundbar Power
  - platform: template
    name: "Soundbar"
    assumed_state: true
    icon: mdi:surround-sound
    # On this soundbar, volume down is ignored if the soundbar is off, and volume up turns it on.
    # Using this, we can build sequences that will always turn the soundbar on and off, regardless
    # of its starting state, and leave it at its initial volume level.
    turn_on_action:
      - switch.turn_on: sb_vol_down
      - delay: 200ms
      - switch.turn_on: sb_vol_up
    turn_off_action:
      # First, ensure it's on.
      - switch.turn_on: sb_vol_down
      - delay: 200ms
      - switch.turn_on: sb_vol_up
      # It takes a bit after turning on before the soundbar will turn back off.
      - delay: 1200ms
      - switch.turn_on: sb_power

  # Soundbar - Individual Commands
  - platform: template
    id: sb_power
    name: "Soundbar: Power"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0x00FF
        command: 0x02FD
  - platform: template
    id: sb_vol_up
    name: "Soundbar: Volume Up"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0x00FF
        command: 0x827D
  - platform: template
    id: sb_vol_down
    name: "Soundbar: Volume Down"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0x00FF
        command: 0xA25D

binary_sensor:
  - platform: remote_receiver
    name: "Roku Remote: Play/Pause Button"
    internal: true
    nec:
      address: 0x57E3
      command: 0x32CD
    on_press:
      then:
        - homeassistant.event:
            event: esphome.living_room.play_pause

  - platform: remote_receiver
    name: "Living Room Remote - Source"
    internal: true
    nec:
      # This is the soundbar's play/pause command.
      address: 0x00FF
      command: 0x718E
    on_press:
      then:
        - homeassistant.event:
            event: esphome.living_room.source

  - platform: remote_receiver
    name: "Living Room Remote - Channel Up"
    internal: true
    nec:
      # This is the soundbar's skip forward command.
      address: 0x00FF
      command: 0xD12E
    on_press:
      then:
        - homeassistant.event:
            event: esphome.living_room.channel_up

  - platform: remote_receiver
    name: "Living Room Remote - Channel Down"
    internal: true
    nec:
      # This is the soundbar's skip backwards command.
      address: 0x00FF
      command: 0x51AE
    on_press:
      then:
        - homeassistant.event:
            event: esphome.living_room.channel_down

#### Reference:

# Captures of the Roku remote application buttons:
# Netflix:
# Received NEC: address=0x57E3, command=0x4AB5
# Received NEC: address=0x57E3, command=0x4BB4
# Received NEC: address=0x57E3, command=0x4BB4
# Amazon:
# Received NEC: address=0x57E3, command=0xD22D
# Received NEC: address=0x57E3, command=0xD32C
# Received NEC: address=0x57E3, command=0xD32C
# Hulu:
# Received NEC: address=0x57E3, command=0xB24D
# Received NEC: address=0x57E3, command=0xB34C
# Received NEC: address=0x57E3, command=0xB34C
# YouTube:
# Received NEC: address=0x57E3, command=0x6A95
# Received NEC: address=0x57E3, command=0x6B94
# Received NEC: address=0x57E3, command=0x6B94
