esphome:
  name: soundbar_controller
  platform: ESP8266
  board: d1_mini
  arduino_version: recommended

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 10.0.0.245

# api:

mqtt:
  broker: !secret mqtt_broker_ip
  username: !secret mqtt_username_esphomelib
  password: !secret mqtt_password_esphomelib
  # discovery: clean

# Enable logging
logger:
  level: INFO

ota:

remote_receiver:
  pin:
    number: D7
    inverted: True
  # dump:
  #   - nec

remote_transmitter:
  pin: D1
  carrier_duty_percent: 50%

switch:
  # Soundbar
  - platform: template
    id: sb_power
    name: "Soundbar: Power"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0x00FF
        command: 0x02FD
  - platform: template
    id: sb_vol_up
    name: "Soundbar: Volume Up"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0x00FF
        command: 0x827D
  - platform: template
    id: sb_vol_down
    name: "Soundbar: Volume Down"
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0x00FF
        command: 0xA25D

binary_sensor:
  - platform: remote_receiver
    name: "Roku Remote: Mute Button"
    nec:
      address: 0x57E3
      command: 0x04FB
    filters:
      - delayed_off: 200ms
    on_release:
      then:
        - switch.turn_on:
            id: sb_power
  - platform: remote_receiver
    name: "Roku Remote: Volume Up Button"
    nec:
      address: 0x57E3
      command: 0xF00F
    filters:
      - delayed_off: 200ms
    on_release:
      then:
        - switch.turn_on:
            id: sb_vol_up
  - platform: remote_receiver
    name: "Roku Remote: Volume Down Button"
    nec:
      address: 0x57E3
      command: 0x08F7
    filters:
      - delayed_off: 200ms
    on_release:
      then:
        - switch.turn_on:
            id: sb_vol_down
  - platform: remote_receiver
    name: "Roku Remote: Play/Pause Button"
    nec:
      address: 0x57E3
      command: 0x32CD
