# Set the light based on the temperature


input_select:
  backlight_mode:
    name: Backlight Mode
    options:
     - Media control
     - Temperature control
     - Manual control
    icon: mdi:traffic-light


automation:
  - alias: "Set TV backlight based on temperature"
    trigger:
      - platform: state
        entity_id: sensor.living_room_thermostat_temperature
    condition:
      - condition: state
        entity_id: light.living_room_tv_backlight
        state: "on"
      - condition: state
        entity_id: input_select.backlight_mode
        state: "Temperature control"
    action:
      - service: script.set_color
        data_template:
          id: light.living_room_tv_backlight
          brightness: "{{ ((states.input_number.backlight_temp_brightness.state | int) / 100 * 255) | int }}"
          transition: 5
          colors: >-
            {% macro map(value, in_min, in_max, out_min, out_max) -%}
              {{ ((value - in_min) * (out_max - out_min) / (in_max - in_min) + out_min) }}
            {%- endmacro %}

            {% macro map_color(value, in_min, in_max, start_color, end_color) -%}
              {% if value < in_min %}
                {% set value = in_min %}
              {% endif %}
              {% if value > in_max %}
                {% set value = in_max %}
              {% endif %}

              {{- map(value, in_min, in_max, start_color[0], end_color[0]) | int -}},
              {{- map(value, in_min, in_max, start_color[1], end_color[1]) | int -}},
              {{- map(value, in_min, in_max, start_color[2], end_color[2]) | int -}}
            {%- endmacro %}

            {% macro pick_color(value) -%}
              {% set temp_low = states.input_number.temperature_low.state | int %}
              {% set temp_high = states.input_number.temperature_high.state | int %}

              {% set color_low = [0, 0, 255] %}
              {% set color_mid = [255, 255, 255] %}
              {% set color_high = [255, 0, 0] %}

              {% set temp_mid = ((temp_low + temp_high) / 2) %}
              {% if value < temp_mid %}
                {{ map_color(value, temp_low, temp_mid, color_low, color_mid) }}
              {% else %}
                {{ map_color(value, temp_mid, temp_high, color_mid, color_high) }}
              {% endif %}
            {%- endmacro %}

            {{ pick_color(states.sensor.living_room_thermostat_temperature.state | float) }}


input_number:
  temperature_low:
    name: Cold Temperature
    # initial: 64
    min: 55
    max: 80
    step: 1
  temperature_high:
    name: Hot Temperature
    # initial: 75
    min: 55
    max: 80
    step: 1
  backlight_temp_brightness:
    name: Brightness
    # initial: 100
    min: 0
    max: 100
    step: 1


script:
  set_color:
    sequence:
      - service: light.turn_on
        data_template:
          entity_id: '{{ id }}'
          rgb_color: ["{{ colors.split(',')[0]|int }}", "{{ colors.split(',')[1]|int }}", "{{ colors.split(',')[2]|int }}"]
          brightness: "{{ brightness }}"
          transition: "{{ transition }}"


homeassistant:
  customize:
    automation.set_tv_backlight_based_on_temperature:
      icon: mdi:thermometer-lines

    input_number.temperature_low:
      icon: mdi:priority-low

    input_number.temperature_high:
      icon: mdi:priority-high

    input_number.backlight_temp_brightness:
      icon: mdi:brightness-6


group:
  temperature_backlight:
    name: "Temperature-Controlled Backlight"
    control: hidden
    entities:
      - automation.set_tv_backlight_based_on_temperature
      - input_select.backlight_mode
      - input_number.temperature_low
      - input_number.temperature_high
      - input_number.backlight_temp_brightness
