light:
  - platform: group
    name: Basement Lights
    unique_id: 838fff02-b354-4132-af97-db73d769affa
    entities:
      - light.basement_laundry_light
      - light.basement_network_rack_light
      - light.basement_oil_tank_light
      - light.basement_main_lights
      - light.basement_craft_table_light
      - light.basement_storage_shelf_light
      - light.basement_furnace_light
      - light.basement_near_storage_doors_light
      - light.basement_water_softener_light

template:
  - trigger:
      - platform: state
        entity_id:
          - binary_sensor.basement_stairs_door_sensor_contact
          - binary_sensor.basement_exterior_door_sensor_contact
        from: "off"
        to: "on"
    binary_sensor:
      - name: "basement_door_just_opened"
        unique_id: 6c54c752-29c1-44e8-b9db-a07974cf70b6
        device_class: door
        auto_off:
          seconds: 1
        state: "on" # Covered by auto_off.

  - binary_sensor:
      - name: "Basement Assumed Motion"
        unique_id: 32c8a84a-35db-45b9-a8ce-f628619eec49
        device_class: occupancy
        # Only count the door sensor as motion if the lights are off. This avoids retriggering when leaving the basement.
        state: >-
          {{
            ( is_state('binary_sensor.basement_door_just_opened', 'on') and is_state('light.basement_lights', 'off')) or
            is_state('binary_sensor.laundry_motion_sensor_occupancy', 'on') or
            is_state('binary_sensor.basement_stairs_motion_sensor_occupancy', 'on')
          }}

automation:
  - id: a057b5d7-4be2-4815-ae9a-616bc0af99c0
    alias: Basement - All Lights Follow Switched Lights
    trigger:
      - platform: state
        entity_id: light.basement_main_lights
        not_from:
          - "unknown"
          - "unavailable"
    action:
      - alias: "On or Off?"
        choose:
          - conditions: >-
              {{ trigger.to_state.state == "on" }}
            sequence:
              - alias: "Turn on basement lights"
                service: light.turn_on
                data:
                  kelvin: 4000
                  brightness: 255
                target:
                  entity_id: light.basement_lights
          - conditions: >-
              {{ trigger.to_state.state == "off" }}
            sequence:
              - alias: "Turn off basement lights"
                service: light.turn_off
                data:
                  transition: 0
                target:
                  entity_id: light.basement_lights

  - id: f1227b65-0d99-4c35-9694-bc229a89f2b7
    alias: Basement - Motion Lights
    # If motion is detected within the delay, we restart the script.
    mode: restart
    trigger:
      - platform: state
        entity_id: binary_sensor.basement_assumed_motion
        from: "off"
        to: "on"
        id: "on"
      - platform: state
        entity_id: binary_sensor.basement_assumed_motion
        to: "off"
        for:
          minutes: 5
        id: "off"
    condition:
      - alias: "Basement automations are not disabled"
        condition: state
        entity_id: input_boolean.room_exclude_basement
        state: "off"
    action:
      - alias: "On or Off?"
        choose:
          - conditions: >-
              {{ trigger.id == "on" }}
            sequence:
              - alias: "Turn on basement lights"
                service: light.turn_on
                data:
                  kelvin: 4000
                  brightness: 255
                target:
                  entity_id: light.basement_lights
          - conditions: >-
              {{ trigger.id == "off" }}
            sequence:
              - alias: "Turn off basement lights"
                service: light.turn_off
                data:
                  transition: 20
                target:
                  entity_id: light.basement_lights
