# Fairy lights mounted on the headboard in the main bedroom.
# See also: packages/bedroom_light_alarm.yaml

automation:
  - alias: "Fairy Lights - Auto-Off"
    id: 4c3b7cbe-c585-4f4f-987c-db16fd814cdd
    trigger:
      - platform: state
        entity_id: light.fairy_lights
        to: "on"
        for:
          hours: 5
          minutes: 0
          seconds: 0
    action:
      - service: light.turn_off
        entity_id: light.fairy_lights
        data:
          transition: 5

  - alias: Turn on Fairy Lights at bedtime
    id: c901fb8b-1858-4533-8dae-96c5f01d15c3
    trigger:
      - platform: time
        at: "22:45"
    condition:
      - condition: state
        entity_id: light.fairy_lights
        state: "off"
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "off"
      - condition: state
        entity_id: input_boolean.home_occupied
        state: "on"
    action:
      - service: light.turn_on
        entity_id: light.fairy_lights
        data:
          transition: 5
          brightness_pct: 30

homeassistant:
  customize:
    light.fairy_lights:
      friendly_name: Fairy Lights
      icon: mdi:bed
