media_player:
  - platform: universal
    name: Bedroom TV
    children:
      - media_player.plex_bedroom_tv
      - media_player.bedroom_roku
    select_source:
      service: media_player.select_source
      data_template:
        entity_id: media_player.bedroom_roku
        source: '{{ source }}'
    attributes:
      source: media_player.bedroom_roku|source
      source_list: media_player.bedroom_roku|source_list

script:
  # Script wrappers for the Roku controls.
  bedroom_roku_play_pause:
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.bedroom_tv
          command: "play"
  bedroom_roku_back:
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.bedroom_tv
          command: "back"
  bedroom_roku_replay:
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.bedroom_tv
          command: "replay"

  start_plex_on_bedroom_tv:
    sequence:
      - service: switch.turn_on
        entity_id: switch.obama
      - service: media_player.select_source
        data:
          entity_id: media_player.bedroom_tv
          source: "Plex - Stream Free TV & Movies"

automation:
  - alias: Turn on the server when the bedroom TV switches to Plex
    trigger:
      - platform: template
        value_template: >
          {{ is_state_attr('media_player.bedroom_roku', 'source', 'Plex - Stream Free TV & Movies') }}
    condition:
      - condition: state
        entity_id: switch.obama
        state: 'off'
    action:
      - service: switch.turn_on
        entity_id: switch.obama

homeassistant:
  customize:
    script.bedroom_roku_play_pause:
      friendly_name: "Play/Pause"
      icon: mdi:play-pause
    script.bedroom_roku_replay:
      friendly_name: "Replay"
      icon: mdi:replay
    script.bedroom_roku_back:
      friendly_name: "Back"
      icon: mdi:keyboard-backspace
