# Slowly fade the bedroom lights on as an alarm.
# See also: packages/bedroom_fairy_lights.yaml

input_number:
  alarm_max_brightness:
    name: Max Brightness
    min: 0
    max: 100
    step: 1

input_datetime:
  alarm_target_time:
    name: Target Time
    has_date: false
    has_time: true
  alarm_start_time:
    name: Start Time
    has_date: false
    has_time: true

automation:
  - alias: "Sunrise Alarm"
    id: cc8e52c9-a310-4b0d-8ec1-69296230588c
    trigger:
      - platform: time
        at: input_datetime.alarm_start_time
    condition:
      - condition: state
        entity_id: input_select.home_mode
        state: "Home"
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: "on"
      - condition: state
        entity_id: light.fairy_lights
        state: "off"
    action:
      - service: light.turn_on
        entity_id: light.fairy_lights
        data_template:
          brightness: "{{ ((states.input_number.alarm_max_brightness.state | int) / 100 * 255) | int }}"
          # Get the difference in seconds of the two times
          transition: "{{ states.input_datetime.alarm_target_time.attributes.timestamp - states.input_datetime.alarm_start_time.attributes.timestamp }}"
      - delay:
          hours: 2
      - service: light.turn_off
        entity_id: light.fairy_lights
        data:
          transition: 20

homeassistant:
  customize:
    automation.sunrise_alarm:
      icon: mdi:weather-sunset
    input_number.alarm_max_brightness:
      icon: mdi:brightness-6
    input_datetime.alarm_start_time:
      icon: mdi:clock-start
    input_datetime.alarm_target_time:
      icon: mdi:clock-end
