# There are two Switchbot Curtain 3 motors installed in the Master Bedroom.

# Group the left and right curtains together
cover:
  - platform: template
    covers:
      master_bedroom_curtains:
        unique_id: 473164d6-14b5-4357-9177-678e86f29e39
        device_class: curtain
        friendly_name: "Master Bedroom Curtains"
        position_template: >-
          {% set position = (state_attr("cover.master_bedroom_curtain_left", "current_position") + state_attr("cover.master_bedroom_curtain_right", "current_position")) / 2 %}

          {% if position < 3 %}
            0
          {% else %}
            {{ position }}
          {% endif %}
        set_cover_position:
          action: v6_quietdrift.set_switchbot_curtain_position
          data:
            entity_id:
              - cover.master_bedroom_curtain_left
              - cover.master_bedroom_curtain_right
            position: "{{position}}"
            speed: 2

automation:
  - alias: "Open curtains when Corban wakes up"
    id: 49524a70-ea40-4ed6-b07f-e6bd950baef0
    trigger:
      - platform: event
        event_type: corban_iphone_sleep
        event_data:
          sleep: false
    condition:
      - alias: "Weekdays"
        condition: time
        weekday:
          - "mon"
          - "tue"
          - "wed"
          - "thu"
          - "fri"
      - alias: "Corban is home"
        condition: state
        entity_id: person.corban
        state: "home"
      - not:
          - alias: "Maggie is not home, such as every other Friday"
            condition: state
            entity_id: person.maggie
            state: "home"
      - alias: "Master Bedroom automations are not disabled"
        condition: state
        entity_id: input_boolean.room_exclude_master_bedroom
        state: "off"
      - not:
          - condition: state
            entity_id: input_select.home_mode
            state: "Vacation"
    action:
      # - service: cover.set_cover_position
      #   target:
      #     entity_id: cover.master_bedroom_curtains
      #   data:
      #     position: 30
      - action: v6_quietdrift.set_switchbot_curtain_position
        data:
          entity_id:
            - cover.master_bedroom_curtains
          position: 30
          speed: 2

  - alias: "Close curtains around sunset"
    id: 3ba2dda8-25b0-4ceb-96d2-c79fe7612603
    trigger:
      - platform: sun
        event: sunset
    condition:
      - alias: "Master Bedroom automations are not disabled"
        condition: state
        entity_id: input_boolean.room_exclude_master_bedroom
        state: "off"
      - not:
          - condition: state
            entity_id: input_select.home_mode
            state: "Vacation"
    action:
      - if:
        - condition: state
          entity_id: binary_sensor.master_bedroom_window_contact
          state: "off"
        then:
          - action: v6_quietdrift.set_switchbot_curtain_position
            data:
              entity_id:
                - cover.master_bedroom_curtain_left
                - cover.master_bedroom_curtain_right
              position: 0
              speed: 2
        else:
          # Close left, and then wait to close right once the window is closed.
          - action: v6_quietdrift.set_switchbot_curtain_position
            data:
              entity_id:
                - cover.master_bedroom_curtain_left
              position: 0
              speed: 2
          - wait_for_trigger:
              - trigger: state
                entity_id:
                  - binary_sensor.master_bedroom_window_contact
                to: "off"
                for:
                  seconds: 2
            continue_on_timeout: false
            timeout:
              hours: 8
          - action: v6_quietdrift.set_switchbot_curtain_position
            data:
              entity_id:
                - cover.master_bedroom_curtain_right
              position: 0
              speed: 2

template:
  - binary_sensor:
      - name: "Bedroom Curtains - Low Battery"
        unique_id: 31ba5362-fa29-4a9f-8eff-f7c2a166f8f2
        device_class: battery
        state: >-
          {{
            states("sensor.master_bedroom_curtain_left_battery") | int(100) < 20 or
            states("sensor.master_bedroom_curtain_right_battery") | int(100) < 20
          }}
