# LED strip mounted under the bed in the master bedroom.
# See also: esphome/bed_lighting.yaml

automation:
  - alias: "Bed Lights - Auto-Off"
    id: a873b354-e261-4790-b2b8-2b1ca8b7b558
    trigger:
      - platform: state
        entity_id: light.bed_lighting_rgb_light
        to: "on"
        for:
          hours: 5
          minutes: 0
          seconds: 0
    action:
      - service: light.turn_off
        entity_id: light.bed_lighting_rgb_light
        data:
          transition: 5

  - alias: Turn on under-bed lights at bedtime
    id: 26a2133f-97ce-463e-bc39-f23c54f57f47
    trigger:
      - platform: time
        at: "22:45"
    condition:
      - alias: "Room not excluded"
        condition: state
        entity_id: input_boolean.room_exclude_master_bedroom
        state: "off"
      - condition: state
        entity_id: light.bed_lighting_rgb_light
        state: "off"
      - condition: state
        entity_id: input_select.home_mode
        state: "Home" # Don't run if we're away or asleep.
    action:
      - service: light.turn_on
        entity_id: light.bed_lighting_rgb_light
        data:
          transition: 5
          brightness: 153
          rgb_color: [255, 78, 30]
