# There are two Switchbot Curtain 3 motors installed in the Master Bedroom.

# Use a template cover to combine them:
# cover:
#   - platform: template
#     covers:
#       master_bedroom_curtains:
#         unique_id: bb610c2a-cbea-4c95-9846-83341e2ef576
#         device_class: curtain
#         friendly_name: "Master Bedroom Curtains"
#         position_template: >-
#           {{ (state_attr("cover.master_bedroom_left_curtain", "current_position") + state_attr("cover.master_bedroom_right_curtain", "current_position")) / 2 }}
#         open_cover:
#           service: cover.open_cover
#           target:
#             entity_id:
#               - cover.master_bedroom_left_curtain
#               - cover.master_bedroom_right_curtain
#         close_cover:
#           service: cover.close_cover
#           target:
#             entity_id:
#               - cover.master_bedroom_left_curtain
#               - cover.master_bedroom_right_curtain
#         stop_cover:
#           service: cover.stop_cover
#           target:
#             entity_id:
#               - cover.master_bedroom_left_curtain
#               - cover.master_bedroom_right_curtain
#         set_cover_position:
#           service: cover.set_cover_position
#           data:
#             position: "{{position}}"
#           target:
#             entity_id:
#               - cover.master_bedroom_left_curtain
#               - cover.master_bedroom_right_curtain

automation:
  - alias: "Open curtains when Corban wakes up"
    id: 49524a70-ea40-4ed6-b07f-e6bd950baef0
    trigger:
      - platform: event
        event_type: corban_iphone_sleep
        event_data:
          sleep: false
    condition:
      - alias: "Weekdays"
        condition: time
        weekday:
          - "mon"
          - "tue"
          - "wed"
          - "thu"
          - "fri"
      - alias: "Corban is home"
        condition: state
        entity_id: person.corban
        state: "home"
      - not:
          - alias: "Maggie is not home, such as every other Friday"
            condition: state
            entity_id: person.corban
            state: "home"
      - alias: "Master Bedroom automations are not disabled"
        condition: state
        entity_id: input_boolean.room_exclude_master_bedroom
        state: "off"
      - not:
          - condition: state
            entity_id: input_select.home_mode
            state: "Vacation"
    action:
      - service: cover.set_cover_position
        target:
          entity_id: cover.master_bedroom_curtains
        data:
          position: 30

  - alias: "Close curtains around sunset"
    id: 3ba2dda8-25b0-4ceb-96d2-c79fe7612603
    trigger:
      - platform: sun
        event: sunset
    condition:
      - alias: "Master Bedroom automations are not disabled"
        condition: state
        entity_id: input_boolean.room_exclude_master_bedroom
        state: "off"
      - not:
          - condition: state
            entity_id: input_select.home_mode
            state: "Vacation"
    action:
      - service: cover.close_cover
        target:
          entity_id: cover.master_bedroom_curtains

template:
  - binary_sensor:
      - name: "Bedroom Curtains - Low Battery"
        unique_id: 31ba5362-fa29-4a9f-8eff-f7c2a166f8f2
        device_class: battery
        state: >-
          {{
            states("sensor.curtain_3_b14b_battery") | int(100) < 15 or
            states("sensor.curtain_3_41ca_battery") | int(100) < 15
          }}
