# Shelly mounted in the light switch in the bedroom. The relay controls a single outlet in the room.

automation:
  - alias: Bedroom Light Switch - Turn on lamp
    trigger:
      - platform: state
        entity_id: binary_sensor.bedroom_switch
    condition:
      - condition: state
        entity_id: light.bedroom_lamp
        state: 'off'
    action:
      - service: light.turn_on
        entity_id: light.bedroom_lamp
        data:
          brightness: 255

  - alias: Bedroom Light Switch - Turn off lamp
    trigger:
      - platform: state
        entity_id: binary_sensor.bedroom_switch
    condition:
      - condition: state
        entity_id: light.bedroom_lamp
        state: 'on'
    action:
      - service: light.turn_off
        entity_id: light.bedroom_lamp
