automation:
  - alias: Bedside Button 2 - Click - Fairy Toggle
    trigger:
      - platform: device
        domain: mqtt
        device_id: ac01e2cb060249f980958e940eb74383
        discovery_id: 0x00158d0001e8842e action_single
        type: action
        subtype: single
      # - platform: state
      #   entity_id: sensor.corban_bedside_button_click
      #   to: "single"
    action:
      # Explanation of the tri-state logic:
      # If the light is off, turn it on to 100%.
      # If it's on at 100%, set it to 25%.
      # If it's on but not at 100%, turn it off.
      - service: light.turn_on
        entity_id: light.fairy_lights
        data_template:
          brightness: >
            {%- set percent = 100 -%}
            {%- if states("light.fairy_lights") == "off" -%}
              {%- set percent = 100 -%}
            {%- elif state_attr("light.fairy_lights", "brightness") == 255 -%}
              {%- set percent = 25 -%}
            {%- else -%}
              {%- set percent = 0 -%}
            {%- endif -%}
            {{ (percent / 100 * 255) | int}}

  - alias: Bedside Button 2 - Double Click - Fan
    trigger:
      - platform: device
        domain: mqtt
        device_id: ac01e2cb060249f980958e940eb74383
        discovery_id: 0x00158d0001e8842e action_double
        type: action
        subtype: double
    action:
      - service: homeassistant.toggle
        entity_id: fan.bedroom_fan

  - alias: Bedside Button 2 - Hold - Everything Off
    trigger:
      - platform: device
        domain: mqtt
        device_id: ac01e2cb060249f980958e940eb74383
        discovery_id: 0x00158d0001e8842e action_hold
        type: action
        subtype: hold
    action:
      - service: script.turn_on
        entity_id: script.everything_off
