automation:
  - alias: Bedside Button 1 - Toggle Bedroom Light
    trigger:
      - platform: device
        device_id: 66f76df28bdd462e84227f8f164ee7c3
        discovery_id: 0x90fd9ffffe886c5f action_toggle
        domain: mqtt
        type: action
        subtype: toggle
      - platform: device
        device_id: 902fe0fc069711eb8fc8e19795714a1d
        discovery_id: 0x680ae2fffebeb7ca action_toggle
        domain: mqtt
        type: action
        subtype: toggle
    action:
      - service: light.toggle
        entity_id: light.bedroom_lamp

  - alias: Bedside Button 1 - Brightness Up
    trigger:
      - platform: device
        device_id: 66f76df28bdd462e84227f8f164ee7c3
        discovery_id: 0x90fd9ffffe886c5f action_brightness_up_click
        domain: mqtt
        type: action
        subtype: brightness_up_click
      - platform: device
        device_id: 902fe0fc069711eb8fc8e19795714a1d
        discovery_id: 0x680ae2fffebeb7ca action_brightness_up_click
        domain: mqtt
        type: action
        subtype: brightness_up_click
    action:
      - service: light.turn_on
        entity_id: light.bedroom_lamp
        data_template:
          # Handles the light being off as well, treating it as 0 brightness.
          brightness: >
            {%- set target = (is_state('light.bedroom_lamp', "on") and state_attr('light.bedroom_lamp', 'brightness')) | int + 40 -%}
            {%- if target > 255 -%}
              255
            {%- else -%}
              {{ target}}
            {%- endif -%}

  - alias: Bedside Button 1 - Brightness Down
    trigger:
      - platform: device
        device_id: 66f76df28bdd462e84227f8f164ee7c3
        discovery_id: 0x90fd9ffffe886c5f action_brightness_down_click
        domain: mqtt
        type: action
        subtype: brightness_down_click
      - platform: device
        device_id: 902fe0fc069711eb8fc8e19795714a1d
        discovery_id: 0x680ae2fffebeb7ca action_brightness_down_click
        domain: mqtt
        type: action
        subtype: brightness_down_click
    condition:
      - condition: state
        entity_id: light.bedroom_lamp
        state: "on"
    action:
      - service: light.turn_on
        entity_id: light.bedroom_lamp
        data_template:
          brightness: >
            {%- set target = state_attr('light.bedroom_lamp', 'brightness') | int - 40 -%}
            {%- if target < 10 -%}
              10
            {%- else -%}
              {{ target}}
            {%- endif -%}

  - alias: Bedside Button 1 - Brightness Up Hold
    trigger:
      - platform: device
        device_id: 66f76df28bdd462e84227f8f164ee7c3
        discovery_id: 0x90fd9ffffe886c5f action_brightness_up_hold
        domain: mqtt
        type: action
        subtype: brightness_up_hold
      - platform: device
        device_id: 902fe0fc069711eb8fc8e19795714a1d
        discovery_id: 0x680ae2fffebeb7ca action_brightness_up_hold
        domain: mqtt
        type: action
        subtype: brightness_up_hold
    action:
      - service: light.turn_on
        entity_id: light.bedroom_lamp
        data:
          brightness: 255

  - alias: Bedside Button 1 - Brightness Down Hold
    trigger:
      - platform: device
        device_id: 66f76df28bdd462e84227f8f164ee7c3
        discovery_id: 0x90fd9ffffe886c5f action_brightness_down_hold
        domain: mqtt
        type: action
        subtype: brightness_down_hold
      - platform: device
        device_id: 902fe0fc069711eb8fc8e19795714a1d
        discovery_id: 0x680ae2fffebeb7ca action_brightness_down_hold
        domain: mqtt
        type: action
        subtype: brightness_down_hold
    action:
      - service: light.turn_on
        entity_id: light.bedroom_lamp
        data:
          brightness: 10

  - alias: Bedside Button 1 - Left Button Click - Fan
    trigger:
      - platform: device
        device_id: 66f76df28bdd462e84227f8f164ee7c3
        discovery_id: 0x90fd9ffffe886c5f action_arrow_left_click
        domain: mqtt
        type: action
        subtype: arrow_left_click
      - platform: device
        device_id: 902fe0fc069711eb8fc8e19795714a1d
        discovery_id: 0x680ae2fffebeb7ca action_arrow_left_click
        domain: mqtt
        type: action
        subtype: arrow_left_click
    action:
      - service: homeassistant.toggle
        entity_id: fan.bedroom_fan

  - alias: Bedside Button 1 - Right Button Click - Fairy Toggle
    trigger:
      - platform: device
        device_id: 66f76df28bdd462e84227f8f164ee7c3
        discovery_id: 0x90fd9ffffe886c5f action_arrow_right_click
        domain: mqtt
        type: action
        subtype: arrow_right_click
      - platform: device
        device_id: 902fe0fc069711eb8fc8e19795714a1d
        discovery_id: 0x680ae2fffebeb7ca action_arrow_right_click
        domain: mqtt
        type: action
        subtype: arrow_right_click
    action:
      # Explanation of the tri-state logic:
      # If the light is off, turn it on to 100%.
      # If it's on at 100%, set it to 25%.
      # If it's on but not at 100%, turn it off.
      - service: light.turn_on
        entity_id: light.fairy_lights
        data_template:
          brightness: >
            {%- set percent = 100 -%}
            {%- if states("light.fairy_lights") == "off" -%}
              {%- set percent = 100 -%}
            {%- elif state_attr("light.fairy_lights", "brightness") == 255 -%}
              {%- set percent = 25 -%}
            {%- else -%}
              {%- set percent = 0 -%}
            {%- endif -%}
            {{ (percent / 100 * 255) | int}}
