group:
  exterior_doors:
    name: Exterior Doors
    entities:
      - binary_sensor.front_door
      - binary_sensor.garage_side_person_door_contact
      - binary_sensor.garage_back_person_door_contact
      - binary_sensor.basement_exterior_door_sensor_contact
      - binary_sensor.sunporch_sliding_door_contact

script:
  bedtime_checkup:
    alias: Bedtime Checkup
    sequence:
      - alias: "Turn everything off"
        service: script.everything_off
        continue_on_error: true
        data:
          ignore_room_exclusions: false
          include_fans: false
      - alias: "Close garage doors"
        service: cover.close_cover
        target:
          entity_id:
            - cover.ratgdo_left_garage_door_door
            - cover.ratgdo_right_garage_door_door
      - alias: "If any exterior door is open, notify"
        if:
          - alias: "Exterior door open"
            condition: state
            entity_id: group.exterior_doors
            state: "on"
        then:
          - service: script.bedtime_checkup_notify
            data:
              message: >-
                Exterior door(s) open: {{ expand("group.exterior_doors") | selectattr('state','eq','on') | map(attribute='name') | list | join(", ") }}
      - alias: "Lock side door"
        service: lock.lock
        target:
          entity_id: lock.side_door

  bedtime_checkup_notify:
    description: "Bedtime Checkup - Notify and Flash Bed Lights"
    fields:
      message:
        description: "Message for the notification"
        example: "Door open"
    sequence:
      - service: notify.corban
        data:
          title: "Bedtime Checkup Failed"
          message: "{{ message }}"
          data:
            tag: "bedtime_checkup"
            actions:
              - action: "BEDTIME_CHECKUP_TRIGGER"
                title: "Rerun Checks"
                activationMode: "background"
                authenticationRequired: false # Don't require unlocking the device
                destructive: false
                behavior: "default"
      - delay:
          seconds: 1
      - alias: "Turn on bed lights"
        service: light.turn_on
        target:
          entity_id: light.bed_lighting_rgb_light
        data:
          brightness_pct: 100
          # effect: blink
      # - delay:
      #     seconds: 1
      # - alias: "Turn on the bed lights (to help remediate the problem)"
      #   service: light.turn_on
      #   target:
      #     entity_id: light.bed_lighting_rgb_light
      #   data:
      #     brightness_pct: 100

automation:
  - alias: Bedtime Checkup - Notification Action
    id: 3335ad34-ca40-424a-ae4e-b7d4f73ed851
    trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: "BEDTIME_CHECKUP_TRIGGER"
    action:
      - alias: "Run bedtime check up"
        service: script.bedtime_checkup
