automation:
  - alias: Show Cat Claw Clipping Card - Calendar Automation
    id: 07d5496d-3810-43a3-b371-59d65c7bc10f
    mode: queued
    trigger:
      - platform: calendar
        event: start
        entity_id: calendar.chores
    condition:
      - condition: template
        value_template: "{{ 'Cat Claw Clipping' in trigger.calendar_event.summary }}"
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.cat_claw_clip_needed

input_boolean:
  cat_claw_clip_needed:
    name: Time to clip some claws!
    icon: mdi:paw

script:
  cat_claw_clipped_run_vacuum:
    alias: Clear Clipping Card and Vacuum Kitchen
    sequence:
      - alias: Hide the card on the wall display
        service: input_boolean.turn_off
        entity_id: input_boolean.cat_claw_clip_needed
      - alias: "Set vacuum mode"
        service: select.select_option
        target:
          entity_id: select.dreamebot_l10s_ultra_cleaning_mode
        data:
          option: "sweeping"
      - alias: Vacuum kitchen
        service: dreame_vacuum.vacuum_clean_segment
        target:
          entity_id: vacuum.dreamebot_l10s_ultra
        data:
          segments: 9 # Kitchen
