sensor:
  - platform: rest
    name: Cat Food Tracker - Most Recent Meal 1
    resource: !secret cat_food_tracker_url
    headers:
      API-Key: !secret cat_food_tracker_api_key
    scan_interval: 300 # 5 minutes
    value_template: >-
      {{ strptime(value_json.entries[0].submission_time, "%Y-%m-%dT%H:%M:%S%z") | as_timestamp | timestamp_custom("%-I:%M%p") }}
    json_attributes:
      - name
      - upc
    json_attributes_path: "$.entries[0].product"

  - platform: rest
    name: Cat Food Tracker - Most Recent Meal 2
    resource: !secret cat_food_tracker_url
    headers:
      API-Key: !secret cat_food_tracker_api_key
    scan_interval: 300 # 5 minutes
    value_template: >-
      {{ strptime(value_json.entries[1].submission_time, "%Y-%m-%dT%H:%M:%S%z") | as_timestamp | timestamp_custom("%-I:%M%p") }}
    json_attributes:
      - name
      - upc
    json_attributes_path: "$.entries[1].product"

rest_command:
  cat_food_log_entry:
    url: !secret cat_food_tracker_log_entry_url
    method: post
    headers:
      API-Key: !secret cat_food_tracker_api_key
    content_type: "application/json"
    payload: '{ "upc": "{{ upc }}" }'

script:
  cat_food_log_dry_food:
    alias: "Log Dry Food Entry"
    sequence:
      - service: rest_command.cat_food_log_entry
        data:
          upc: "dry-food"

automation:
  - id: dc5364e0-0b05-49dd-9e55-e357226af28b
    alias: Update Cat Food Scanner on Webhook
    trigger:
      - platform: webhook
        webhook_id: !secret cat_food_scanner_update_webhook
    action:
      - alias: Update CFT sensors
        service: homeassistant.update_entity
        data:
          entity_id:
            - sensor.cat_food_tracker_most_recent_meal_1
            - sensor.cat_food_tracker_most_recent_meal_2
      - alias: Turn on kitchen display
        service: light.turn_on
        target:
          entity_id: light.kitchen_display_screen
      - alias: Display toast on kitchen display
        service: browser_mod.toast
        data:
          deviceID: browser_mod_kitchen_display
          message: Cat food scan registered.
          duration: 10000
