input_boolean:
  cat_claw_clip_needed:
    name: Time to clip some claws!
    icon: mdi:paw

input_datetime:
  cat_claw_last_clipped:
    name: Cat Claw Clipping - Last Clipped
    has_date: true
    has_time: false

automation:
  - alias: Cat Claw Clipping - Mark Clipped
    mode: single
    id: c577630f-a024-453e-a4a4-dd3732fe7493
    trigger:
      - platform: state
        entity_id: input_boolean.cat_claw_clip_needed
        to: "off"
    action:
      - service: input_datetime.set_datetime
        target:
          entity_id: input_datetime.cat_claw_last_clipped
        data:
          datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"

  - alias: Cat Claw Clipping - Needs Clipping Reminder
    mode: single
    id: 6124cc2c-b790-4554-9b99-7bbe3488d4a2
    trigger:
      - platform: time_pattern
        hours: "/1"
    condition:
      - condition: template
        value_template: >
          {% set last = states('input_datetime.cat_claw_last_clipped') %}
          {% if last in ('unknown', 'unavailable', '') %}
            true
          {% else %}
            {{ (now() - strptime(last, '%Y-%m-%d %H:%M:%S')).days >= 7 }}
          {% endif %}
    action:
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.cat_claw_clip_needed
