automation:
  - alias: Turn on the Christmas tree in the morning # if someone is home
    trigger:
      - platform: time
        at: "06:30:00"
    condition:
      - condition: state
        entity_id: input_boolean.home_occupied
        state: "on"
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "off"
    action:
      - service: light.turn_on
        data:
          entity_id: switch.christmas_tree

homeassistant:
  customize:
    switch.christmas_tree:
      icon: mdi:pine-tree
