# Each year I end up changing what switch is used for the Christmas Tree, so
# make it configurable here.
light:
  - platform: switch
    name: Christmas Tree Lights
    entity_id: switch.christmas_tree

automation:
  # See also `package/home_away_mode.yaml`.
  - alias: Christmas lights on when getting home or waking up
    id: 515b458d-c596-434e-a356-c824bf229171
    trigger:
      - platform: state
        entity_id: input_select.home_mode
        to: "Home"
    action:
      - service: light.turn_on
        data:
          entity_id: light.christmas_tree_lights
