automation:
  - alias: Turn on the Christmas tree in the morning # if someone is home
    trigger:
      - platform: time
        at: "06:30:00"
    condition:
      - condition: state
        entity_id: input_boolean.home_occupied
        state: "on"
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "off"
    action:
      - service: light.turn_on
        data:
          entity_id: switch.christmas_tree

light:
  - platform: switch
    name: Christmas Tree
    entity_id: switch.christmas_tree
  - platform: switch
    name: TV Lamp
    entity_id: switch.living_room_lamp_near_tv
  - platform: switch
    name: Couch Lamp
    entity_id: switch.living_room_couch

homeassistant:
  customize:
    light.christmas_tree:
      icon: mdi:pine-tree