# Package for the Donut Delivery System

script:
  send_donut_and_randomize:
    sequence:
    - service: script.turn_on
      entity_id: script.send_donut
    - service: input_select.select_option
      entity_id: input_select.donut_selector
      data_template:
        option: >
          {{ states.input_select.donut_selector.attributes.options | random }}

  send_donut:
    sequence:
    - service: notify.html5
      data_template:
        target: >
          {%- if is_state("input_select.donut_destination", "Maggie") -%}
            jackie
          {%- elif is_state("input_select.donut_destination", "Corban") -%}
            ida
          {%- endif -%}
        title: "Donut Delivery!"
        message: >
          {{ states('input_select.donut_selector') }}
        data:
          icon: >
            https://corb.co/images/donuts/{{ states('input_select.donut_selector') | lower | replace(' ', '_') }}.png
          badge: https://corb.co/images/donuts/donut_icon.ico


automation:
  - alias: "Bring me a donut"
    hide_entity: true
    trigger:
      - platform: mqtt
        topic: home/espbutton
        payload: "ON"
    action: 
      - service: script.turn_on
        entity_id: script.send_donut_and_randomize


input_select:
  donut_selector:
    name: What is the next donut type?
    options:
     - Boston Creme
     - Chocolate Iced with Rainbow Sprinkles
     - Cinnamon Apple Filled
     - Cinnamon Sugar
     - Dulce De Leche
     - Glazed
     - Jelly
     - Maple Glazed
     - Powdered
     - Strawberry Iced
    icon: mdi:disk

  donut_destination:
    name: Donut Destination
    options:
      - Maggie
      - Corban
    icon: mdi:cellphone


group:
  send_me_a_donut:
    name: Donut Delivery
    entities:
      - input_select.donut_selector
      - input_select.donut_destination
      - script.send_donut_and_randomize
