automation:
  - id: 0c6fbbda-5e27-4659-9e73-556a4c18d805
    alias: Notify on Doorbell Person Detection
    trigger:
      - platform: state
        entity_id: binary_sensor.main_doorbell_person
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: timer.doorbell_person_mute_time
        state: idle
      - alias: "Privacy Mode disabled"
        condition: state
        entity_id: input_boolean.exterior_privacy_mode
        state: "off"
    action:
      - service: script.doorbell_snapshot_and_notify

  - id: cb72d982-0be9-485c-a170-2f143227268c
    alias: Doorbell - Notification Action - Refresh Image
    trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: "DOORBELL_UPDATE_SNAPSHOT"
    action:
      - service: script.doorbell_snapshot_and_notify

  - id: 4f90db44-8017-48b9-a950-f304d34b9702
    alias: Doorbell - Notification Action - Mute for one hour
    trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: "DOORBELL_PERSON_SILENCE_ONE_HOUR"
    action:
      - service: timer.start
        entity_id: timer.doorbell_person_mute_time
        data:
          duration: "01:00:00"

timer:
  doorbell_person_mute_time:

script:
  doorbell_snapshot_and_notify:
    alias: "Take Doorbell Snapshot and Notify"
    variables:
      camera: camera.main_doorbell_sub
      snapshot_create_file_path: /config/www/tmp/snapshot_{{ states[camera].object_id }}.jpg
      snapshot_access_file_path: "{{ snapshot_create_file_path | replace('/config/www','/local') }}"
    sequence:
      - service: camera.snapshot
        target:
          entity_id: "{{ camera }}"
        data:
          filename: "{{ snapshot_create_file_path }}"
      - service: notify.corban_phone_and_ipad # Previously just notify.corban
        data:
          title: "Person Detected at the Doorbell"
          message: "Hold for Image"
          data:
            # entity_id: camera.main_doorbell_sub
            image: "{{ snapshot_access_file_path }}"
            tag: "doorbell-person-detected" # Allows replacing the notification
            actions:
              - action: "URI"
                title: "Open Feed"
                uri: "/lovelace/security"
                icon: "sfsymbols:camera"
              - action: URI
                title: Open Reolink App
                uri: fb1675493782511558://
                icon: "sfsymbols:camera.viewfinder"
              - action: "DOORBELL_PERSON_SILENCE_ONE_HOUR"
                title: "Mute for an Hour"
                icon: "sfsymbols:bell.slash"
              - action: "DOORBELL_UPDATE_SNAPSHOT"
                title: "Refresh Image"
                icon: "sfsymbols:arrow.clockwise"
