script:
  everything_off:
    sequence:
      - service: homeassistant.turn_off
        entity_id: group.everything_custom
      - service: media_player.media_pause
        entity_id: media_player.spotify


homeassistant:
  customize:
    script.everything_off:
      friendly_name: "Everything"
