automation:
  - alias: "Edith - Going to Bed (Tasker)"
    trigger:
      - platform: webhook
        webhook_id: !secret edith_going_to_bed_webhook
    action:
      - service: script.turn_on
        entity_id: script.everything_off


script:
  everything_off:
    sequence:
      - service: homeassistant.turn_off
        entity_id: group.everything_custom
      - service: media_player.media_pause
        entity_id: media_player.spotify


homeassistant:
  customize:
    script.everything_off:
      friendly_name: "Everything"
