# Package for the exit sign

light:
  - platform: mqtt_json
    name: exit_sign
    state_topic: "home/exit"
    command_topic: "home/exit/set"
    brightness: true
    rgb: false
    optimistic: false
    retain: true
    qos: 0


input_select:
  exit_sign_button_action:
    name: Exit Sign Button Action
    options:
      - "Toggle Exit Sign"
      - "Toggle Party Mode"
    icon: mdi:sign-caution


automation:
  - alias: "Exit Sign Button - Toggle Exit Sign"
    hide_entity: true
    trigger:
      platform: mqtt
      topic: home/exit/button
      payload: "ON"
    condition:
    - condition: state
      entity_id: input_select.exit_sign_button_action
      state: "Toggle Exit Sign"
    action:
      service: light.toggle
      entity_id: light.exit_sign

  - alias: "Exit Sign Button - Toggle Party Mode"
    hide_entity: true
    trigger:
      platform: mqtt
      topic: home/exit/button
      payload: "ON"
    condition:
    - condition: state
      entity_id: input_select.exit_sign_button_action
      state: "Toggle Party Mode"
    action:
      service: input_boolean.toggle
      entity_id: input_boolean.party_mode

  - alias: "Turn off exit sign at 11pm"
    hide_entity: true
    trigger:
      platform: time
      at: '23:00:00'
    condition:
    - condition: state
      entity_id: light.exit_sign
      state: "on"
    action:
      service: light.turn_off
      entity_id: light.exit_sign


scene:
  - name: Exit Bright
    entities:
      light.exit_sign:
        state: on
        transition: 2
        brightness: 255
  - name: Exit Dim
    entities:
      light.exit_sign:
        state: on
        transition: 2
        brightness: 75


homeassistant:
  customize:
    light.exit_sign:
      friendly_name: Exit Sign
      icon: mdi:sign-caution
