# Package for the exit sign

automation:
  - alias: "Exit Sign Button - Toggle Exit Sign"
    trigger:
      - platform: state
        entity_id: binary_sensor.exit_sign_button
        to: "on"
    action:
      - service: light.toggle
        entity_id: light.exit_sign

homeassistant:
  customize:
    light.exit_sign:
      friendly_name: Exit Sign
      icon: mdi:sign-caution
