# For all of the exterior/landscape lighting, turn on before sunset and off in the night.

# TODO: Other things to consider:
# If we're hosting a party, we may want the lighting on later than 11pm.
# Could/should I tie the exterior lighting together to function on one switch instead of 3+?

light:
  - platform: group
    name: Exterior Lights
    unique_id: be301746-714b-4b73-9d49-e4d83e654bd8
    entities:
      - light.exterior_front_porch
      - light.exterior_garage
      - light.exterior_side_door

automation:
  - id: 7bb9e3c3-514c-4a64-9556-40dde9551500
    alias: Exterior Lighting - Lights On Before Sunset
    trigger:
      - platform: sun
        event: sunset
        offset: "-00:45:00"
    # condition:
    #   - alias: "Not in Vacation Mode"
    #     not:
    #       - condition: state
    #         entity_id: input_select.home_mode
    #         state: "Vacation"
    action:
      - alias: "Lights On"
        service: homeassistant.turn_on
        target:
          entity_id: light.exterior_lights

  - id: 4bb29781-aeaf-426e-88fa-0b4fa5d768cd
    alias: Exterior Lighting - Lights Off At Night
    trigger:
      - platform: time
        at: "23:00:00"
    # condition:
    #   - alias: "Not in Vacation Mode"
    #     not:
    #       - condition: state
    #         entity_id: input_select.home_mode
    #         state: "Vacation"
    action:
      - alias: "Lights Off"
        service: homeassistant.turn_off
        target:
          entity_id: light.exterior_lights

  - id: ed3ca607-bc60-4952-ba47-395cd6d1b8f1
    alias: Exterior Lighting - Lights On in the Morning
    trigger:
      - platform: time
        at: "06:00:00"
    condition:
      - alias: "Sunrise hasn't happened yet"
        condition: state
        entity_id: sun.sun
        state: "below_horizon"
      # - alias: "Not in Vacation Mode"
      #   not:
      #     - condition: state
      #       entity_id: input_select.home_mode
      #       state: "Vacation"
    action:
      - alias: "Lights On"
        service: homeassistant.turn_on
        target:
          entity_id: light.exterior_lights

  - id: 0222a662-5ec3-4d21-92b4-d208c1d4fee9
    alias: Exterior Lighting - Lights Off After Sunrise
    trigger:
      - platform: sun
        event: sunrise
        offset: "00:00:00"
    # condition:
    #   - alias: "Not in Vacation Mode"
    #     not:
    #       - condition: state
    #         entity_id: input_select.home_mode
    #         state: "Vacation"
    action:
      - alias: "Lights On"
        service: homeassistant.turn_off
        target:
          entity_id: light.exterior_lights
