automation:
  - id: e5c316e1-78f0-4f4b-8dac-a0140926aaf1
    alias: Garage Parking Sign - Door Triggers
    mode: restart # It's possible for both doors to be triggered. If so, use the later door.
    triggers:
      - trigger: state
        entity_id: cover.ratgdo_left_garage_door_door
        to: opening
        id: "switch.garage_parking_sign_poll_range_sensor_left"
      - trigger: state
        entity_id: cover.ratgdo_right_garage_door_door
        to: opening
        id: "switch.garage_parking_sign_poll_range_sensor_right"
    conditions:
      - alias: "Garage automations are not disabled"
        condition: state
        entity_id: input_boolean.room_exclude_garage
        state: "off"
    actions:
      - alias: Start with both sensors off
        action: switch.turn_off
        target:
          entity_id:
            - switch.garage_parking_sign_poll_range_sensor_left
            - switch.garage_parking_sign_poll_range_sensor_right
      - alias: Start polling the sensor
        action: switch.turn_on
        target:
          entity_id: >-
            {{ trigger.id }}
      - alias: "Wait for the door to be closing OR 2 minutes."
        wait_for_trigger:
          - trigger: state
            entity_id:
              - cover.ratgdo_left_garage_door_door
              - cover.ratgdo_right_garage_door_door
            to:
              - closing
              - closed
        timeout:
          minutes: 2
      - alias: Stop polling
        action: switch.turn_off
        target:
          entity_id: >-
            {{ trigger.id }}

script:
  parking_sign_clear_display:
    alias: "Clear Parking Sign Display"
    icon: mdi:monitor-off
    sequence:
      - alias: "Turn off walk and hand sign"
        action: light.turn_off
        target:
          entity_id:
            - light.garage_parking_sign_hand
            - light.garage_parking_sign_walk
      - alias: "Turn off numbers"
        action: number.set_value
        target:
          entity_id: number.garage_parking_sign_display_number
        data:
          value: -10
