automation:
  - id: 61b416af-0182-40d6-9550-dcd5f7a07d52
    alias: Restart AirCast each night
    trigger:
      - platform: time
        at: "02:00:00"
    action:
      - service: hassio.addon_restart
        data:
          addon: a0d7b954_aircast
