input_text:
  text_to_speak:
    name: Text to Speak
    initial: ""

input_select:
  text_to_speak_destination:
    name: Destination
    options:
     - All
     - Living Room
     - Bedroom
     - Bathroom
     - Kitchen
     - Office
    initial: All
    icon: mdi:text-to-speech

script:
  speak_chosen_text_on_google_home:
    sequence:
      - service: tts.google_translate_say
        data_template:
          entity_id: >-
            media_player.{{
              {
                'All': 'everything',
                'Living Room': 'living_room_speaker',
                'Bedroom': 'bedroom_speaker',
                'Bathroom': 'bathroom_speaker',
                'Kitchen': 'kitchen_speaker',
                'Office': 'office_speaker'
              }[states('input_select.text_to_speak_destination')] | default('everything')
            }}
          message: >-
            {{ states('input_text.text_to_speak') }}

  play_pause_google_homes:
    sequence:
      - service: media_player.media_play_pause
        entity_id: media_player.everything

  set_optimal_volumes_on_google_homes:
    sequence:
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.living_room_speaker
          volume_level: >-
            {{ states('input_number.gh_volume_target_living_room') | int / 100 }}
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.bedroom_speaker
          volume_level: >-
            {{ states('input_number.gh_volume_target_bedroom') | int / 100 }}
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.office_speaker
          volume_level: >-
            {{ states('input_number.gh_volume_target_office') | int / 100 }}
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.kitchen_speaker
          volume_level: >-
            {{ states('input_number.gh_volume_target_kitchen') | int / 100 }}
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.bathroom_speaker
          volume_level: >-
            {{ states('input_number.gh_volume_target_bathroom') | int / 100 }}

input_number:
  gh_volume_target_living_room:
    name: Target Living Room Speaker Volume
    min: 0
    max: 100
    unit_of_measurement: "%"
    icon: mdi:google-home
  gh_volume_target_bedroom:
    name: Target Bedroom Speaker Volume
    min: 0
    max: 100
    unit_of_measurement: "%"
    icon: mdi:google-home
  gh_volume_target_office:
    name: Target Office Speaker Volume
    min: 0
    max: 100
    unit_of_measurement: "%"
    icon: mdi:google-home
  gh_volume_target_kitchen:
    name: Target Kitchen Speaker Volume
    min: 0
    max: 100
    unit_of_measurement: "%"
    icon: mdi:google-home
  gh_volume_target_bathroom:
    name: Target Bathroom Speaker Volume
    min: 0
    max: 100
    unit_of_measurement: "%"
    icon: mdi:google-home


homeassistant:
  customize:
    script.play_pause_google_homes:
      friendly_name: "Play/Pause Homes"
      icon: mdi:play-pause
