# Guest mode is an override layer that modifies some automations. This is used when
# there is someone staying in our guest room. Search `guest_mode` in other automations for specifics.

input_boolean:
  guest_mode:
    name: Guest Mode
    icon: mdi:bag-checked

# Adding an input_text to allow loading the password from secrets into the frontend.
input_text:
  guest_wifi_password:
    initial: !secret guest_wifi_password

automation:
  - alias: Guest Mode - Enable and Disable Guest WiFi
    id: f8188dc5-e5f0-4821-ae9b-88bf14229932
    triggers:
      - trigger: state
        entity_id: input_boolean.guest_mode
    actions:
      - choose:
          - conditions: "{{ trigger.to_state.state == 'on' }}"
            sequence:
              - action: switch.turn_on
                target:
                  entity_id: switch.whatfi_guest
          - conditions: "{{ trigger.to_state.state == 'off' }}"
            sequence:
              - action: switch.turn_off
                target:
                  entity_id: switch.whatfi_guest

  - alias: Guest Mode - Add Guest Room Exclusion When Enabling
    id: 846ee07b-3953-48f7-9255-31b4a5d0cde7
    triggers:
      - trigger: state
        entity_id: input_boolean.guest_mode
        from: "off"
        to: "on"
    actions:
      - alias: "Set guest room exclusions"
        action: input_boolean.turn_on
        target:
          entity_id: input_boolean.room_exclude_guest_bedroom

  - alias: Guest Mode - Disable Room Exclusions when Unset
    id: 1567def0-c8f1-4297-a2bd-628fb03db93e
    triggers:
      - trigger: state
        entity_id: input_boolean.guest_mode
        from: "on"
        to: "off"
    actions:
      - alias: "Reset room exclusions"
        action: script.reset_room_exclusions
