# Package for the HASS Notifications

automation:
  - alias: HASS Update Notification
    trigger:
      - platform: state
        entity_id: binary_sensor.updater
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "off"
    action:
      service: notify.mobile_app_oneplus_a5000 # TODO: Extract the core stuff. Make a `notify.corban` just like `person.corban`.
      data:
        title: "Home Assistant Update"
      data_template:
        message: "Home Assistant version {{ state_attr('binary_sensor.updater', 'newest_version') }} is now available."
