# Simplify the tracking of whether or not someone is home. Device trackers have been complicated and frustrating, so let's start over with a switch.
# If no one is home and a door is opened, assume someone got home.
# Pressing the button by the door (when leaving the house) indicates that no one is home.

input_boolean:
  home_occupied:
    name: Home Occupied
    icon: mdi:home

binary_sensor:
  - platform: template
    sensors:
      home_occupied:
        friendly_name: "Home Occupied"
        device_class: occupancy
        value_template: >-
          {{ is_state('input_boolean.home_occupied', 'on') }}

automation:
  - alias: Mark home occupied when the door opens
    id: 9abcaf04-6f2a-41dc-b392-9c29d4d2b2e8
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door
        to: "on"
    condition:
      # Only count this as someone coming home if the home has been unoccupied for at least 1 minute.
      # This allows a grace period to leave, much like alarm systems.
      - condition: state
        entity_id: input_boolean.home_occupied
        state: "off"
        for:
          minutes: 1
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.home_occupied

  - alias: Mark home occupied when someone is home for a few minutes
    id: fb337c2f-3474-43db-9269-21c4658c8d27
    # This functions as a backup in case the door sensor didn't trip somehow.
    trigger:
      - platform: state
        entity_id: group.adults
        to: "home"
        for:
          minutes: 2
    # TODO: Guest mode condition
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.home_occupied

  - alias: Automatically mark the home as unoccupied if no one is home
    id: f024de99-f4dd-4d30-9aeb-cb3f0252a676
    trigger:
      - platform: state
        entity_id: group.adults
        to: "not_home"
        for:
          minutes: 3
    # TODO: Guest mode condition
    condition:
      - condition: state
        entity_id: input_boolean.home_occupied
        state: "on"
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.home_occupied

  ## Switch Actions ##

  # - alias: Living Room Switch - Press On sets the home as occupied
  #   id: e639851a-63db-4fdb-8e21-1dbb35384b36
  #   trigger:
  #     - platform: device
  #       device_id: c267d3d48bf04135851855dc4be36cbb
  #       discovery_id: 0x000d6ffffea6b202 action_on
  #       domain: mqtt
  #       type: action
  #       subtype: "on" # Up
  #   action:
  #     - service: input_boolean.turn_on
  #       data:
  #         entity_id: input_boolean.home_occupied

  # - alias: Living Room Switch - Press Off sets the home as unoccupied
  #   id: 3742c4ea-fd85-4332-9660-25d5f5b9b69a
  #   trigger:
  #     - platform: device
  #       device_id: c267d3d48bf04135851855dc4be36cbb
  #       discovery_id: 0x000d6ffffea6b202 action_off
  #       domain: mqtt
  #       type: action
  #       subtype: "off" # Down
  #   action:
  #     - service: input_boolean.turn_off
  #       data:
  #         entity_id: input_boolean.home_occupied

  # - alias: Living Room Switch - Hold On turns on movie mode
  #   id: a3c6ff1d-63d0-45b1-8d4c-48d05e31a1fe
  #   trigger:
  #     - platform: device
  #       device_id: c267d3d48bf04135851855dc4be36cbb
  #       discovery_id: 0x000d6ffffea6b202 action_brightness_move_up
  #       domain: mqtt
  #       type: action
  #       subtype: brightness_move_up
  #   action:
  #     - service: scene.turn_on
  #       entity_id: scene.movie_mode

  # - alias: Living Room Switch - Hold Off for unoccupied and light on for cats
  #   id: 9952b92c-fa1c-47d9-9ded-11e59e12c62e
  #   trigger:
  #     - platform: device
  #       device_id: c267d3d48bf04135851855dc4be36cbb
  #       discovery_id: 0x000d6ffffea6b202 action_brightness_move_down
  #       domain: mqtt
  #       type: action
  #       subtype: brightness_move_down
  #   action:
  #     - service: input_boolean.turn_off
  #       data:
  #         entity_id: input_boolean.home_occupied
  #     - delay:
  #         seconds: 5
  #     - service: light.turn_on
  #       data:
  #         brightness_pct: 30
  #       target:
  #         entity_id: light.tv_lamp

  ## Outputs/actions from Home/Away Changes ##

  # When someone gets home, play a welcome message on the Google Home Mini that is near the front door.
  # This welcome message will only play if it wouldn't be a disruption to the current occupants of the apartment.
  - alias: Welcome Home announcement when someone gets home
    id: b5c7eeb6-bd12-435f-98b3-ead8610cf95a
    trigger:
      - platform: state
        entity_id: input_boolean.home_occupied
        to: "on"
    condition:
      - condition: time # From 7AM - 9:30PM
        after: "07:00:00"
        before: "21:30:00"
    action:
      - service: script.turn_on
        entity_id: script.welcome_home_announcement

  - alias: Home Occupied - Lights, Wall Display on
    id: e2855b3b-04a7-4e28-b4d9-97091b1975fd
    trigger:
      - platform: state
        entity_id: input_boolean.home_occupied
        to: "on"
    action:
      - service: light.turn_on
        data:
          entity_id: light.tablet_wall_display_screen
      - service: light.turn_on
        data:
          entity_id: light.tv_lamp
          brightness: 255

  # TODO: Set up for new thermostat.
  # - alias: Home Occupied - Set Nest home
  #   id: 7bd1fd35-6ef1-4767-b9e1-fec037e6c186
  #   trigger:
  #     - platform: state
  #       entity_id: input_boolean.home_occupied
  #       to: "on"
  #   action:
  #     - service: nest.set_away_mode
  #       data:
  #         away_mode: home

  - alias: Home Unoccupied - Turn everything off
    id: 230957ce-f646-4c5d-8819-9b6b069d3628
    trigger:
      - platform: state
        entity_id: input_boolean.home_occupied
        to: "off"
    action:
      - service: script.turn_on
        entity_id: script.everything_off

  # TODO: Set up for new thermostat.
  # - alias: Home Unoccupied - Set Nest away
  #   id: 52a24388-93aa-40dc-b779-fcaceaf18681
  #   trigger:
  #     - platform: state
  #       entity_id: input_boolean.home_occupied
  #       to: "off"
  #   action:
  #     - service: nest.set_away_mode
  #       data:
  #         away_mode: away

script:
  welcome_home_announcement:
    sequence:
      - delay:
          seconds: 2
      - service: media_player.volume_set
        data:
          entity_id: media_player.kitchen_speaker
          volume_level: 0.6
      - service: tts.cloud_say
        entity_id: media_player.kitchen_speaker
        data_template:
          message: Welcome home!
