# Package for the HASS Notifications

alert:
  hass_update_available:
    name: HASS Update Available
    title: Home Assistant Update
    message: Home Assistant version {{ state_attr('binary_sensor.updater', 'newest_version') }} is now available.
    entity_id: binary_sensor.updater
    state: "on"
    repeat: 2880 # 2 days
    notifiers:
      - corban
    data:
      group: "hass_update"
      actions:
        - action: "SILENCE_HASS_UPDATE_ALERT"
          title: "Acknowledge Alert"
          activationMode: "background"
          authenticationRequired: true
          destructive: true
          behavior: "default"
      push:
        sound: none

automation:
  - alias: "Alert Silence - HASS Update"
    id: 872a9e5b-941c-4af4-9da8-7de156440670
    trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: "SILENCE_HASS_UPDATE_ALERT"
    condition:
      - condition: state
        entity_id: alert.hass_update_available
        state: "on"
    action:
      - service: alert.turn_off
        data:
          entity_id: alert.hass_update_available

  # Original automation, before using alerts.
  # - alias: HASS Update Notification
  #   id: 7b969ab7-f2fd-43af-8695-3e691f0ef9f0
  #   trigger:
  #     - platform: state
  #       entity_id: binary_sensor.updater
  #       from: "off"
  #       to: "on"
  #   condition:
  #     - condition: state
  #       entity_id: input_boolean.vacation_mode
  #       state: "off"
  #   action:
  #     service: notify.corban
  #     data:
  #       title: "Home Assistant Update"
  #     data_template:
  #       message: >-
  #         Home Assistant version {{ state_attr('binary_sensor.updater', 'newest_version') }} is now available.
