# Package for the HASS Notifications

automation:
  - alias: HASS Update Notification
    trigger:
      - platform: state
        entity_id: binary_sensor.updater
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "off"
    action:
      service: notify.html5_corban_phone
      data:
        title: "Home Assistant Update"
      data_template:
        message: "Home Assistant version {{ state_attr('binary_sensor.updater', 'newest_version') }} is now available."

  # Reminder to turn off the lights
  # - alias: Reminder to turn off the lights
  #   trigger:
  #     - platform: state
  #       entity_id: device_tracker.edith_wifi
  #       from: "home"
  #       to: "not_home"
  #   condition:
  #     condition: and
  #     conditions:
  #       - condition: state
  #         entity_id: "device_tracker.jackie_wifi"
  #         state: "not_home"
  #       - condition: or
  #         conditions:
  #           - condition: state
  #             entity_id: group.all_switches
  #             state: "on"
  #           - condition: state
  #             entity_id: group.all_lights
  #             state: "on"
  #   action:
  #     service: notify.html5_corban_phone
  #     data:
  #       title: "Lights are still on."
  #       message: "You seem to have left some lights on."
  #       data:
  #         actions:
  #           - action: "turn_off_lights"
  #             title: "Turn off"
  # - alias: Notification turn off lights clicked
  #   trigger:
  #     platform: event
  #     event_type: html5_notification.clicked
  #     event_data:
  #       action: turn_off_lights
  #   action:
  #     service: homeassistant.turn_off
  #     entity_id:
  #       - group.all_switches
  #       - group.all_lights

  # Ask to turn on the lights when we get home
  - alias: Corban - Ask to turn on a light when coming home
    trigger:
      - platform: state
        entity_id: device_tracker.edith_wifi
        from: "not_home"
        to: "home"
    condition:
      - condition: state
        entity_id: switch.living_room_lamp_near_tv
        state: "off"
    action:
      service: notify.html5_corban_phone
      data:
        title: "Welcome Home"
        message: "Wanna light?"
        data:
          tag: "wanna-light-edith"
          actions:
            - action: "turn_on_light_next_to_tv"
              title: "Turn on"
  - alias: Maggie - Ask to turn on a light when coming home
    initial_state: false
    trigger:
      - platform: state
        entity_id: device_tracker.jackie_wifi
        from: "not_home"
        to: "home"
    condition:
      - condition: state
        entity_id: switch.living_room_lamp_near_tv
        state: "off"
    action:
      service: notify.html5_jackie
      data:
        title: "Welcome Home"
        message: "Wanna light?"
        data:
          tag: "wanna-light-jackie"
          actions:
            - action: "turn_on_light_next_to_tv"
              title: "Turn on"
  - alias: Notification turn on light next to TV clicked
    trigger:
      platform: event
      event_type: html5_notification.clicked
      event_data:
        action: turn_on_light_next_to_tv
    action:
      service: switch.turn_on
      entity_id: switch.living_room_lamp_near_tv

group:
  hass_notifications:
    name: Home Assistant Notifications
    entities:
      - automation.hass_update_notification
      - automation.reminder_to_turn_off_the_lights
      - automation.corban_ask_to_turn_on_a_light_when_coming_home
      - automation.maggie_ask_to_turn_on_a_light_when_coming_home
      # - automation.notify_if_nest_goes_offline

homeassistant:
  customize:
    automation.hass_update_notification:
      icon: mdi:home-assistant

    automation.reminder_to_turn_off_the_lights:
      icon: mdi:lightbulb-outline

    automation.corban_ask_to_turn_on_a_light_when_coming_home:
      icon: mdi:home-map-marker
    automation.maggie_ask_to_turn_on_a_light_when_coming_home:
      icon: mdi:home-map-marker

    automation.notify_if_nest_goes_offline:
      icon: mdi:server-network
