# Home Modes
# The overall state of the home, used for modifying other automations.
# See also: https://github.com/corbanmailloux/home-assistant-configuration/issues/96

input_select:
  home_mode:
    name: Home Mode
    options:
      - Home
      - Away
      - Sleep
      - Vacation
    icon: mdi:home-circle
# Note: Guest "mode" is a separate concept because the home can be in any mode while guests are being considered.

input_boolean:
  cats_are_home:
    name: Cats Are Home
    icon: mdi:home-heart

automation:
  # See also: `bedside_button_1_corban.yaml`, which has automations for entering Sleep Mode.

  - alias: Sleep Mode - Enabled - Turn Everything Off
    id: a0fb5a75-9d4f-4bf4-a6fb-81b6bf3f8682
    trigger:
      - platform: state
        entity_id: input_select.home_mode
        to: "Sleep"
    action:
      - if:
          - alias: "Guest Mode On"
            condition: state
            entity_id: input_boolean.guest_mode
            state: "on"
        then:
          - alias: "Turn everything off except guest room"
            service: homeassistant.turn_off
            entity_id: group.everything_custom_for_guest_mode
        else:
          - alias: "Turn everything off"
            service: script.turn_on
            entity_id: script.everything_off

  - alias: Sleep Mode - Disable in Morning
    id: 60dc7343-2499-4137-bfc9-7fa7bbc50540
    trigger:
      - platform: time
        at: "06:00:00"
        # TODO: Move to a input_datetime. Share with wall display wake up time.
    condition:
      - condition: state
        entity_id: input_select.home_mode
        state: "Sleep"
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.home_mode
          option: "Home"

  - alias: Mark home occupied when the door opens
    id: 9abcaf04-6f2a-41dc-b392-9c29d4d2b2e8
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door
        to: "on"
    condition:
      # Only count this as someone coming home if the home has been unoccupied for at least 1 minute.
      # This allows a grace period to leave, much like alarm systems.
      - condition: state
        entity_id: input_select.home_mode
        state: "Away"
        for:
          minutes: 1
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.home_mode
          option: "Home"

  - alias: Mark home occupied when someone is home for a few minutes
    id: fb337c2f-3474-43db-9269-21c4658c8d27
    # This functions as a backup in case the door sensor didn't trip somehow.
    trigger:
      - platform: state
        entity_id: group.adults
        to: "home"
        for:
          minutes: 10 # 2 is good for rapid response, but this way the door switch usually covers it.
    condition:
      - condition: state
        entity_id: input_select.home_mode
        state: "Away"
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.home_mode
          option: "Home"

  - alias: Automatically mark the home as unoccupied if no one is home
    id: f024de99-f4dd-4d30-9aeb-cb3f0252a676
    trigger:
      - platform: state
        entity_id: group.adults
        to: "not_home"
        for:
          minutes: 3
    condition:
      - condition: state
        entity_id: input_select.home_mode
        state: "Home"
      - alias: "Guest Mode Off"
        condition: state
        entity_id: input_boolean.guest_mode
        state: "off"
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.home_occupied
      - service: input_select.select_option
        data:
          entity_id: input_select.home_mode
          option: "Away"

  ## Outputs/actions from Home/Away Changes ##

  # When someone gets home, play a welcome message on the Google Home Mini that is near the front door.
  # This welcome message will only play if it wouldn't be a disruption to the current occupants of the apartment.
  - alias: Welcome Home announcement when someone gets home
    id: b5c7eeb6-bd12-435f-98b3-ead8610cf95a
    trigger:
      - platform: state
        entity_id: input_select.home_mode
        to: "Home"
    condition:
      - condition: time # From 7AM - 9:30PM
        after: "07:00:00"
        before: "21:30:00"
    action:
      - service: script.turn_on
        entity_id: script.welcome_home_announcement

  - alias: Home Occupied - Lights, Wall Display on
    id: e2855b3b-04a7-4e28-b4d9-97091b1975fd
    trigger:
      - platform: state
        entity_id: input_select.home_mode
        to: "Home"
    action:
      - service: light.turn_on
        data:
          entity_id: light.tablet_wall_display_screen

  - alias: Home Unoccupied - Turn everything off
    id: 230957ce-f646-4c5d-8819-9b6b069d3628
    trigger:
      - platform: state
        entity_id: input_select.home_mode
        to:
          - "Away"
          - "Vacation"
    action:
      - service: script.turn_on
        entity_id: script.everything_off
      # Okay, so I should really rebuild this part, but...
      # If the cats are home, turn some lighting back on for them.
      - condition: state
        entity_id: input_boolean.cats_are_home
        state: "on"
      - delay:
          seconds: 3
      - service: light.turn_on
        data:
          entity_id: light.corner_lamp
          brightness: 60

script:
  welcome_home_announcement:
    sequence:
      - delay:
          seconds: 2
      - service: tts.cloud_say
        entity_id: media_player.kitchen
        data_template:
          message: Welcome home!
