# There are two zones in the house. Using the custom climate_group integration, merge them to a single entity for easier control.
# See: https://github.com/bjrnptrsn/climate_group
# Feature request for this to be native: https://community.home-assistant.io/t/climate-group-helper/465876
# PR for this to be native: https://github.com/home-assistant/core/pull/114290

climate:
  - platform: climate_group
    name: 'Home HVAC'
    temperature_unit: F
    decimal_accuracy_to_half: False  # Round the averaged temperatures to 0.5 degree increments.
    unique_id: c97027fa-0aaa-41be-a2cf-da459c724999
    entities:
      - climate.first_floor_hvac
      - climate.second_floor_hvac


## OLD STUFF BELOW


# The main thermostat is pulled in through both HomeKit and through the Honeywell Lyric cloud integration.
# Generally we use the HomeKit version for local control (climate.t9_thermostat), but that doesn't
# expose the options for setting and clearing holds. In those cases, use the cloud version (climate.hallway).

# The thermostat itself maintains the basic schedule. These automations override that schedule as needed.

# TODO: These are for the heating season only. Once the HVAC is replaced with a heat pump, update to work for both heating and cooling.

automation:
  # - alias: HVAC - Vacation Mode
  #   id: b273e1b3-cf99-45c1-bced-c9bddfd7e2cf
  #   trigger:
  #     - platform: state
  #       entity_id: input_select.home_mode
  #       to: "Vacation"
  #       id: "on"
  #     - platform: state
  #       entity_id: input_select.home_mode
  #       from: "Vacation"
  #       id: "off"
  #   condition:
  #     - alias: "Thermostat in heating mode"
  #       condition: state
  #       entity_id: climate.hallway
  #       state: "heat"
  #   action:
  #     - alias: "Vacation mode on or off?"
  #       choose:
  #         - conditions: >-
  #             {{ trigger.id == "on" }}
  #           sequence:
  #             - alias: "Wait a few seconds in case this is going from Away to Vacation"
  #               delay:
  #                 seconds: 5
  #             - alias: "Set the temperature"
  #               service: climate.set_temperature
  #               data:
  #                 temperature: 62
  #               target:
  #                 entity_id: climate.hallway
  #             - delay:
  #                 seconds: 1
  #             - alias: "Lock the temperature"
  #               service: climate.set_preset_mode
  #               data:
  #                 preset_mode: PermanentHold
  #               target:
  #                 entity_id: climate.hallway

  #         - conditions: >-
  #             {{ trigger.id == "off" }}
  #           sequence:
  #             - alias: "Reset to default schedule"
  #               service: climate.set_preset_mode
  #               data:
  #                 preset_mode: NoHold
  #               target:
  #                 entity_id: climate.hallway

  # - alias: HVAC - Reduce temperature when away
  #   id: 977e9e4a-0906-460f-9197-ccc1d866052c
  #   trigger:
  #     - platform: state
  #       entity_id: input_select.home_mode
  #       to: "Away"
  #       id: "on"
  #     - platform: state
  #       entity_id: input_select.home_mode
  #       from: "Away"
  #       id: "off"
  #   condition:
  #     - alias: "Thermostat in heating mode"
  #       condition: state
  #       entity_id: climate.hallway
  #       state: "heat"
  #   action:
  #     - alias: "Away mode on or off?"
  #       choose:
  #         - conditions: >-
  #             {{ trigger.id == "on" }}
  #           sequence:
  #             - alias: "Wait a few seconds in case this is going from Vacation to Away"
  #               delay:
  #                 seconds: 5
  #             - alias: "Set the temperature"
  #               service: climate.set_temperature
  #               data:
  #                 temperature: 64
  #               target:
  #                 entity_id: climate.hallway
  #             - delay:
  #                 seconds: 1
  #             - alias: "Lock the temperature"
  #               service: climate.set_preset_mode
  #               data:
  #                 preset_mode: PermanentHold
  #               target:
  #                 entity_id: climate.hallway

  #         - conditions: >-
  #             {{ trigger.id == "off" }}
  #           sequence:
  #             - alias: Reset to default schedule
  #               service: climate.set_preset_mode
  #               data:
  #                 preset_mode: NoHold
  #               target:
  #                 entity_id: climate.hallway

  - alias: HVAC - Notify if the internal temperature drops below 55
    id: f36d39b0-74ac-46a1-b2a0-e9b54ab17ecc
    trigger:
      - platform: template
        value_template: >-
          {{
            [
              states("sensor.bedroom_temperature") | int(100),
              states("sensor.living_room_temperature") | int(100),
              states("sensor.office_temperature") | int(100),
            ] | min < 55
          }}
    action:
      - alias: "Notify"
        service: notify.adult_phones
        data:
          title: "House is Too Cold"
          message: >-
            The internal temperature at home has dropped below 55°. Is the heat working?

  - alias: HVAC - Notify when the heat strips activate
    id: 42810f98-39f3-4f23-b3f5-c00810e9430f
    trigger:
      - platform: numeric_state
        entity_id:
          - sensor.home_energy_monitor_power_fl1_heat_strips
          - sensor.home_energy_monitor_power_fl2_heat_strips
        above: 10
    action:
      - alias: "Notify"
        service: notify.corban
        data:
          title: "Heat Strips Active"
          message: >-
            One or more of the heat strips are active.
