automation:
  - alias: iOS Event - Roku Play/Pause
    trigger:
      - platform: event
        event_type: ios.action_fired
        event_data:
          actionID: 3BB720C8-1921-4CD8-8791-7F7D08DF4637
          actionName: Play/Pause
          sourceDeviceID: corbans_iphone
    action:
      - choose:
        # If the TV's on, send play/pause.
        - conditions:
            - condition: state
              entity_id: switch.living_room_tv_power
              state: "on"
          sequence:
            - service: script.roku_play_pause
        # If the TV's off, just turn it on.
        default:
          - service: switch.turn_on
            entity_id: switch.living_room_tv_power
