# In the kitchen, there are 3 separate counter lights. I have all of them on Zigbee smart plugs to allow automation.

template:
  - trigger:
      - platform: state
        entity_id: input_select.home_mode
        from: "Away"
        to: "Home"
    binary_sensor:
      - name: "just_got_home"
        unique_id: 0e6d69ef-6fc5-4abf-a2d8-69e8395d9fbf
        auto_off:
          minutes: 2
        state: >-
          {{ is_state('input_select.home_mode', 'Home') }}
  - binary_sensor:
      - name: "Kitchen Assumed Motion"
        unique_id: 348607b5-5c4f-4a94-be3c-044370fe76f3
        device_class: occupancy
        state: >-
          {{ is_state('binary_sensor.just_got_home', 'on') or is_state('binary_sensor.kitchen_cabinet_motion_sensor_occupancy', 'on') }}

input_boolean:
  kitchen_lights_lock_on:
    name: Lock On Kitchen Lights
    icon: mdi:upload-lock

automation:
  - id: 82f4ed0d-77ed-4afc-9d63-5ea44e85a955
    alias: Kitchen Counter Lights - Toggle all based on one
    description: Use the one easily-accessible switch button to control all of the kitchen counter lights.
    trigger:
      - platform: state
        entity_id: light.kitchen_counter_light_3
    action:
      - service: >-
          {% if trigger.to_state.state == "on" %}
            light.turn_on
          {% else %}
            light.turn_off
          {% endif %}
        target:
          entity_id: light.kitchen_counter_lights
      - alias: "Reset lock lockout"
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.kitchen_lights_lock_on
    mode: single

  - id: 95a3a27b-a251-4665-8976-17ae27132e22
    alias: Kitchen Motion Lights
    # If motion is detected within the delay,
    # we restart the script.
    mode: restart
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_assumed_motion
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: input_select.home_mode
        state: "Home"
    action:
      - alias: "Time-based selection"
        choose:
          - conditions:
              - alias: "10 PM to 6 AM"
                condition: time
                after: "22:00:00"
                before: "06:00:00"
            sequence:
              - alias: "Turn on just the snack counter light"
                service: light.turn_on
                target:
                  entity_id: light.kitchen_counter_light_1
        default:
          - alias: "Turn on all counter lights"
            service: light.turn_on
            target:
              entity_id: light.kitchen_counter_lights
      - wait_for_trigger:
          platform: state
          entity_id: binary_sensor.kitchen_assumed_motion
          from: "on"
          to: "off"
      - delay:
          minutes: 10
      - alias: "Wait if the lights are locked on"
        wait_template: "{{ is_state('input_boolean.kitchen_lights_lock_on', 'off') }}"
      - alias: "Turn off one light as a warning"
        service: light.turn_off
        target:
          entity_id: light.kitchen_counter_light_1
      - delay:
          seconds: 10
      - alias: "Turn off all counter lights"
        service: light.turn_off
        target:
          entity_id: light.kitchen_counter_lights

script:
  kitchen_light_show_on_off:
    alias: "Kitchen Light Show - On/Off"
    sequence:
      - alias: "Disable kitchen light automation"
        service: automation.turn_off
        target:
          entity_id: automation.kitchen_counter_lights_toggle_all_based_on_one
      - alias: "All off"
        service: light.turn_off
        target:
          entity_id: light.kitchen_counter_lights
      - delay:
          milliseconds: 150
      - service: light.turn_on
        target:
          entity_id: light.kitchen_counter_light_1
      - delay:
          milliseconds: 150
      - service: light.turn_on
        target:
          entity_id: light.kitchen_counter_light_2
      - delay:
          milliseconds: 150
      - service: light.turn_on
        target:
          entity_id: light.kitchen_counter_light_3
      - delay:
          milliseconds: 300
      - service: light.turn_off
        target:
          entity_id: light.kitchen_counter_light_3
      - delay:
          milliseconds: 150
      - service: light.turn_off
        target:
          entity_id: light.kitchen_counter_light_2
      - delay:
          milliseconds: 150
      - service: light.turn_off
        target:
          entity_id: light.kitchen_counter_light_1
      - alias: "Enable kitchen light automation"
        service: automation.turn_on
        target:
          entity_id: automation.kitchen_counter_lights_toggle_all_based_on_one

  kitchen_light_show_round:
    alias: "Kitchen Light Show - Round"
    sequence:
      - alias: "Disable kitchen light automation"
        service: automation.turn_off
        target:
          entity_id: automation.kitchen_counter_lights_toggle_all_based_on_one
      - alias: "All off"
        service: light.turn_off
        target:
          entity_id: light.kitchen_counter_lights
      - delay:
          milliseconds: 150

      - repeat:
          count: 4
          sequence:
            - service: light.turn_on
              target:
                entity_id: light.kitchen_counter_light_1
            - service: light.turn_off
              target:
                entity_id: light.kitchen_counter_light_3
            - delay:
                milliseconds: 200
            - service: light.turn_on
              target:
                entity_id: light.kitchen_counter_light_2
            - service: light.turn_off
              target:
                entity_id: light.kitchen_counter_light_1
            - delay:
                milliseconds: 200
            - service: light.turn_on
              target:
                entity_id: light.kitchen_counter_light_3
            - service: light.turn_off
              target:
                entity_id: light.kitchen_counter_light_2
            - delay:
                milliseconds: 200

      - alias: "All off"
        service: light.turn_off
        target:
          entity_id: light.kitchen_counter_lights
      - alias: "Enable kitchen light automation"
        service: automation.turn_on
        target:
          entity_id: automation.kitchen_counter_lights_toggle_all_based_on_one
