# Notification System for our Washing Machine
# -------
# The washer is plugged into a power-monitoring smart plug (Linksio).
# It's flashed with Tasmota, and `PowerOnState 4` means that it's always on.
# Using the real-time power usage, Home Assistant can see when the washer is running.
#
# When the washer finishes, send a notification to our phones.
# Additional features:
# - Only send the “washer done” notification to people who are home.
# - If the notification should have been sent but you weren’t home, send it when you do get home.
# - Motion near the washer acknowledges and dismisses the notification automatically on all devices.
# - The notification has an action button added to acknowledge and dismiss on all devices.

# TODO/Ideas:
# - The average washer cycle here is ~58 minutes. When starting, set a countdown timer on a wall display for an estimated completion.
# - The new washer has WiFi and uses the LQ ThinQ app. Set up that integration?

template:
  - binary_sensor:
      - name: "Washing Machine Running"
        unique_id: 5b770b3c-326a-49ca-87ee-fa3de53fdeff
        device_class: running
        delay_on:
          minutes: 1
        delay_off:
          minutes: 3
        state: >-
          {{ states('sensor.washing_machine_power_draw') | float(default=0) > 10 }}
        icon: >
          {% if is_state("binary_sensor.washing_machine_running", "on") %}
            mdi:washing-machine
          {% else %}
            mdi:washing-machine-off
          {% endif %}

input_boolean:
  washer_reminder_notifying:
    name: Washer Reminder - Notifying
    icon: mdi:washing-machine

automation:
  - id: e3edfa1f-a705-4394-bedb-945151332a3c
    alias: Washer Reminder - Notify when washing machine finishes
    triggers:
      - trigger: state
        entity_id: binary_sensor.washing_machine_running
        from: "on"
        to: "off"
    actions:
      - alias: "Turn on notify switch"
        action: input_boolean.turn_on
        target:
          entity_id: input_boolean.washer_reminder_notifying

  - id: 1ede28c4-0132-418b-b526-373b02b53798
    alias: Washer Reminder - Send notifications based on boolean
    triggers:
      - trigger: state
        entity_id: input_boolean.washer_reminder_notifying
        from: "off"
        to: "on"
    actions:
      - if:
          - alias: "Is Corban home?"
            condition: state
            entity_id: person.corban
            state: "home"
        then:
          - alias: "Notify Corban"
            action: script.washer_reminder_send_notification_to_variable
            data:
              notify_device: corban
              dismiss_notification: false
      - if:
          - alias: "Is Maggie home?"
            condition: state
            entity_id: person.maggie
            state: "home"
        then:
          - alias: "Notify Maggie"
            action: script.washer_reminder_send_notification_to_variable
            data:
              notify_device: maggie
              dismiss_notification: false

  - id: 93b3840e-76d3-4cbe-a1ed-179aac220154
    alias: Washer Reminder - Dismiss notifications based on boolean
    triggers:
      - trigger: state
        entity_id: input_boolean.washer_reminder_notifying
        from: "on"
        to: "off"
    actions:
      - alias: "Clear notifications"
        action: script.washer_reminder_send_notification_to_variable
        data:
          notify_device: adult_phones
          dismiss_notification: true

  - id: beba8d5b-7898-4d1e-b796-e63b19c2bdba
    alias: Washer Reminder - Acknowledge alert when motion is detected in the basement
    triggers:
      - trigger: state
        entity_id: binary_sensor.laundry_motion_sensor_occupancy
        from: "off"
        to: "on"
    conditions:
      - alias: "Notification active"
        condition: state
        entity_id: input_boolean.washer_reminder_notifying
        state: "on"
    actions:
      - alias: "Turn off boolean"
        action: input_boolean.turn_off
        target:
          entity_id: input_boolean.washer_reminder_notifying

  - id: 19098e11-621e-4f4c-a0f4-aee3c5d8e8cf
    alias: Washer Reminder - Acknowledge alert from notification
    triggers:
      - trigger: event
        event_type: mobile_app_notification_action
        event_data:
          action: "WASHER_REMINDER_ACK"
    conditions:
      - alias: "Notification active"
        condition: state
        entity_id: input_boolean.washer_reminder_notifying
        state: "on"
    actions:
      - alias: "Turn off boolean"
        action: input_boolean.turn_off
        target:
          entity_id: input_boolean.washer_reminder_notifying

  - id: 7201114f-3317-4c7b-8488-8930f2722faf
    alias: Washer Reminder - Send delayed notification if someone gets home
    mode: parallel
    triggers:
      - trigger: state
        entity_id: person.corban
        to: "home"
        id: "corban"
      - trigger: state
        entity_id: person.maggie
        to: "home"
        id: "maggie"
    conditions:
      - alias: "Notification active"
        condition: state
        entity_id: input_boolean.washer_reminder_notifying
        state: "on"
    actions:
      - alias: "Notify the right person"
        action: script.washer_reminder_send_notification_to_variable
        data:
          notify_device: >-
            {{ trigger.id }}
          dismiss_notification: false

  - id: 9d4ec00e-140f-458e-a2ab-84ec7e45069b
    alias: Washer Reminder - Dismiss notification if someone leaves home
    mode: parallel
    triggers:
      - trigger: state
        entity_id: person.corban
        from: "home"
        id: "corban"
      - trigger: state
        entity_id: person.maggie
        from: "home"
        id: "maggie"
    conditions:
      - alias: "Notification active"
        condition: state
        entity_id: input_boolean.washer_reminder_notifying
        state: "on"
    actions:
      - alias: "Notify the right person"
        action: script.washer_reminder_send_notification_to_variable
        data:
          notify_device: >-
            {{ trigger.id }}
          dismiss_notification: true

script:
  washer_reminder_send_notification_to_variable:
    description: "Washer Reminder - Send notification to variable"
    fields:
      notify_device:
        description: "The service call to use for notification: notify.X"
        example: "corban"
      dismiss_notification:
        description: "true to dismiss the notification"
        example: "true"
    sequence:
      - if:
          - "{{ dismiss_notification == true }}"
        then:
          - action: notify.{{ notify_device }}
            data:
              message: clear_notification
              data:
                tag: "laundry_reminder_washer"
        else:
          - action: notify.{{ notify_device }}
            data:
              title: "Laundry Reminder"
              message: Washing machine done.
              data:
                tag: "laundry_reminder_washer"
                actions:
                  - action: "WASHER_REMINDER_ACK"
                    title: "Mark complete."
