# Notification System for our Clothes Dryer
# -------
# Power-monitoring-based notifications when the dryer has completed a cycle.
#
# When the dryer finishes, send a notification to our phones.
# Additional features:
# - Only send the “dryer done” notification to people who are home.
# - If the notification should have been sent but you weren’t home, send it when you do get home.
# - Motion near the dryer acknowledges and dismisses the notification automatically on all devices.
# - The notification has an action button added to acknowledge and dismiss on all devices.

template:
  - binary_sensor:
      - name: "Dryer Running"
        unique_id: 1db556f2-b73e-4127-85b1-7bbd1cff4d17
        device_class: running
        delay_on:
          minutes: 1
        delay_off:
          minutes: 1
        state: >-
          {{ states('sensor.home_energy_monitor_power_dryer') | float(default=0) > 50 }}
        icon: >
          {% if is_state("binary_sensor.dryer_running", "on") %}
            mdi:tumble-dryer
          {% else %}
            mdi:tumble-dryer-off
          {% endif %}

input_boolean:
  dryer_reminder_notifying:
    name: Dryer Reminder - Notifying
    icon: mdi:tumble-dryer

automation:
  - id: 3d45c62b-c99a-43cb-a1b7-7e5ab2974a1b
    alias: Dryer Reminder - Notify when dryer finishes
    trigger:
      - platform: state
        entity_id: binary_sensor.dryer_running
        from: "on"
        to: "off"
    action:
      - alias: "Turn on notify switch"
        service: input_boolean.turn_on
        target:
          entity_id: input_boolean.dryer_reminder_notifying

  - id: b7826c90-2dc8-40fb-9abb-a21e5678a23d
    alias: Dryer Reminder - Send notifications based on boolean
    trigger:
      - platform: state
        entity_id: input_boolean.dryer_reminder_notifying
        from: "off"
        to: "on"
    action:
      - if:
          - alias: "Is Corban home?"
            condition: state
            entity_id: person.corban
            state: "home"
        then:
          - alias: "Notify Corban"
            service: script.dryer_reminder_send_notification_to_variable
            data:
              notify_device: corban
              dismiss_notification: false
      - if:
          - alias: "Is Maggie home?"
            condition: state
            entity_id: person.maggie
            state: "home"
        then:
          - alias: "Notify Maggie"
            service: script.dryer_reminder_send_notification_to_variable
            data:
              notify_device: maggie
              dismiss_notification: false

  - id: 081bf63f-8413-4dea-be82-d537dd2e1a20
    alias: Dryer Reminder - Dismiss notifications based on boolean
    trigger:
      - platform: state
        entity_id: input_boolean.dryer_reminder_notifying
        from: "on"
        to: "off"
    action:
      - alias: "Clear notifications"
        service: script.dryer_reminder_send_notification_to_variable
        data:
          notify_device: adult_phones
          dismiss_notification: true

  - id: 3b991b80-fc3f-4d67-9900-5cf5f6510c96
    alias: Dryer Reminder - Acknowledge alert when motion is detected in the basement
    trigger:
      - platform: state
        entity_id: binary_sensor.laundry_motion_sensor_occupancy
        from: "off"
        to: "on"
    condition:
      - alias: "Notification active"
        condition: state
        entity_id: input_boolean.dryer_reminder_notifying
        state: "on"
    action:
      - alias: "Turn off boolean"
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.dryer_reminder_notifying

  - id: 551dc831-c06e-4af2-843f-6654fb049661
    alias: Dryer Reminder - Acknowledge alert from notification
    trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: "DRYER_REMINDER_ACK"
    condition:
      - alias: "Notification active"
        condition: state
        entity_id: input_boolean.dryer_reminder_notifying
        state: "on"
    action:
      - alias: "Turn off boolean"
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.dryer_reminder_notifying

  - id: b8d28099-0cb5-4290-82ef-90dbeb9717a9
    alias: Dryer Reminder - Send delayed notification if someone gets home
    mode: parallel
    trigger:
      - platform: state
        entity_id: person.corban
        to: "home"
        id: "corban"
      - platform: state
        entity_id: person.maggie
        to: "home"
        id: "maggie"
    condition:
      - alias: "Notification active"
        condition: state
        entity_id: input_boolean.dryer_reminder_notifying
        state: "on"
    action:
      - alias: "Notify the right person"
        service: script.dryer_reminder_send_notification_to_variable
        data:
          notify_device: >-
            {{ trigger.id }}
          dismiss_notification: false

  - id: 3f6458fd-c731-47ff-a825-fec4f7591fd1
    alias: Dryer Reminder - Dismiss notification if someone leaves home
    mode: parallel
    trigger:
      - platform: state
        entity_id: person.corban
        from: "home"
        id: "corban"
      - platform: state
        entity_id: person.maggie
        from: "home"
        id: "maggie"
    condition:
      - alias: "Notification active"
        condition: state
        entity_id: input_boolean.dryer_reminder_notifying
        state: "on"
    action:
      - alias: "Notify the right person"
        service: script.dryer_reminder_send_notification_to_variable
        data:
          notify_device: >-
            {{ trigger.id }}
          dismiss_notification: true

script:
  dryer_reminder_send_notification_to_variable:
    description: "Dryer Reminder - Send notification to variable"
    fields:
      notify_device:
        description: "The service call to use for notification: notify.X"
        example: "corban"
      dismiss_notification:
        description: "true to dismiss the notification"
        example: "true"
    sequence:
      - if:
          - "{{ dismiss_notification == true }}"
        then:
          - service: notify.{{ notify_device }}
            data:
              message: clear_notification
              data:
                tag: "laundry_reminder_dryer"
        else:
          - service: notify.{{ notify_device }}
            data:
              title: "Laundry Reminder"
              message: Dryer done.
              data:
                tag: "laundry_reminder_dryer"
                actions:
                  - action: "DRYER_REMINDER_ACK"
                    title: "Mark complete."
