# Basic timer-based reminder for the dryer.
# I tried to use a vibration sensor initially, but it wasn't sensitive enough.
# Someday I'll either add power monitoring with a CT clamp or mount something permanent.

# See `laundry_washer_reminder.yaml` for a breakdown of the notification system.
# The difference here is that a button mounted on the dryer starts a timer, and
# we assume the dryer is done when the timer ends.

timer:
  dryer_running_countdown:
    name: "Dryer Reminder - Countdown timer"
    restore: true
    duration: "00:55:00"

input_boolean:
  dryer_reminder_notifying:
    name: Dryer Reminder - Notifying
    icon: mdi:tumble-dryer

automation:
  - id: 5c175757-2e3e-4eca-b43f-3a5930c43995
    alias: Dryer Reminder - Notify when washing machine finishes
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.dryer_running_countdown
    action:
      - alias: "Turn on notify switch"
        service: input_boolean.turn_on
        target:
          entity_id: input_boolean.dryer_reminder_notifying

  - id: 9c7f5b99-d046-43fc-bb0b-103574f3a0d7
    alias: Dryer Reminder - Send notifications based on boolean
    trigger:
      - platform: state
        entity_id: input_boolean.dryer_reminder_notifying
        from: "off"
        to: "on"
    action:
      - if:
          - alias: "Is Corban home?"
            condition: state
            entity_id: person.corban
            state: "home"
        then:
          - alias: "Notify Corban"
            service: script.dryer_reminder_send_notification_to_variable
            data:
              notify_device: corban
              dismiss_notification: false
      - if:
          - alias: "Is Maggie home?"
            condition: state
            entity_id: person.maggie
            state: "home"
        then:
          - alias: "Notify Maggie"
            service: script.dryer_reminder_send_notification_to_variable
            data:
              notify_device: maggie
              dismiss_notification: false

  - id: db2573e7-c7fc-4c42-aeb1-4da74c7e2eee
    alias: Dryer Reminder - Dismiss notifications based on boolean
    trigger:
      - platform: state
        entity_id: input_boolean.dryer_reminder_notifying
        from: "on"
        to: "off"
    action:
      - alias: "Clear notifications"
        service: script.dryer_reminder_send_notification_to_variable
        data:
          notify_device: adult_phones
          dismiss_notification: true

  - id: ce5f31c2-2c20-4de4-96a6-4f61998e1dbe
    alias: Dryer Reminder - Acknowledge alert when opening the laundry room door
    trigger:
      - platform: state
        entity_id: binary_sensor.laundry_room_door_sensor_contact
        from: "off"
        to: "on"
        for:
          seconds: 3
    condition:
      - alias: "Notification active"
        condition: state
        entity_id: input_boolean.dryer_reminder_notifying
        state: "on"
    action:
      - alias: "Turn off boolean"
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.dryer_reminder_notifying

  - id: 97e081a6-90f1-4a23-a0a5-44c3abb47e8e
    alias: Dryer Reminder - Acknowledge alert from notification
    trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: "DRYER_REMINDER_ACK"
    condition:
      - alias: "Notification active"
        condition: state
        entity_id: input_boolean.dryer_reminder_notifying
        state: "on"
    action:
      - alias: "Turn off boolean"
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.dryer_reminder_notifying

  - id: 2bf1c5fb-e527-41d1-83d1-73ab9e5fd2ce
    alias: Dryer Reminder - Send delayed notification if someone gets home
    mode: parallel
    trigger:
      - platform: state
        entity_id: person.corban
        to: "home"
        id: "corban"
      - platform: state
        entity_id: person.maggie
        to: "home"
        id: "maggie"
    condition:
      - alias: "Notification active"
        condition: state
        entity_id: input_boolean.dryer_reminder_notifying
        state: "on"
    action:
      - alias: "Notify the right person"
        service: script.dryer_reminder_send_notification_to_variable
        data:
          notify_device: >-
            {{ trigger.id }}
          dismiss_notification: false

  - id: 0b858b2c-5dc1-4c52-9040-514f42e62e61
    alias: Dryer Reminder - Dismiss notification if someone leaves home
    mode: parallel
    trigger:
      - platform: state
        entity_id: person.corban
        from: "home"
        id: "corban"
      - platform: state
        entity_id: person.maggie
        from: "home"
        id: "maggie"
    condition:
      - alias: "Notification active"
        condition: state
        entity_id: input_boolean.dryer_reminder_notifying
        state: "on"
    action:
      - alias: "Notify the right person"
        service: script.dryer_reminder_send_notification_to_variable
        data:
          notify_device: >-
            {{ trigger.id }}
          dismiss_notification: true

  ### Button Actions

  - alias: Laundry Room Button - Click - Start/Restart Timer
    id: 78184c4f-0f36-4d2c-9316-412a274deef1
    trigger:
      - platform: device
        domain: mqtt
        device_id: 24d7573f0424b71156560a74fede5da7
        discovery_id: 0x00158d00027bee0b action_single
        type: action
        subtype: single
    action:
      - service: timer.start
        target:
          entity_id: timer.dryer_running_countdown

  - alias: Laundry Room Button - Hold - Stop Timer
    id: e4b0b2cd-237c-4584-bf69-3b135e59faff
    trigger:
      - platform: device
        domain: mqtt
        device_id: 24d7573f0424b71156560a74fede5da7
        type: action
        subtype: hold
        discovery_id: 0x00158d00027bee0b action_hold
    action:
      - service: timer.cancel
        target:
          entity_id: timer.dryer_running_countdown

  - alias: Laundry Room Button - Double Click - Toggle Light
    id: 71b7cd78-cca2-4546-9214-556897241e9e
    trigger:
      - platform: device
        domain: mqtt
        device_id: 24d7573f0424b71156560a74fede5da7
        type: action
        subtype: double
        discovery_id: 0x00158d00027bee0b action_double
    action:
      - service: light.toggle
        target:
          entity_id: light.laundry_room_light

script:
  dryer_reminder_send_notification_to_variable:
    description: "Dryer Reminder - Send notification to variable"
    fields:
      notify_device:
        description: "The service call to use for notification: notify.X"
        example: "corban"
      dismiss_notification:
        description: "true to dismiss the notification"
        example: "true"
    sequence:
      - if:
          - "{{ dismiss_notification == true }}"
        then:
          - service: notify.{{ notify_device }}
            data:
              message: clear_notification
              data:
                tag: "laundry_reminder_dryer"
        else:
          - service: notify.{{ notify_device }}
            data:
              title: "Laundry Reminder"
              message: Dryer done.
              data:
                tag: "laundry_reminder_dryer"
                actions:
                  - action: "DRYER_REMINDER_ACK"
                    title: "Mark complete."
