automation:
  - id: c2218b90-acab-421c-aab2-b958efd3ba27
    alias: Set Laundry Room Light Based on Door
    trigger:
      - platform: state
        entity_id: binary_sensor.laundry_room_door_sensor_contact
    action:
      - service: >-
          {% if trigger.to_state.state == "on" %}
            light.turn_off
          {% else %}
            light.turn_on
          {% endif %}
        target:
          entity_id: light.laundry_room_light
