automation:
  ## Button Actions

  - id: 34a158cc-aa49-4aeb-9426-705f3a98bd85
    alias: Upstairs Light Switch - Config Single Press - Toggle Under Bed Lighting
    trigger:
      - platform: device
        domain: mqtt
        device_id: 6239543fc9a684fbba5d4af77ccdf052
        type: action
        subtype: config_single
    action:
      - service: light.toggle
        data:
          brightness_pct: 100
          rgb_color:
            - 255
            - 78
            - 30
        target:
          entity_id: light.bed_lighting_rgb_light

  - id: f65fe143-e99c-4bb8-b131-295e121d2240
    alias: Upstairs Light Switch - Config Double Press - Toggle Fairy Lights
    trigger:
      - platform: device
        domain: mqtt
        device_id: 6239543fc9a684fbba5d4af77ccdf052
        type: action
        subtype: config_double
    action:
      - service: light.toggle
        target:
          entity_id: light.fairy_lights
        data:
          brightness_pct: 100

  ## Light Strip Controls

  - id: a8f98277-f3cf-4a9d-a2a2-9cdfbd2196ff
    alias: Litter Box Status - Set Input Select
    mode: restart
    trigger:
      - platform: state
        entity_id: vacuum.litter_robot_4_litter_box
      - platform: state
        entity_id: sensor.litter_robot_4_litter_level
      - platform: state
        entity_id: sensor.litter_robot_4_waste_drawer
    action:
      - choose:
          - conditions:
              - alias: "Litter Box Cycling"
                condition: state
                entity_id: vacuum.litter_robot_4_litter_box
                state: "cleaning"
            sequence:
              - service: input_select.select_option
                target:
                  entity_id: input_select.upstairs_hall_light_switch_led_mode
                data:
                  option: "Litter Box Cycling"
          - conditions:
              - alias: "Litter Drawer Full"
                condition: numeric_state
                entity_id: sensor.litter_robot_4_waste_drawer
                above: 89
            sequence:
              - service: input_select.select_option
                target:
                  entity_id: input_select.upstairs_hall_light_switch_led_mode
                data:
                  option: "Off"
              - delay:
                  seconds: 1
              - service: input_select.select_option
                target:
                  entity_id: input_select.upstairs_hall_light_switch_led_mode
                data:
                  option: "Litter Drawer Full"
          - conditions:
              - alias: "Litter Drawer Almost Full"
                condition: numeric_state
                entity_id: sensor.litter_robot_4_waste_drawer
                above: 80
            sequence:
              - service: input_select.select_option
                target:
                  entity_id: input_select.upstairs_hall_light_switch_led_mode
                data:
                  option: "Off"
              - delay:
                  seconds: 1
              - service: input_select.select_option
                target:
                  entity_id: input_select.upstairs_hall_light_switch_led_mode
                data:
                  option: "Litter Drawer Almost Full"
          - conditions:
              - alias: "Litter Level Low"
                condition: numeric_state
                entity_id: sensor.litter_robot_4_litter_level
                below: 40
            sequence:
              - service: input_select.select_option
                target:
                  entity_id: input_select.upstairs_hall_light_switch_led_mode
                data:
                  option: "Off"
              - delay:
                  seconds: 1
              - service: input_select.select_option
                target:
                  entity_id: input_select.upstairs_hall_light_switch_led_mode
                data:
                  option: "Litter Level Low"
        default:
          - service: input_select.select_option
            target:
              entity_id: input_select.upstairs_hall_light_switch_led_mode
            data:
              option: "Off"

  - id: 8efcc481-cdef-4943-b443-93860546c935
    alias: Upstairs Hall Light Switch - Set LEDs Based on Input Select
    mode: queued
    trigger:
      - platform: state
        entity_id: input_select.upstairs_hall_light_switch_led_mode
    action:
      - choose:
          - conditions: >-
              {{ trigger.to_state.state == "Off" }}
            sequence:
              - service: script.inovelli_led_control
                metadata: {}
                data:
                  led: All
                  color: Cyan
                  level: 43
                  effect: Clear
                  duration: Indefinitely
                  target:
                    device_id: 6239543fc9a684fbba5d4af77ccdf052
              - service: script.inovelli_led_control
                metadata: {}
                data:
                  led: Led 1
                  color: Cyan
                  level: 43
                  effect: Clear
                  duration: Indefinitely
                  target:
                    device_id: 6239543fc9a684fbba5d4af77ccdf052
              - service: script.inovelli_led_control
                metadata: {}
                data:
                  led: Led 2
                  color: Cyan
                  level: 43
                  effect: Clear
                  duration: Indefinitely
                  target:
                    device_id: 6239543fc9a684fbba5d4af77ccdf052
              - service: script.inovelli_led_control
                metadata: {}
                data:
                  led: Led 3
                  color: Cyan
                  level: 43
                  effect: Clear
                  duration: Indefinitely
                  target:
                    device_id: 6239543fc9a684fbba5d4af77ccdf052
              - service: script.inovelli_led_control
                metadata: {}
                data:
                  led: Led 4
                  color: Cyan
                  level: 43
                  effect: Clear
                  duration: Indefinitely
                  target:
                    device_id: 6239543fc9a684fbba5d4af77ccdf052
              - service: script.inovelli_led_control
                metadata: {}
                data:
                  led: Led 5
                  color: Cyan
                  level: 43
                  effect: Clear
                  duration: Indefinitely
                  target:
                    device_id: 6239543fc9a684fbba5d4af77ccdf052
              - service: script.inovelli_led_control
                metadata: {}
                data:
                  led: Led 6
                  color: Cyan
                  level: 43
                  effect: Clear
                  duration: Indefinitely
                  target:
                    device_id: 6239543fc9a684fbba5d4af77ccdf052
              - service: script.inovelli_led_control
                metadata: {}
                data:
                  led: Led 7
                  color: Cyan
                  level: 43
                  effect: Clear
                  duration: Indefinitely
                  target:
                    device_id: 6239543fc9a684fbba5d4af77ccdf052
          - conditions: >-
              {{ trigger.to_state.state == "Litter Level Low" }}
            sequence:
              - service: script.inovelli_led_control
                metadata: {}
                data:
                  led: Led 1
                  color: Cyan
                  level: 30
                  effect: Solid
                  duration: Indefinitely
                  target:
                    device_id: 6239543fc9a684fbba5d4af77ccdf052
              - service: script.inovelli_led_control
                metadata: {}
                data:
                  led: Led 2
                  color: Cyan
                  level: 30
                  effect: Solid
                  duration: Indefinitely
                  target:
                    device_id: 6239543fc9a684fbba5d4af77ccdf052
          - conditions: >-
              {{ trigger.to_state.state == "Litter Drawer Almost Full" }}
            sequence:
              - service: script.inovelli_led_control
                metadata: {}
                data:
                  led: Led 1
                  color: Orange
                  level: 30
                  effect: Solid
                  duration: Indefinitely
                  target:
                    device_id: 6239543fc9a684fbba5d4af77ccdf052
              - service: script.inovelli_led_control
                metadata: {}
                data:
                  led: Led 2
                  color: Orange
                  level: 30
                  effect: Solid
                  duration: Indefinitely
                  target:
                    device_id: 6239543fc9a684fbba5d4af77ccdf052
              - service: script.inovelli_led_control
                metadata: {}
                data:
                  led: Led 3
                  color: Orange
                  level: 30
                  effect: Solid
                  duration: Indefinitely
                  target:
                    device_id: 6239543fc9a684fbba5d4af77ccdf052
              - service: script.inovelli_led_control
                metadata: {}
                data:
                  led: Led 4
                  color: Orange
                  level: 30
                  effect: Solid
                  duration: Indefinitely
                  target:
                    device_id: 6239543fc9a684fbba5d4af77ccdf052
              - service: script.inovelli_led_control
                metadata: {}
                data:
                  led: Led 5
                  color: Orange
                  level: 30
                  effect: Solid
                  duration: Indefinitely
                  target:
                    device_id: 6239543fc9a684fbba5d4af77ccdf052
          - conditions: >-
              {{ trigger.to_state.state == "Litter Drawer Full" }}
            sequence:
              - service: script.inovelli_led_control
                metadata: {}
                data:
                  led: All
                  color: Red
                  level: 40
                  effect: Solid
                  duration: Indefinitely
                  target:
                    device_id: 6239543fc9a684fbba5d4af77ccdf052
          - conditions: >-
              {{ trigger.to_state.state == "Litter Box Cycling" }}
            sequence:
              - service: script.inovelli_led_control
                data:
                  target:
                    device_id:
                      - 6239543fc9a684fbba5d4af77ccdf052
                  led: All
                  color: White
                  level: 15
                  duration: Indefinitely
                  effect: Fast Rising

input_select:
  upstairs_hall_light_switch_led_mode:
    name: Upstairs Hall Light Switch LED Mode
    icon: mdi:led-strip
    options:
      - "Off"
      - "Litter Level Low"
      - "Litter Drawer Almost Full"
      - "Litter Drawer Full"
      - "Litter Box Cycling"
