# TODO: Turn this into a blueprint. I have multiple closets where I want this same set of automations.

automation:
  - id: 2eec6c30-e10f-4c4d-816e-8008c1598b92
    alias: Set Linen Closet Light Based on Door
    trigger:
      - platform: state
        entity_id: binary_sensor.linen_closet_door_sensor_contact
        not_from:
          - "unknown"
          - "unavailable"
    action:
      - service: >-
          {% if trigger.to_state.state == "on" %}
            light.turn_on
          {% else %}
            light.turn_off
          {% endif %}
        target:
          entity_id: light.linen_closet_light

  - id: 59de41f9-636f-4803-aa3b-3d3d47c4947f
    alias: Turn off linen closet light after 30 minutes
    trigger:
      - platform: state
        entity_id: light.linen_closet_light
        from: "off"
        to: "on"
        for:
          minutes: 30
    action:
      - alias: "Debug - Notify"
        service: notify.corban
        data:
          title: "Linen closet light left on."
          message: "Turning off after 30 minutes."
      - alias: "Turn off"
        service: light.turn_off
        target:
          entity_id: light.linen_closet_light
