# Litter Box Reminder System

# This pushes a notification to both of our phones to ensure the litter box is cleaned each night.
# If one user acknowledges the notification, the notification is dismissed on both devices.

input_boolean:
  litter_box_clean_needed:
    name: "Litter Box Needs Cleaning"
    icon: "mdi:broom"
  litter_box_clean_skip:
    name: "Skip Next Litter Box Cleaning Reminder"
    icon: "mdi:debug-step-over"

automation:
  - alias: Reminder to do the litter box
    id: c4dcc56f-1797-444f-90d5-db1abc436a19
    trigger:
      - platform: time
        at: "19:00:00" # 7 PM.
    condition:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "off"
    action:
      # If the skip setting is on, just turn it off.
      # Otherwise, send the notification.
      - choose:
          - conditions:
              - condition: state
                entity_id: input_boolean.litter_box_clean_skip
                state: "on"
            sequence:
              - service: input_boolean.turn_off
                data:
                  entity_id: input_boolean.litter_box_clean_skip
        default:
          - service: input_boolean.turn_on
            data:
              entity_id: input_boolean.litter_box_clean_needed

  - alias: Send reminder to do the litter box
    id: 6d7045a8-d073-45f0-b752-e8292f2ff875
    trigger:
      - platform: state
        entity_id: input_boolean.litter_box_clean_needed
        to: "on"
    action:
      # - service: notify.adult_android_phones
      #   data:
      #     title: "Litter Box Check"
      #     message: "Has the litter box been done?"
      #     data:
      #       tag: 10 # Arbitrary but constant.
      #       icon: https://home.corb.co/local/litter_box/litter_box_icon.png
      #       actions:
      #         - action: "litter_box_complete"
      #           title: "Yes, complete."
      - service: notify.adult_ios_phones
        data:
          title: "Litter Box Check"
          message: "Has the litter box been done?"
          data:
            tag: "litter_box_reminder"
            actions:
              - action: "LITTER_COMPLETE"
                title: "Yes, complete."
                activationMode: "background"
                authenticationRequired: false # Don't require unlocking the device
                destructive: false
                behavior: "default"

  # Dismiss notifications on all devices when acknowledged.
  - alias: Litter box reminder clicked
    id: b3132070-58f0-47c2-acec-ac471ba040ce
    trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: "LITTER_COMPLETE"
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.litter_box_clean_needed

  - alias: Dismiss litter box notifications
    id: bced3701-219b-4c41-824f-b38416cb0506
    trigger:
      - platform: state
        entity_id: input_boolean.litter_box_clean_needed
        to: "off"
    action:
      - service: notify.adult_ios_phones
        data:
          message: clear_notification
          data:
            tag: "litter_box_reminder"

  - alias: Litter Box Button - Click
    id: 6bca1452-eb94-4cfd-b396-82f8555d8f2b
    trigger:
      - platform: device
        domain: mqtt
        device_id: 24d7573f0424b71156560a74fede5da7
        discovery_id: 0x00158d00027bee0b action_single
        type: action
        subtype: single
    action:
      # If the reminder is already issued, just turn it off.
      # If not, skip it for the day.
      - choose:
          - conditions:
              - condition: state
                entity_id: input_boolean.litter_box_clean_needed
                state: "on"
            sequence:
              - service: input_boolean.turn_off
                data:
                  entity_id: input_boolean.litter_box_clean_needed
        default:
          - service: input_boolean.turn_on
            data:
              entity_id: input_boolean.litter_box_clean_skip
