# Litter Box Reminder System

# This pushes a notification to both of our phones to ensure the litter box is cleaned each night.
# If one user acknowledges the notification, the notification is dismissed on both devices.

input_boolean:
  litter_box_clean_needed:
    name: "Litter Box Needs Cleaning"
    icon: "mdi:broom"

automation:
  - alias: Reminder to do the litter box
    trigger:
      - platform: time
        at: "19:00:00" # 7 PM. TODO: Make configurable?
    condition:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "off"
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.litter_box_clean_needed

  - alias: Send reminder to do the litter box
    trigger:
      - platform: state
        entity_id: input_boolean.litter_box_clean_needed
        to: "on"
    action:
      # - service: notify.adult_android_phones
      #   data:
      #     title: "Litter Box Check"
      #     message: "Has the litter box been done?"
      #     data:
      #       tag: 10 # Arbitrary but constant.
      #       icon: https://home.corb.co/local/litter_box/litter_box_icon.png
      #       actions:
      #         - action: "litter_box_complete"
      #           title: "Yes, complete."
      - service: notify.adult_ios_phones
        data:
          title: "Litter Box Check"
          message: "Has the litter box been done?"
          data:
            push:
              category: "litter_box" # Adds the action button.
            apns_headers:
              "apns-collapse-id": "litter-box"


  # Dismiss notifications on all devices when acknowledged.
  - alias: Litter box reminder clicked
    trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: litter_box_complete
      - platform: event
        event_type: ios.notification_action_fired
        event_data:
          actionName: COMPLETE
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.litter_box_clean_needed

  - alias: Dismiss litter box notifications
    trigger:
      - platform: state
        entity_id: input_boolean.litter_box_clean_needed
        to: "off"
    action:
      # - service: notify.adult_android_phones
      #   data:
      #     message: clear_notification
      #     data:
      #       tag: 10 # Arbitrary but constant.
      - service: notify.adult_ios_phones
        data:
          title: "Litter Box Check - Complete"
          message: "Litter box has been done."
          data:
            push:
              sound: none
            apns_headers:
              "apns-collapse-id": "litter-box"


ios:
  push:
    categories:
      - name: Litter Box
        identifier: "litter_box"
        actions:
          - identifier: "COMPLETE"
            title: "Yes, complete."
            activationMode: "background"
            authenticationRequired: false # Don't require unlocking the device
            destructive: false
            behavior: "default"
