# Litter Box Reminder System

# This pushes a notification to both of our phones to ensure the litter box is cleaned each night.
# If one user acknowledges the notification, the notification is dismissed on both devices.

automation:
  - alias: Reminder to do the litter box
    trigger:
      - platform: time
        at: '19:00:00' # 7 PM. TODO: Make configurable?
    condition:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "off"
    action:
      service: script.turn_on
      entity_id: script.litter_send_notifications
  - alias: Litter box reminder clicked
    trigger:
      platform: event
      event_type: ariela_notification_clicked
      event_data:
        action: litter_box_complete
    action:
      service: script.turn_on
      entity_id: script.litter_dismiss_notifications


script:
  litter_send_notifications:
    sequence:
      - service: notify.mobile_app_edith
        data:
          title: "Litter Box Check"
          message: "Has the litter box been done?"
          data:
            tag: 10 # Arbitrary but constant.
            icon: https://home.corb.co/local/litter_box/litter_box_icon.png
            actions:
              - action: "litter_box_complete"
                title: "Yes, complete."
                # icon: https://home.corb.co/local/litter_box/check-bold.png
      - service: notify.mobile_app_jackie
        data:
          title: "Litter Box Check"
          message: "Has the litter box been done?"
          data:
            tag: 10 # Arbitrary but constant.
            icon: https://home.corb.co/local/litter_box/litter_box_icon.png
            actions:
              - action: "litter_box_complete"
                title: "Yes, complete."
                # icon: https://home.corb.co/local/litter_box/check-bold.png
  litter_dismiss_notifications:
    sequence:
      - service: notify.mobile_app_edith
        data:
          title: "Litter Box Check"
          message: "Has the litter box been done?"
          data:
            tag: 10 # Arbitrary but constant.
            dismiss: true # Get rid of the notification
            actions:
              - action: "litter_box_complete"
                title: "Yes, complete."
      - service: notify.mobile_app_jackie
        data:
          title: "Litter Box Check"
          message: "Has the litter box been done?"
          data:
            tag: 10 # Arbitrary but constant.
            dismiss: true # Get rid of the notification
            actions:
              - action: "litter_box_complete"
                title: "Yes, complete."
