# See `esphome/living-room-switch-shelly.yaml`

# TODO: Turn this into a blueprint for the Shelly switched outlet sensors.

automation:
  - alias: Living Room Switch - Toggle Lamp
    id: 94d5ae95-169b-4a87-ab06-43585bd7462e
    trigger:
      - platform: state
        entity_id: binary_sensor.office_switch_sensor # binary_sensor.living_room_switch_sensor
        from: "off"
        to: "on"
      - platform: state
        entity_id: binary_sensor.office_switch_sensor # living_room_switch_sensor
        from: "on"
        to: "off"
    action:
      - choose:
          # If off, turn on.
          - conditions:
              - condition: state
                entity_id: light.corner_lamp
                state: "off"
            sequence:
              - service: light.turn_on
                entity_id: light.corner_lamp
                #  Brightness is currently controlled by Adaptive Lighting.
                # data:
                #   brightness: 255
          # If on, turn off.
          - conditions:
              - condition: state
                entity_id: light.corner_lamp
                state: "on"
            sequence:
              - service: light.turn_off
                target:
                  entity_id: light.corner_lamp
      - delay:
          milliseconds: 250
