template:
  - binary_sensor:
      - name: "Living Room Assumed Presence"
        unique_id: c647ffd9-f8af-4e09-a862-9959a99e2a9a
        device_class: occupancy
        state: >-
          {{
            is_state('binary_sensor.living_room_presence', 'on') or
            is_state('media_player.living_room_lg_tv', 'on')
          }}

automation:
  - alias: Living Room Motion Lights
    id: 42109bf8-895c-4fca-88f4-2e2d17975d27
    mode: restart
    trigger:
      - platform: state
        entity_id: binary_sensor.living_room_assumed_presence
        to: "on"
      - platform: state
        entity_id: binary_sensor.living_room_assumed_presence
        to: "off"
        for:
          minutes: 5
    condition:
      - alias: "Home Mode"
        condition: state
        entity_id: input_select.home_mode
        state: "Home"
      - alias: "Living room is not marked as excluded"
        condition: state
        entity_id: input_boolean.room_exclude_livingroom
        state: "off"
    action:
      - choose:
          - conditions: "{{ trigger.to_state.state == 'on' }}"
            sequence:
              - service: light.turn_on
                target:
                  entity_id: light.corner_lamp
          - conditions: "{{ trigger.to_state.state == 'off' }}"
            sequence:
              - if:
                  - alias: "Training Mode On"
                    condition: state
                    entity_id: input_boolean.training_mode
                    state: "on"
                then:
                  - alias: "Wait until Training Mode is off"
                    wait_for_trigger:
                      - platform: state
                        entity_id: input_boolean.training_mode
                        to: "off"
              - service: light.turn_off
                target:
                  entity_id: light.corner_lamp
