# There are two Switchbot Curtain 3 motors installed in the Living Room.

# https://github.com/v6ak/v6-quietdrift
# Custom integration to support "QuietDrift" mode.
v6_quietdrift:

automation:
  - alias: "Open living room curtains in the morning"
    id: ca39ee01-15c7-48b0-a34c-2500d2f91a64
    triggers:
      - trigger: state
        entity_id: input_select.home_mode
        from: "Sleep"
        to: "Home"
    conditions:
      - alias: "Living room automations are not disabled"
        condition: state
        entity_id: input_boolean.room_exclude_livingroom
        state: "off"
    actions:
      # - action: cover.open_cover
      #   target:
      #     entity_id:
      #       - cover.living_room_curtain_left
      #       - cover.living_room_curtain_right
      - action: v6_quietdrift.set_switchbot_curtain_position
        data:
          entity_id:
            - cover.living_room_curtain_left
            - cover.living_room_curtain_right
          position: 100
          speed: 2

  - alias: "Close living room curtains around sunset"
    id: 7b1fcd09-ff2a-4257-a733-06e7840ee49c
    mode: restart
    triggers:
      - trigger: sun
        event: sunset
    conditions:
      - alias: "Living room automations are not disabled"
        condition: state
        entity_id: input_boolean.room_exclude_livingroom
        state: "off"
      - not:
          - condition: state
            entity_id: input_select.home_mode
            state: "Vacation"
    actions:
      - if:
          - condition: state
            entity_id: binary_sensor.living_room_window_1_contact
            state: "off"
        then:
          - action: v6_quietdrift.set_switchbot_curtain_position
            data:
              entity_id:
                - cover.living_room_curtain_left
                - cover.living_room_curtain_right
              position: 0
              speed: 2
        else:
          # Close left, and then wait to close right once the window is closed.
          - action: v6_quietdrift.set_switchbot_curtain_position
            data:
              entity_id:
                - cover.living_room_curtain_left
              position: 0
              speed: 2
          ## This is now handled by the general case automation below.
          # - wait_for_trigger:
          #     - trigger: state
          #       entity_id:
          #         - binary_sensor.living_room_window_1_contact
          #       to: "off"
          #       for:
          #         seconds: 2
          #   continue_on_timeout: false
          #   timeout:
          #     hours: 8
          # - action: v6_quietdrift.set_switchbot_curtain_position
          #   data:
          #     entity_id:
          #       - cover.living_room_curtain_right
          #     position: 0
          #     speed: 2

  - alias: Living Room Curtains - Match Window State
    id: 3600672a-34d4-40ef-9154-4d95b8798151
    mode: restart
    triggers:
      - trigger: state
        entity_id:
          - binary_sensor.living_room_window_1_contact
        from: "on"
        to: "off"
        id: closed
        for:
          hours: 0
          minutes: 0
          seconds: 2
      - trigger: state
        entity_id:
          - binary_sensor.living_room_window_1_contact
        from: "off"
        to: "on"
        id: open
        for:
          hours: 0
          minutes: 0
          seconds: 5
    conditions:
      - alias: Living room automations are not disabled
        condition: state
        entity_id: input_boolean.room_exclude_livingroom
        state: "off"
      - condition: state
        entity_id: cover.living_room_curtain_left
        state: closed
    actions:
      - choose:
          - conditions:
              - condition: trigger
                id:
                  - open
              - condition: state
                entity_id: cover.living_room_curtain_right
                state: closed
            sequence:
              - alias: Open the Right Curtain
                action: v6_quietdrift.set_switchbot_curtain_position
                data:
                  entity_id:
                    - cover.living_room_curtain_right
                  position: 100
                  speed: 2
          - conditions:
              - condition: trigger
                id:
                  - closed
              - condition: state
                entity_id: cover.living_room_curtain_right
                state: open
            sequence:
              - alias: Close the Right Curtain
                action: v6_quietdrift.set_switchbot_curtain_position
                data:
                  entity_id:
                    - cover.living_room_curtain_right
                  position: 0
                  speed: 2

template:
  - binary_sensor:
      - name: "Living Room Curtains - Low Battery"
        unique_id: 46eab49d-8bd9-4cc0-872a-1fb64269231e
        device_class: battery
        state: >-
          {{
            states("sensor.living_room_curtain_left_battery") | int(100) < 20 or
            states("sensor.living_room_curtain_right_battery") | int(100) < 20
          }}

  - cover:
      # Group the left and right curtains together
      - unique_id: 684b2cc9-618d-4d7e-a42c-6fe9c5c5980b
        name: Living Room Window 1 Curtains
        device_class: curtain
        set_cover_position:
          - action: v6_quietdrift.set_switchbot_curtain_position
            data:
              entity_id:
                - cover.living_room_curtain_left
                - cover.living_room_curtain_right
              position: "{{position}}"
              speed: 2
        default_entity_id: cover.living_room_window_1_curtains
        position: >-
          {% set position = (state_attr("cover.living_room_curtain_left", "current_position") + state_attr("cover.living_room_curtain_right", "current_position")) / 2 %}

          {% if position < 3 %}
            0
          {% else %}
            {{ position }}
          {% endif %}
