# Similar to `packages/living_room_remote.yaml`. Stepped control of the living room lights.

automation:
  - id: 666f0048-d937-49aa-a42a-104f93a8795e
    alias: Living Room Switch - On - Lights
    trigger:
      - platform: device
        domain: mqtt
        device_id: c267d3d48bf04135851855dc4be36cbb
        type: action
        subtype: "on"
        discovery_id: 0x000d6ffffea6b202 action_on
    action:
      # Regardless of state, just set the living room lamp to full.
      # This allows tapping once for full brightness and then tapping down to go to the right setting.
      - service: light.turn_on
        entity_id: light.corner_lamp
        data:
          brightness: 255
      # - choose:
      #     # Off: Turn on TV lamp full brightness
      #     - conditions:
      #         - condition: template
      #           value_template: >-
      #             {{
      #               is_state("light.tv_lamp", "off")
      #             }}
      #       sequence:
      #         - service: light.turn_on
      #           entity_id: light.tv_lamp
      #           data:
      #             brightness: 255
      #     # On but dim: Turn on to full brightness
      #     - conditions:
      #         - condition: template
      #           value_template: >-
      #             {{
      #               is_state("light.tv_lamp", "on") and
      #               state_attr("light.tv_lamp", "brightness") <= 180
      #             }}
      #       sequence:
      #         - service: light.turn_on
      #           entity_id: light.tv_lamp
      #           data:
      #             brightness: 255
      #     # Bright: Do nothing
      #     - conditions:
      #         - condition: template
      #           value_template: >-
      #             {{
      #               is_state("light.tv_lamp", "on") and
      #               180 < state_attr("light.tv_lamp", "brightness")
      #             }}
      #       sequence:

  - id: f3012019-cddb-4c26-803a-96b5f355e25d
    alias: Living Room Switch - Off - Lights
    trigger:
      - platform: device
        domain: mqtt
        device_id: c267d3d48bf04135851855dc4be36cbb
        type: action
        subtype: "off"
        discovery_id: 0x000d6ffffea6b202 action_off
    action:
      - choose:
          # Bright: Go to medium
          - conditions:
              - condition: template
                value_template: >-
                  {{
                    is_state("light.corner_lamp", "on") and
                    170 < state_attr("light.corner_lamp", "brightness")
                  }}
            sequence:
              - service: light.turn_on
                entity_id: light.corner_lamp
                data:
                  brightness: 170
          # Medium: Go to dim
          - conditions:
              - condition: template
                value_template: >-
                  {{
                    is_state("light.corner_lamp", "on") and
                    100 < state_attr("light.corner_lamp", "brightness") <= 170
                  }}
            sequence:
              - service: light.turn_on
                entity_id: light.corner_lamp
                data:
                  brightness: 100
          # Dim: Turn off
          - conditions:
              - condition: template
                value_template: >-
                  {{
                    is_state("light.corner_lamp", "on") and
                    0 < state_attr("light.corner_lamp", "brightness") <= 100
                  }}
            sequence:
              - service: light.turn_off
                entity_id: light.corner_lamp
                data:
                  transition: 0
          # Off: Do nothing.
          # - conditions:
          #     - condition: template
          #       value_template: >-
          #         {{
          #           is_state("light.corner_lamp", "off")
          #         }}
          #   sequence:

  - id: e28f0500-362d-4222-90fe-a092b6d68a38
    alias: Living Room Switch - Hold On - Vacuum
    trigger:
      - platform: device
        domain: mqtt
        device_id: c267d3d48bf04135851855dc4be36cbb
        type: action
        subtype: brightness_move_up
        discovery_id: 0x000d6ffffea6b202 action_brightness_move_up
    action:
      - service: vacuum.start
        target:
          entity_id: vacuum.valetudo_eve

  - id: 7d3730d4-093c-4340-b10c-03e517fcd74d
    alias: Living Room Switch - Hold Off - Pause TV
    trigger:
      - platform: device
        domain: mqtt
        device_id: c267d3d48bf04135851855dc4be36cbb
        type: action
        subtype: brightness_move_down
        discovery_id: 0x000d6ffffea6b202 action_brightness_move_down
    action:
      - service: media_player.media_play_pause
        target:
          entity_id: media_player.living_room_apple_tv
