automation:
  - alias: "Living Room Remote - Channel Up: Brighten lights"
    id: 86567e74-da83-49e7-b1e0-7b0a89127224
    mode: single # Cool down delay at the end.
    trigger:
      - platform: event
        event_type: esphome.living_room.channel_up
    action:
      - choose:
          # Off: Turn on dim
          - conditions:
              - condition: template
                value_template: >-
                  {{
                    is_state("light.tv_lamp", "off")
                  }}
            sequence:
              - service: light.turn_on
                entity_id: light.tv_lamp
                data:
                  brightness: 34
          # Dim: Turn on medium
          - conditions:
              - condition: template
                value_template: >-
                  {{
                    is_state("light.tv_lamp", "on") and
                    0 < state_attr("light.tv_lamp", "brightness") <= 100
                  }}
            sequence:
              - service: light.turn_on
                entity_id: light.tv_lamp
                data:
                  brightness: 150
          # Medium: Turn on bright
          - conditions:
              - condition: template
                value_template: >-
                  {{
                    is_state("light.tv_lamp", "on") and
                    100 < state_attr("light.tv_lamp", "brightness") <= 180
                  }}
            sequence:
              - service: light.turn_on
                entity_id: light.tv_lamp
                data:
                  brightness: 255
          # Bright: Turn on the rest of the living room lights
          - conditions:
              - condition: template
                value_template: >-
                  {{
                    is_state("light.tv_lamp", "on") and
                    180 < state_attr("light.tv_lamp", "brightness")
                  }}
            sequence:
              - service: scene.turn_on
                entity_id: scene.living_room_bright
      - delay:
          milliseconds: 200

  - alias: "Living Room Remote - Channel Down: Dim lights"
    id: 03b43a1b-e0d8-471e-88c3-b2f369aab564
    mode: single # Cool down delay at the end.
    trigger:
      - platform: event
        event_type: esphome.living_room.channel_down
    action:
      - choose:
          # Bright with other lights on: Turn off the other lights.
          - conditions:
              - condition: template
                value_template: >-
                  {{
                    is_state("light.tv_lamp", "on") and
                    180 < state_attr("light.tv_lamp", "brightness") and
                    is_state("light.couch_side_table_lamp", "on")
                  }}
            sequence:
              - service: scene.turn_on
                entity_id: scene.living_room_dim # TODO: This needs a medium scene again. Maybe this could just cycle between a couple scenes?
          # Bright: Turn on medium
          - conditions:
              - condition: template
                value_template: >-
                  {{
                    is_state("light.tv_lamp", "on") and
                    180 < state_attr("light.tv_lamp", "brightness")
                  }}
            sequence:
              - service: light.turn_on
                entity_id: light.tv_lamp
                data:
                  brightness: 150
          # Medium: Turn on dim
          - conditions:
              - condition: template
                value_template: >-
                  {{
                    is_state("light.tv_lamp", "on") and
                    100 < state_attr("light.tv_lamp", "brightness") <= 180
                  }}
            sequence:
              - service: light.turn_on
                entity_id: light.tv_lamp
                data:
                  brightness: 34
          # Dim: Turn off
          - conditions:
              - condition: template
                value_template: >-
                  {{
                    is_state("light.tv_lamp", "on") and
                    0 < state_attr("light.tv_lamp", "brightness") <= 100
                  }}
            sequence:
              # This should be a scene, but the scene seems to automatically add a transition. Skip it.
              - service: light.turn_off
                entity_id: light.tv_lamp
                data:
                  transition: 0
          # Off: Turn off living room lights
          - conditions:
              - condition: template
                value_template: >-
                  {{
                    is_state("light.tv_lamp", "off")
                  }}
            sequence:
              - service: scene.turn_on
                entity_id: scene.living_room_off
      - delay:
          milliseconds: 200

  # - alias: "Living Room Remote - Source Button"
  #   id: e44385f5-c0be-46e0-b965-6e987c965374
  #   trigger:
  #     - platform: event
  #       event_type: esphome.living_room.source
  #   action:
  #     # TODO: What do we want this to do?
