media_player:
  - platform: universal
    name: Living Room TV
    children:
      - media_player.plex_living_room_roku_tv
      - media_player.living_room_chromecast
      - media_player.65_tcl_roku_tv
    commands:
      volume_up:
        service: script.soundbar_volume_up
      volume_down:
        service: script.soundbar_volume_down
      volume_mute:
        service: script.soundbar_power
      select_source:
        service: media_player.select_source
        data_template:
          entity_id: media_player.65_tcl_roku_tv
          source: "{{ source }}"
    attributes:
      source: media_player.65_tcl_roku_tv|source
      source_list: media_player.65_tcl_roku_tv|source_list

switch:
  - platform: template
    switches:
      living_room_tv_power:
        friendly_name: Living Room TV
        icon_template: mdi:television
        value_template: "{{ is_state('remote.living_room_roku_tv', 'on') }}"
        turn_on:
          - service: media_player.turn_on
            data:
              entity_id: media_player.65_tcl_roku_tv
        turn_off:
          - service: media_player.turn_off
            entity_id: media_player.65_tcl_roku_tv

script:
  # Script wrappers for the Roku controls.
  roku_play_pause:
    alias: "Play/Pause"
    icon: mdi:play-pause
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.living_room_roku_tv
          command: "play"
  roku_replay:
    alias: "Replay"
    icon: mdi:replay
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.living_room_roku_tv
          command: "replay"
  roku_back:
    alias: "Back"
    icon: mdi:keyboard-backspace
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.living_room_roku_tv
          command: "back"

  # esphome autoconfigures switches for these. Wrap them in scripts so they appear as buttons in the front end.
  soundbar_volume_up:
    sequence:
      - service: switch.turn_on
        entity_id: switch.soundbar_volume_up
  soundbar_volume_down:
    sequence:
      - service: switch.turn_on
        entity_id: switch.soundbar_volume_down
  soundbar_power:
    sequence:
      - service: switch.turn_on
        entity_id: switch.soundbar_power

  # "Scenes"
  living_room_movie_mode:
    alias: Movie Mode
    icon: mdi:movie
    sequence:
      - service: scene.turn_on
        entity_id: scene.movie_mode
      - service: script.living_room_tv_and_soundbar_on

  living_room_game_mode:
    alias: Game Mode
    icon: mdi:google-controller
    sequence:
      - service: scene.turn_on
        entity_id: scene.movie_mode # At least until I make a game mode scene.
      - service: script.living_room_tv_and_soundbar_on
      - delay: 00:00:02
      - service: media_player.select_source
        data:
          entity_id: media_player.65_tcl_roku_tv
          source: Switch
      - delay: 00:00:03 # Try a second time in case
      - service: media_player.select_source
        data:
          entity_id: media_player.65_tcl_roku_tv
          source: Switch

  # Other
  living_room_tv_and_soundbar_on:
    sequence:
      - service: switch.turn_on
        entity_id:
          - switch.living_room_tv_power # Turn on the TV.
          - switch.soundbar # And the soundbar.

automation:
  - alias: Send play/pause to Chromecast when selected
    trigger:
      - platform: event
        event_type: esphome.living_room.play_pause
    condition:
      - condition: template
        value_template: >
          {{ is_state_attr('media_player.65_tcl_roku_tv', 'source', 'Chromecast') }}
    action:
      - service: media_player.media_play_pause
        data:
          entity_id: media_player.living_room_chromecast

  - alias: Switch the TV to the Chromecast when someone starts casting
    trigger:
      - platform: state
        entity_id: media_player.living_room_chromecast
        to: "idle"
      - platform: state
        entity_id: media_player.living_room_chromecast
        to: "playing"
    condition:
      - condition: template
        value_template: >
          {{ not is_state_attr('media_player.65_tcl_roku_tv', 'source', 'Chromecast') }}
    action:
      - service: script.living_room_tv_and_soundbar_on
      - service: media_player.select_source
        data:
          entity_id: media_player.65_tcl_roku_tv
          source: Chromecast

  - alias: Turn on the soundbar when the TV turns on
    trigger:
      - platform: state
        entity_id: switch.living_room_tv_power
        from: 'off'
        to: 'on'
    action:
      - service: switch.turn_on
        entity_id: switch.soundbar
