media_player:
  - platform: universal
    name: Living Room TV
    unique_id: aea9df25-cb3a-4d61-88b8-4412ecc69d92
    device_class: tv
    children:
      # - media_player.plex_living_room_roku_tv
      # - media_player.plex_plex_for_apple_tv_apple_tv
      - media_player.living_room_apple_tv
      - media_player.living_room_chromecast
      # - media_player.65_tcl_roku_tv
    commands:
      turn_on:
        service: media_player.turn_on
        data:
          entity_id: media_player.65_tcl_roku_tv
      turn_off:
        service: media_player.turn_off
        data:
          entity_id: media_player.65_tcl_roku_tv
      volume_up:
        service: media_player.volume_up
        target:
          entity_id: media_player.living_room_apple_tv
      volume_down:
        service: media_player.volume_down
        target:
          entity_id: media_player.living_room_apple_tv
      # select_source:
      #   service: media_player.select_source
      #   data_template:
      #     entity_id: media_player.65_tcl_roku_tv
      #     source: "{{ source }}"
    attributes:
      state: switch.living_room_tv_power
      # source: media_player.65_tcl_roku_tv|source
      # source_list: media_player.65_tcl_roku_tv|source_list

switch:
  - platform: template
    switches:
      living_room_tv_power:
        friendly_name: Living Room TV
        icon_template: mdi:television
        value_template: "{{ is_state('remote.living_room_roku_tv', 'on') }}"
        turn_on:
          - service: media_player.turn_on
            data:
              entity_id: media_player.65_tcl_roku_tv
        turn_off:
          - service: media_player.turn_off
            entity_id: media_player.65_tcl_roku_tv

script:
  # Script wrappers for the Roku controls.
  roku_play_pause:
    alias: "Play/Pause"
    icon: mdi:play-pause
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.living_room_roku_tv
          command: "play"
  roku_replay:
    alias: "Replay"
    icon: mdi:replay
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.living_room_roku_tv
          command: "replay"
  roku_back:
    alias: "Back"
    icon: mdi:keyboard-backspace
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.living_room_roku_tv
          command: "back"

automation:
  - alias: Send play/pause to Chromecast when selected
    id: 29bd3071-1a72-45f7-a4f8-7ce8deb7210f
    trigger:
      - platform: event
        event_type: esphome.living_room.play_pause
    condition:
      - condition: template
        value_template: >
          {{ is_state_attr('media_player.65_tcl_roku_tv', 'source', 'Chromecast') }}
    action:
      - service: media_player.media_play_pause
        data:
          entity_id: media_player.living_room_chromecast

  - alias: Turn on the soundbar when the TV turns on
    id: d7bedd79-cc08-4fec-bf25-5971f0fbcaad
    trigger:
      - platform: state
        entity_id: switch.living_room_tv_power
        from: "off"
        to: "on"
    action:
      - service: switch.turn_on
        entity_id: switch.soundbar
