media_player:
  - platform: universal
    name: Living Room TV
    children:
      - media_player.plex_living_room_roku_tv
      - media_player.living_room_chromecast
      - media_player.65_tcl_roku_tv
    commands:
      volume_up:
        service: script.soundbar_volume_up
      volume_down:
        service: script.soundbar_volume_down
      volume_mute:
        service: script.soundbar_power
      select_source:
        service: media_player.select_source
        data_template:
          entity_id: media_player.65_tcl_roku_tv
          source: "{{ source }}"
    attributes:
      source: media_player.65_tcl_roku_tv|source
      source_list: media_player.65_tcl_roku_tv|source_list

switch:
  - platform: command_line
    switches:
      living_room_tv_power_command_line:
        command_on: "curl -X POST http://10.0.0.248:8060/keypress/PowerOn"
        command_off: "curl -X POST http://10.0.0.248:8060/keypress/PowerOff"
        command_state: 'curl -m 5 -s GET http://10.0.0.248:8060/query/device-info | grep power-mode | sed -e "s:<power-mode>DisplayOff</power-mode>:OFF:" -e "s:<power-mode>PowerOn</power-mode>:ON:"'
        value_template: '{{ value == "ON" }}'
  - platform: template
    switches:
      living_room_tv_power:
        value_template: "{{ is_state('switch.living_room_tv_power_command_line', 'on') }}"
        turn_on:
          - service: wake_on_lan.send_magic_packet
            data:
              mac: !secret living_room_tv_mac
          - service: switch.turn_on
            data:
              entity_id: switch.living_room_tv_power_command_line
        turn_off:
          - service: switch.turn_off
            entity_id: switch.living_room_tv_power_command_line

      living_room_soundbar_power:
        # On this soundbar, volume down is ignored if the soundbar is off, and volume up turns it on.
        # Using this, we can build sequences that will always turn the soundbar on and off, regardless
        # of its starting state, and leave it at its initial volume level.
        value_template: "false" # assumed_state, set below, because we can't tell if it's on or off.
        turn_on:
          - service: switch.turn_on
            entity_id: switch.soundbar_volume_down
          - delay:
              milliseconds: 200
          - service: switch.turn_on
            entity_id: switch.soundbar_volume_up
        turn_off:
          # First, ensure it's on.
          - service: switch.turn_on
            entity_id: switch.soundbar_volume_down
          - delay:
              milliseconds: 200
          - service: switch.turn_on
            entity_id: switch.soundbar_volume_up
          # It takes a bit after turning on before the soundbar will turn back off.
          - delay:
              seconds: 1
          - service: switch.turn_on
            entity_id: switch.soundbar_power

rest_command:
  # https://sdkdocs.roku.com/display/sdkdoc/External+Control+API#ExternalControlAPI-KeypressKeyValues
  living_room_roku_keypress:
    url: "http://10.0.0.248:8060/keypress/{{button}}"
    method: post

script:
  # Script wrappers for the Roku controls.
  roku_play_pause:
    alias: "Play/Pause"
    icon: mdi:play-pause
    sequence:
      - service: rest_command.living_room_roku_keypress
        data:
          button: Play
  roku_replay:
    alias: "Replay"
    icon: mdi:replay
    sequence:
      - service: rest_command.living_room_roku_keypress
        data:
          button: InstantReplay
  roku_back:
    alias: "Back"
    icon: mdi:keyboard-backspace
    sequence:
      - service: rest_command.living_room_roku_keypress
        data:
          button: Back

  # esphome autoconfigures switches for these. Wrap them in scripts so they appear as buttons in the front end.
  soundbar_volume_up:
    sequence:
      - service: switch.turn_on
        entity_id: switch.soundbar_volume_up
  soundbar_volume_down:
    sequence:
      - service: switch.turn_on
        entity_id: switch.soundbar_volume_down
  soundbar_power:
    sequence:
      - service: switch.turn_on
        entity_id: switch.soundbar_power

  # "Scenes"
  living_room_dinner_mode:
    alias: Dinner Mode
    icon: mdi:silverware
    sequence:
      - service: scene.turn_on
        entity_id: scene.dinner_mode
      - service: script.living_room_tv_and_soundbar_on

  living_room_movie_mode:
    alias: Movie Mode
    icon: mdi:movie
    sequence:
      - service: scene.turn_on
        entity_id: scene.movie_mode
      - service: script.living_room_tv_and_soundbar_on

  living_room_game_mode:
    alias: Game Mode
    icon: mdi:google-controller
    sequence:
      - service: scene.turn_on
        entity_id: scene.movie_mode # At least until I make a game mode scene.
      - service: script.living_room_tv_and_soundbar_on
      - delay: 00:00:02
      - service: media_player.select_source
        data:
          entity_id: media_player.65_tcl_roku_tv
          source: Switch
      - delay: 00:00:03 # Try a second time in case
      - service: media_player.select_source
        data:
          entity_id: media_player.65_tcl_roku_tv
          source: Switch

  # Other
  living_room_tv_and_soundbar_on:
    sequence:
      - service: switch.turn_on
        entity_id:
          - switch.living_room_tv_power # Turn on the TV.
          - switch.living_room_soundbar_power # And the soundbar.

automation:
  - alias: Send play/pause to Chromecast when selected
    trigger:
      - platform: state
        entity_id: binary_sensor.roku_remote_play_pause_button
        to: "on"
    condition:
      - condition: template
        value_template: >
          {{ is_state_attr('media_player.65_tcl_roku_tv', 'source', 'Chromecast') }}
    action:
      - service: media_player.media_play_pause
        data:
          entity_id: media_player.living_room_chromecast

  - alias: Switch the TV to the Chromecast when someone starts casting
    trigger:
      - platform: state
        entity_id: media_player.living_room_chromecast
        to: "idle"
      - platform: state
        entity_id: media_player.living_room_chromecast
        to: "playing"
    condition:
      - condition: template
        value_template: >
          {{ not is_state_attr('media_player.65_tcl_roku_tv', 'source', 'Chromecast') }}
    action:
      - service: media_player.select_source
        data:
          entity_id: media_player.65_tcl_roku_tv
          source: Chromecast
      - service: switch.turn_on
        entity_id:
          - switch.living_room_tv_power # No action if it's on.
          - switch.living_room_soundbar_power # No action if it's on.
      - service: media_player.select_source
        data:
          entity_id: media_player.65_tcl_roku_tv
          source: Chromecast
      - delay: 00:00:03 # Try a second time in case
      # TODO: Can you add a condition as a step in a script, so it stops here if the first attempt worked?
      - service: media_player.select_source
        data:
          entity_id: media_player.65_tcl_roku_tv
          source: Chromecast

homeassistant:
  customize:
    switch.living_room_tv_power:
      friendly_name: Living Room TV
      icon: mdi:television
    switch.living_room_soundbar_power:
      friendly_name: Soundbar Power
      icon: mdi:surround-sound
      assumed_state: true # Enable the separate buttons for on and off
