automation:
  - alias: Maggie Office Button - Click - Toggle Main Light
    id: 53398cd4-c8b8-44cd-8c7b-3b0e176144f5
    trigger:
      - platform: device
        domain: mqtt
        device_id: c0293035d2661c9c80bcd3643fa33a8a
        discovery_id: 0x00158d0006ba283b action_single
        type: action
        subtype: single
    action:
      - service: light.toggle
        entity_id: light.office_lamp

  - alias: Maggie Office Button - Double Click - Toggle Task Light
    id: 6883cc7e-425e-4855-b9bd-d4f5a32f88b8
    trigger:
      - platform: device
        domain: mqtt
        device_id: c0293035d2661c9c80bcd3643fa33a8a
        discovery_id: 0x00158d0006ba283b action_double
        type: action
        subtype: double
    action:
      - service: light.toggle
        entity_id: light.office_lamp_bottom

  - alias: Maggie Office Button - Hold - Toggle All Lights
    id: 64de12bd-58c8-42e4-9dee-a8b5cee3dcae
    trigger:
      - platform: device
        domain: mqtt
        device_id: c0293035d2661c9c80bcd3643fa33a8a
        discovery_id: 0x00158d0006ba283b action_hold
        type: action
        subtype: hold
    action:
      - alias: "If any light is on, turn all off. Otherwise, turn all on."
        choose:
          - conditions:
              - condition: state
                entity_id: group.maggies_office_lights
                state: "on"
            sequence:
              - service: homeassistant.turn_off
                target:
                  entity_id: group.maggies_office_lights
        default:
          - service: homeassistant.turn_on
            target:
              entity_id: group.maggies_office_lights
