automation:
  - id: 2cb23cab-a4a4-4e67-8af0-7bbe9ef1709d
    alias: Mail Reminder - Notify Maggie if there's mail
    trigger:
      - platform: state
        entity_id: person.maggie
        from: "L3Harris"
        to: "not_home"
    condition:
      - alias: "After 2 pm, to avoid alerting over lunch."
        condition: time
        after: "14:00:00"
      - condition: or
        conditions:
          - alias: "There is mail"
            condition: numeric_state
            entity_id: sensor.mail_usps_mail
            above: 0
          - alias: "There are packages"
            condition: numeric_state
            entity_id: sensor.mail_usps_delivered
            above: 0
    action:
      - alias: "Notify Maggie"
        service: notify.maggie
        data:
          title: "Check the Mail"
          message: >-
            Expecting {{states("sensor.mail_usps_mail")|int(0)}} {{ "" }}
            {%- if states("sensor.mail_usps_mail")|int(0) == 1 -%}
              piece of mail
            {%- else -%}
              pieces of mail
            {%- endif -%}
            {%- if states("sensor.mail_usps_delivered")|int(0) > 0 -%} {{ "" }}
            and {{states("sensor.mail_usps_delivered")|int(0)}} {{ "" }}
            {%- if states("sensor.mail_usps_mail")|int(0) == 1 -%}
              USPS package
            {%- else -%}
              USPS packages
            {%- endif -%}
            {%- endif -%}
            .
