# Package for the Master Play/Pause Control

script:
  play_pause_master:
    sequence:
      - service: media_player.media_play_pause
        entity_id:
          - media_player.kodi_obama
          - media_player.corban_and_maggie

homeassistant:
  customize:
    script.play_pause_master:
      friendly_name: "Master Play/Pause"
      icon: mdi:play-pause
