# Adding a motion-based night light in the bathroom.
# For the moment, this is a cheap night light plugged into a Zigbee outlet.
# In the future, this will be an LED string mounted near the vanity's kick plate.

automation:
  - id: 370ec425-d1e2-4db2-bb5e-001859cb176c
    alias: Master Bathroom - Motion Nightlight
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_motion_sensor_occupancy # Naming is wrong for now.
        from: "off"
        to: "on"
        id: "on"
      - platform: state
        entity_id: binary_sensor.kitchen_motion_sensor_occupancy
        to: "off"
        for:
          minutes: 2
        id: "off"
    condition:
      - alias: "Bathroom automations are not disabled"
        condition: state
        entity_id: input_boolean.room_exclude_bathrooms
        state: "off"
    action:
      - alias: "On or Off?"
        choose:
          - conditions: >-
              {{ trigger.id == "on" }}
            sequence:
              # TODO: Maybe only in "Sleep"?
              # TODO: Add time condition, or light level from the motion sensor?
              # - condition: state
              #   entity_id: input_select.home_mode
              #   state: "Home"
              - alias: "Turn on night light"
                service: switch.turn_on
                target:
                  entity_id: switch.master_bathroom_night_light
          - conditions: >-
              {{ trigger.id == "off" }}
            sequence:
              - alias: "Turn off night light"
                service: switch.turn_off
                target:
                  entity_id: switch.master_bathroom_night_light
