# Also configured the NZBGet integration in the UI.

input_select:
  download_speed:
    name: Download Speed Mode
    options:
      - Full Speed
      - Medium Speed
      - Slow Speed
      - Paused
    icon: mdi:speedometer

sensor:
  - platform: template
    sensors:
      download_speed_limit:
        friendly_name: Download Speed Limit
        unit_of_measurement: MB/s
        value_template: >-
          {% set e_id = "input_select.download_speed" %}
          {% if is_state(e_id, "Full Speed") %}
            N/A
          {% elif is_state(e_id, "Medium Speed") %}
            7
          {% elif is_state(e_id, "Slow Speed") %}
            1
          {% elif is_state(e_id, "Pause") %}
            0
          {% endif %}

input_boolean:
  download_mode_change_lock:
    name: Lock Download Speed Setting
    icon: mdi:download-lock

automation:
  - alias: Slow down downloading when someone is home
    trigger:
      - platform: state
        entity_id: input_boolean.home_occupied
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.download_mode_change_lock
        state: "off"
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.download_speed
          option: Slow Speed

  - alias: Run downloads at full speed when no one is home
    trigger:
      - platform: state
        entity_id: input_boolean.home_occupied
        to: "off"
    condition:
      - condition: state
        entity_id: input_boolean.download_mode_change_lock
        state: "off"
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.download_speed
          option: Full Speed

  - alias: Run downloads at full speed overnight
    trigger:
      # TODO: Consider adding a "night mode" that's activated by the bedside button/phone notification.
      - platform: time
        at: "23:30:00"
    condition:
      - condition: state
        entity_id: input_boolean.download_mode_change_lock
        state: "off"
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.download_speed
          option: Full Speed

  - alias: Run downloads at slow speed in the morning if someone is home
    trigger:
      - platform: time
        at: "06:00:00"
    condition:
      - condition: state
        entity_id: input_boolean.home_occupied
        state: "on"
      - condition: state
        entity_id: input_boolean.download_mode_change_lock
        state: "off"
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.download_speed
          option: Slow Speed

  - alias: Run downloads at medium speed after business hours
    trigger:
      - platform: time
        at: "18:00:00"
    condition:
      - condition: state
        entity_id: input_boolean.download_mode_change_lock
        state: "off"
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.download_speed
          option: Medium Speed

  # Set speed based on input_select

  - alias: Set download speed based on input_select - Full
    trigger:
      - platform: state
        entity_id: input_select.download_speed
        to: Full Speed
    action:
      - service: nzbget.resume
      - service: nzbget.set_speed
        data:
          speed: 0 # Unlimited

  - alias: Set download speed based on input_select - Medium
    trigger:
      - platform: state
        entity_id: input_select.download_speed
        to: Medium Speed
    action:
      - service: nzbget.resume
      - service: nzbget.set_speed
        data:
          speed: 7000 # KB/s

  - alias: Set download speed based on input_select - Slow
    trigger:
      - platform: state
        entity_id: input_select.download_speed
        to: Slow Speed
    action:
      - service: nzbget.resume
      - service: nzbget.set_speed
        data:
          speed: 1000 # KB/s

  - alias: Set download speed based on input_select - Paused
    trigger:
      - platform: state
        entity_id: input_select.download_speed
        to: Paused
    action:
      - service: nzbget.pause
