# Also configured the NZBGet integration in the UI.

input_select:
  download_speed:
    name: Download Speed Mode
    options:
      - Full Speed
      - Medium Speed
      - Slow Speed
      - Paused
    icon: mdi:speedometer

template:
  - sensor:
      - name: Download Speed Limit
        unit_of_measurement: MB/s
        default_entity_id: sensor.download_speed_limit
        availability: '{{ has_value("input_select.download_speed") }}'
        state: >-
          {% set e_id = "input_select.download_speed" %}
          {% if is_state(e_id, "Full Speed") %}
            N/A
          {% elif is_state(e_id, "Medium Speed") %}
            7
          {% elif is_state(e_id, "Slow Speed") %}
            1
          {% elif is_state(e_id, "Pause") %}
            0
          {% endif %}

input_boolean:
  download_mode_change_lock:
    name: Lock Download Speed Setting
    icon: mdi:download-lock

automation:
  - alias: Slow down downloading when someone arrives home
    id: f3a700e3-6a72-405e-b0c3-9297c2e59863
    triggers:
      - trigger: state
        entity_id: input_select.home_mode
        from:
          - "Away"
          - "Vacation"
        to: "Home"
    conditions:
      - condition: state
        entity_id: input_boolean.download_mode_change_lock
        state: "off"
    actions:
      - action: input_select.select_option
        data:
          entity_id: input_select.download_speed
          option: Slow Speed

  - alias: Run downloads at full speed when no one is home
    id: 9a369e71-6b1a-4ea3-ac23-3dfac244a9dc
    triggers:
      - trigger: state
        entity_id: input_select.home_mode
        to:
          - "Away"
          - "Vacation"
    conditions:
      - condition: state
        entity_id: input_boolean.download_mode_change_lock
        state: "off"
    actions:
      - action: input_select.select_option
        data:
          entity_id: input_select.download_speed
          option: Full Speed

  - alias: Run downloads at full speed when in sleep mode
    id: 0ba2ae8b-097e-48b0-aa3c-051e4a1c3ae2
    triggers:
      - trigger: state
        entity_id: input_select.home_mode
        to: "Sleep"
    conditions:
      - condition: state
        entity_id: input_boolean.download_mode_change_lock
        state: "off"
    actions:
      - action: input_select.select_option
        data:
          entity_id: input_select.download_speed
          option: Full Speed

  - alias: Run downloads at slow speed in the morning if someone is home
    id: 1e79b053-788e-4d87-9a06-e90453d2ed38
    triggers:
      - trigger: state
        entity_id: input_select.home_mode
        from: "Sleep"
        to: "Home"
    conditions:
      - condition: state
        entity_id: input_boolean.download_mode_change_lock
        state: "off"
    actions:
      - action: input_select.select_option
        data:
          entity_id: input_select.download_speed
          option: Slow Speed

  - alias: Run downloads at medium speed after business hours
    id: 59856c82-9e5a-492a-af7d-8cddca438fb3
    triggers:
      - trigger: time
        at: "18:00:00"
    conditions:
      - condition: state
        entity_id: input_boolean.download_mode_change_lock
        state: "off"
    actions:
      - action: input_select.select_option
        data:
          entity_id: input_select.download_speed
          option: Medium Speed

  - alias: Set download speed based on input_select
    id: 9a27930f-dd38-4a66-a7f1-85f7c600a89c
    triggers:
      - trigger: state
        entity_id: input_select.download_speed
    actions:
      - choose:
          - conditions: >
              {{ trigger.to_state.state == "Full Speed" }}
            sequence:
              - action: nzbget.resume
              - action: nzbget.set_speed
                data:
                  speed: 0 # Unlimited
          - conditions: >
              {{ trigger.to_state.state == "Medium Speed" }}
            sequence:
              - action: nzbget.resume
              - action: nzbget.set_speed
                data:
                  speed: 7000 # KB/s
          - conditions: >
              {{ trigger.to_state.state == "Slow Speed" }}
            sequence:
              - action: nzbget.resume
              - action: nzbget.set_speed
                data:
                  speed: 1000 # KB/s
          - conditions: >
              {{ trigger.to_state.state == "Paused" }}
            sequence:
              - action: nzbget.pause
