automation:
  - alias: "Notify if Nest goes offline"
    trigger:
      - platform: state
        entity_id: binary_sensor.hallway_thermostat_online
        to: "off"
    action:
      - service: notify.mobile_app_oneplus_a5000 # TODO: Extract the core stuff. Make a `notify.corban` just like `person.corban`.
        data:
          title: "Nest is Offline"
          message: "Might want to look into that."

homeassistant:
  customize:
    automation.notify_if_nest_goes_offline:
      icon: mdi:server-network
