automation:
  - alias: "Notify if Nest goes offline"
    trigger:
      - platform: state
        entity_id: binary_sensor.hallway_thermostat_online
        to: "off"
    action:
      - service: notify.html5_corban_phone
        data:
          title: "Nest is Offline"
          message: "Might want to look into that."

homeassistant:
  customize:
    automation.notify_if_nest_goes_offline:
      icon: mdi:server-network
