automation:
  - alias: Notify Corban if the network cabinet gets too hot
    trigger:
      - platform: numeric_state
        entity_id: sensor.network_cabinet_temperature
        above: 100 # °F
        for:
          minutes: 5
    action:
      service: notify.corban
      data:
        title: "Network Cabinet Too Hot"
      data_template:
        message: >
          The network cabinet is {{ states('sensor.network_cabinet_temperature') | round(1) }}°F.
          This exceeds the threshold of 100°F.
