automation:
  - alias: Notify Corban if the network closet gets too hot
    trigger:
      - platform: numeric_state
        entity_id: sensor.network_closet_temperature
        above: 90 # °F
        for:
          minutes: 5
    action:
      service: notify.corban
      data:
        title: "Network Closet Too Hot"
      data_template:
        message: >
          The network closet is {{ states('sensor.network_closet_temperature') | round(1) }}°F.
          This exceeds the threshold of 90°F.
