switch:
  - platform: template
    switches:
      obama:
        friendly_name: Obama
        icon_template: "mdi:desktop-tower"
        entity_id: "binary_sensor.obama_online"
        value_template: "{{ is_state('binary_sensor.obama_online', 'on') }}"
        turn_on:
          service: script.obama_wake
        turn_off:
          service: script.obama_sleep

binary_sensor:
  - platform: mqtt
    name: "Obama - Online"
    state_topic: "iotlink/workgroup/obama/lwt"
    value_template: "{{ value }}"
    payload_on: "ON"
    payload_off: "OFF"
    device_class: "connectivity"
    qos: 1

script:
  obama_wake:
    sequence:
      - service: wake_on_lan.send_magic_packet
        data:
          mac: !secret obama_mac
  obama_shutdown:
    alias: Shutdown Obama
    icon: mdi:power
    sequence:
      - service: mqtt.publish
        data:
          topic: "iotlink/workgroup/obama/commands/shutdown"
          payload: ""
  obama_sleep:
    sequence:
      - service: mqtt.publish
        data:
          topic: "iotlink/workgroup/obama/commands/suspend"
          payload: ""
