binary_sensor:
  - platform: octoprint
    monitored_conditions:
      - Printing
      - Printing Error


sensor:
  - platform: octoprint
    name: OctoPrint
    monitored_conditions:
      - Current State
      - Temperatures
      - Job Percentage


group:
  octoprint:
    name: OctoPrint
    icon: mdi:printer-3d
    control: hidden
    entities:
      - sensor.octoprint_current_state
      - sensor.octoprint_job_percentage
      - binary_sensor.octoprint_printing
      - binary_sensor.octoprint_printing_error
      - sensor.octoprint_actual_tool0_temp
      - sensor.octoprint_target_tool0_temp
      - sensor.octoprint_actual_bed_temp
      - sensor.octoprint_target_bed_temp


homeassistant:
  customize:
    binary_sensor.octoprint_printing:
      icon: mdi:printer-3d
      friendly_name: Printing
    binary_sensor.octoprint_printing_error:
      icon: mdi:printer-alert
      friendly_name: Print Error
    sensor.octoprint_actual_bed_temp:
      icon: mdi:oil-temperature
      friendly_name: Bed Temperature
    sensor.octoprint_actual_tool0_temp:
      icon: mdi:thermometer
      friendly_name: Extruder Temperature
    sensor.octoprint_current_state:
      icon: mdi:printer-3d
      friendly_name: Current State
    sensor.octoprint_job_percentage:
      icon: mdi:percent
      friendly_name: Percent Complete
    sensor.octoprint_target_bed_temp:
      icon: mdi:thermometer-lines
      friendly_name: Bed Target
    sensor.octoprint_target_tool0_temp:
      icon: mdi:thermometer-lines
      friendly_name: Extruder Target
