automation:
  - alias: Office Remote - Toggle
    trigger:
      - platform: device
        device_id: 66f76df28bdd462e84227f8f164ee7c3
        discovery_id: 0x90fd9ffffe886c5f action_toggle
        domain: mqtt
        type: action
        subtype: toggle
    action:
      - choose:
        # Lamp on, but office light off
        - conditions:
            - condition: state
              entity_id: light.office_lamp
              state: "on"
            - condition: state
              entity_id: light.office_video_light
              state: "off"
          sequence:
            - service: light.turn_on
              entity_id: light.office_video_light
              # data:
              #   brightness: 255 # Use previous setting for now.
        # Lamp and office light on
        - conditions:
            - condition: state
              entity_id: light.office_lamp
              state: "on"
            - condition: state
              entity_id: light.office_video_light
              state: "on"
          sequence:
            - service: light.turn_off
              entity_id: light.office_video_light
        # Lamp off
        - conditions:
            - condition: state
              entity_id: light.office_lamp
              state: "off"
          sequence:
            - service: light.turn_on
              entity_id: light.office_lamp
            - service: light.turn_on
              entity_id: light.office_video_light


  - alias: Office Remote - Brightness Up
    trigger:
      - platform: device
        device_id: 66f76df28bdd462e84227f8f164ee7c3
        discovery_id: 0x90fd9ffffe886c5f action_brightness_up_click
        domain: mqtt
        type: action
        subtype: brightness_up_click
    action:
      - service: light.turn_on
        entity_id: light.office_video_light
        data_template:
          # Handles the light being off as well, treating it as 0 brightness.
          brightness: >
            {%- set target = (is_state('light.office_video_light', "on") and state_attr('light.office_video_light', 'brightness')) | int + 40 -%}
            {%- if target > 255 -%}
              255
            {%- else -%}
              {{ target}}
            {%- endif -%}

  - alias: Office Remote - Brightness Down
    trigger:
      - platform: device
        device_id: 66f76df28bdd462e84227f8f164ee7c3
        discovery_id: 0x90fd9ffffe886c5f action_brightness_down_click
        domain: mqtt
        type: action
        subtype: brightness_down_click
    condition:
      - condition: state
        entity_id: light.office_video_light
        state: "on"
    action:
      - service: light.turn_on
        entity_id: light.office_video_light
        data_template:
          brightness: >
            {%- set target = state_attr('light.office_video_light', 'brightness') | int - 40 -%}
            {%- if target < 10 -%}
              10
            {%- else -%}
              {{ target}}
            {%- endif -%}

  - alias: Office Remote - Brightness Up Hold
    trigger:
      - platform: device
        device_id: 66f76df28bdd462e84227f8f164ee7c3
        discovery_id: 0x90fd9ffffe886c5f action_brightness_up_hold
        domain: mqtt
        type: action
        subtype: brightness_up_hold
    action:
      - service: light.turn_on
        entity_id: light.office_video_light
        data:
          brightness: 255

  - alias: Office Remote - Brightness Down Hold
    trigger:
      - platform: device
        device_id: 66f76df28bdd462e84227f8f164ee7c3
        discovery_id: 0x90fd9ffffe886c5f action_brightness_down_hold
        domain: mqtt
        type: action
        subtype: brightness_down_hold
    action:
      - service: light.turn_on
        entity_id: light.office_video_light
        data:
          brightness: 10

  - alias: Office Remote - Left Button Click - Toggle Plant Lamp
    trigger:
      - platform: device
        device_id: 66f76df28bdd462e84227f8f164ee7c3
        discovery_id: 0x90fd9ffffe886c5f action_arrow_left_click
        domain: mqtt
        type: action
        subtype: arrow_left_click
    action:
      - service: light.toggle
        entity_id: light.plant_lamp

  - alias: Office Remote - Right Button Click - Toggle Lamp
    trigger:
      - platform: device
        device_id: 66f76df28bdd462e84227f8f164ee7c3
        discovery_id: 0x90fd9ffffe886c5f action_arrow_right_click
        domain: mqtt
        type: action
        subtype: arrow_right_click
    action:
      - service: light.toggle
        entity_id: light.office_lamp
