# Using a mmWave sensor with ESPHome to determine the office occupancy and control lighting.

automation:
  - alias: Office Motion Lights - Set LEDs based on occupancy
    id: 3c42906d-db94-454e-8dc9-bc980e94223f
    trigger:
      - platform: state
        entity_id: binary_sensor.office_mini_motion_presence
    condition:
      - alias: "Home Mode"
        condition: state
        entity_id: input_select.home_mode
        state: "Home"
    action:
      - choose:
          - conditions: "{{ trigger.to_state.state == 'on' }}"
            sequence:
              - service: light.turn_on
                entity_id: light.office_leds
          - conditions: "{{ trigger.to_state.state == 'off' }}"
            sequence:
              - service: light.turn_off
                entity_id: light.office_leds
