# Outlet sensor system used in the office. See esphome/office_outlet_sensor.yaml.

automation:
  - alias: Office Light Switch - Toggle Office Light
    id: a8cad28a-ce45-43de-b2ec-f1479c9e9976
    trigger:
      - platform: state
        entity_id: binary_sensor.office_outlet_sensor
        from: "off"
        to: "on"
      - platform: state
        entity_id: binary_sensor.office_outlet_sensor
        from: "on"
        to: "off"
    action:
      - choose:
          # Off, turn on full brightness.
          - conditions:
              - condition: state
                entity_id: light.office_lamp
                state: "off"
            sequence:
              - service: light.turn_on
                entity_id: light.office_lamp
                data:
                  brightness: 255
          # On, turn off.
          - conditions:
              - condition: state
                entity_id: light.office_lamp
                state: "on"
            sequence:
              - service: homeassistant.turn_off
                target:
                  entity_id: group.office_lights
      - delay:
          milliseconds: 250
