automation:
  - alias: Office Single Button - Click - Toggle Main Light
    id: 99ea49dd-33a7-46e0-8e81-34fe2f5320f7
    trigger:
      - platform: device
        domain: mqtt
        device_id: bcf6893bbfd9aabd9be142a4af2db637
        discovery_id: 0x00158d0006ba4618 action_single
        type: action
        subtype: single
    action:
      - service: light.toggle
        entity_id: light.corban_s_office_ceiling_light

  - alias: Office Single Button - Double Click - Toggle Office LEDs
    id: f336a227-ebd1-4980-bdba-c14bcdf9dc8b
    trigger:
      - platform: device
        domain: mqtt
        device_id: bcf6893bbfd9aabd9be142a4af2db637
        discovery_id: 0x00158d0006ba4618 action_double
        type: action
        subtype: double
    action:
      - service: light.toggle
        entity_id: light.office_leds

  - alias: Office Single Button - Hold - Start Cycle
    id: 0a8f28e3-34c5-47ec-9dc7-06354d6d8470
    trigger:
      - platform: device
        domain: mqtt
        device_id: bcf6893bbfd9aabd9be142a4af2db637
        discovery_id: 0x00158d0006ba4618 action_hold
        type: action
        subtype: hold
    action:
      - service: script.brightness_cycle
        data:
          light_entity_id: light.tv_lamp

  - alias: Office Single Button - Release - Stop Cycle
    id: 4d4b8963-b9b0-424e-8b02-d1e1fe8e286b
    trigger:
      - platform: device
        domain: mqtt
        device_id: bcf6893bbfd9aabd9be142a4af2db637
        discovery_id: 0x00158d0006ba4618 action_release
        type: action
        subtype: release
    action:
      - service: script.turn_off
        entity_id: script.brightness_cycle

input_boolean:
  going_up:

script:
  brightness_cycle:
    mode: single
    description: "Cycle the brightness of a light until stopped"
    fields:
      light_entity_id:
        description: "The light to cycle."
        example: "light.office_lamp"
        required: true
        selector:
          entity:
            domain: light
    sequence:
      - variables:
          step_size: 15
          sleep_ms: 60
      - alias: "Cycle brightness for a long time. Stops after a while just in case."
        repeat:
          count: 100
          sequence:
            - variables:
                brightness: >
                  {% if is_state("input_boolean.going_up", "on") %}
                  {{ state_attr(light_entity_id, 'brightness') | int(0) + step_size }}
                  {% else %}
                  {{ state_attr(light_entity_id, 'brightness') | int(0) - step_size }}
                  {% endif %}
            - if:
                - "{{ brightness > 255 }}"
              then:
                - service: input_boolean.turn_off
                  entity_id: input_boolean.going_up
            - if:
                - "{{ brightness < 0 }}"
              then:
                - service: input_boolean.turn_on
                  entity_id: input_boolean.going_up
            - variables:
                brightness: >
                  {% if brightness > 255 %}
                  {{ 255 - step_size }}
                  {% elif brightness < 0 %}
                  {{ step_size }}
                  {% else %}
                  {{ brightness }}
                  {% endif %}
            - service: light.turn_on
              target:
                entity_id: "{{ light_entity_id }}"
              data_template:
                brightness: >
                  {{ brightness }}
                # transition: 1
            - delay:
                milliseconds: "{{ sleep_ms }}"
