automation:
  - alias: Office Remote - Toggle
    trigger:
      - platform: device
        device_id: 66f76df28bdd462e84227f8f164ee7c3
        discovery_id: 0x90fd9ffffe886c5f action_toggle
        domain: mqtt
        type: action
        subtype: toggle
    action:
      - service: light.toggle
        entity_id: light.office_lamp_bottom

  - alias: Office Remote - Brightness Up
    trigger:
      - platform: device
        device_id: 66f76df28bdd462e84227f8f164ee7c3
        discovery_id: 0x90fd9ffffe886c5f action_brightness_up_click
        domain: mqtt
        type: action
        subtype: brightness_up_click
    action:
      - choose:
          # If the bottom light is on, control it directly.
          - conditions:
              - condition: state
                entity_id: light.office_lamp_bottom
                state: "on"
            sequence:
              - service: light.turn_on
                entity_id: light.office_lamp_bottom
                data_template:
                  brightness: >
                    {%- set target = state_attr('light.office_lamp_bottom', 'brightness') | int + 40 -%}
                    {%- if target > 255 -%}
                      255
                    {%- else -%}
                      {{ target}}
                    {%- endif -%}
          # If the bottom light is off, control the lamp as a whole.
          - conditions:
              - condition: state
                entity_id: light.office_lamp_bottom
                state: "off"
            sequence:
              - service: light.turn_on
                entity_id: light.office_lamp
                data_template:
                  # Handles the light being off as well, treating it as 0 brightness.
                  brightness: >
                    {%- set target = (is_state('light.office_lamp', "on") and state_attr('light.office_lamp', 'brightness')) | int + 40 -%}
                    {%- if target > 255 -%}
                      255
                    {%- else -%}
                      {{ target}}
                    {%- endif -%}

  - alias: Office Remote - Brightness Down
    trigger:
      - platform: device
        device_id: 66f76df28bdd462e84227f8f164ee7c3
        discovery_id: 0x90fd9ffffe886c5f action_brightness_down_click
        domain: mqtt
        type: action
        subtype: brightness_down_click
    action:
      - choose:
          # If the bottom light is on, control it directly.
          - conditions:
              - condition: state
                entity_id: light.office_lamp_bottom
                state: "on"
            sequence:
              - service: light.turn_on
                entity_id: light.office_lamp_bottom
                data_template:
                  brightness: >
                    {%- set target = state_attr('light.office_lamp_bottom', 'brightness') | int - 40 -%}
                    {%- if target < 10 -%}
                      10
                    {%- else -%}
                      {{ target}}
                    {%- endif -%}
          # If the bottom light is off, control the lamp as a whole.
          - conditions:
              - condition: state
                entity_id: light.office_lamp_bottom
                state: "off"
            sequence:
              - service: light.turn_on
                entity_id: light.office_lamp
                data_template:
                  brightness: >
                    {%- set target = state_attr('light.office_lamp', 'brightness') | int - 40 -%}
                    {%- if target < 10 -%}
                      10
                    {%- else -%}
                      {{ target}}
                    {%- endif -%}

  - alias: Office Remote - Brightness Up Hold
    trigger:
      - platform: device
        device_id: 66f76df28bdd462e84227f8f164ee7c3
        discovery_id: 0x90fd9ffffe886c5f action_brightness_up_hold
        domain: mqtt
        type: action
        subtype: brightness_up_hold
    action:
      - service: light.turn_on
        entity_id: light.office_lamp_bottom
        data:
          brightness: 255

  - alias: Office Remote - Brightness Down Hold
    trigger:
      - platform: device
        device_id: 66f76df28bdd462e84227f8f164ee7c3
        discovery_id: 0x90fd9ffffe886c5f action_brightness_down_hold
        domain: mqtt
        type: action
        subtype: brightness_down_hold
    action:
      - service: light.turn_on
        entity_id: light.office_lamp_bottom
        data:
          brightness: 10

  - alias: Office Remote - Left Button Click - Toggle Plant Lamp
    trigger:
      - platform: device
        device_id: 66f76df28bdd462e84227f8f164ee7c3
        discovery_id: 0x90fd9ffffe886c5f action_arrow_left_click
        domain: mqtt
        type: action
        subtype: arrow_left_click
    action:
      - service: light.toggle
        entity_id: light.plant_lamp

  - alias: Office Remote - Left Button Hold - Toggle Fan
    trigger:
      - platform: device
        device_id: 66f76df28bdd462e84227f8f164ee7c3
        discovery_id: 0x90fd9ffffe886c5f action_arrow_left_hold
        domain: mqtt
        type: action
        subtype: arrow_left_hold
    action:
      - service: fan.toggle
        entity_id: fan.office_fan

  - alias: Office Remote - Right Button Click - Toggle Lamp
    trigger:
      - platform: device
        device_id: 66f76df28bdd462e84227f8f164ee7c3
        discovery_id: 0x90fd9ffffe886c5f action_arrow_right_click
        domain: mqtt
        type: action
        subtype: arrow_right_click
    action:
      - service: light.toggle
        data:
          entity_id: light.office_lamp
          brightness: 255

  - alias: Office Remote - Right Button Hold - Toggle PTZ Camera
    trigger:
      - platform: device
        device_id: 66f76df28bdd462e84227f8f164ee7c3
        discovery_id: 0x90fd9ffffe886c5f action_arrow_right_hold
        domain: mqtt
        type: action
        subtype: arrow_right_hold
    action:
      - service: switch.toggle
        entity_id: switch.ptz_camera # Template switch. See `office_ptz_camera` package.
