# OpenHASP

openhasp:
  office_plate:
    objects:
      # All Pages: Header
      # Clock, also refresh button
      - obj: "p0b1"
        properties:
          "text": '{{ as_timestamp(now())|timestamp_custom("%I:%M") }}'
        event:
          "down":
            - service: script.reload_openhasp

      # Status Message
      - obj: "p0b2"
        properties:
          "text": >-
            {% if is_state('input_boolean.wall_display_show_map', 'on') %}
              {{ states('sensor.maggie_time_to_home_for_display') }} minutes away
            {% elif is_state('binary_sensor.corban_on_a_call', 'on') %}
              {% if is_state('binary_sensor.cmaillouxtjq31_camera_in_use', 'on') -%}
                #FF0000 {{ "\uE7AE" | e }}#
              {%- endif %} In a Meeting
            {% else %}
              #AAAAAA Hello there!#
            {% endif %}

      # Page 1: Main Buttons
      - obj: "p1b111" # LEDs
        properties:
          "val": '{{ 1 if is_state("light.office_leds", "on") else 0 }}'
          # "text": '{{ "\uE6E8" if is_state("light.office_leds", "on") else "\uE335" | e }}'
        event:
          "down":
            - service: homeassistant.toggle
              entity_id: "light.office_leds"

      - obj: "p1b112" # Main Light
        properties:
          "val": '{{ 1 if is_state("light.corban_s_office_lamp", "on") else 0 }}'
          "text": '{{ "\uE6E8" if is_state("light.corban_s_office_lamp", "on") else "\uE335" | e }}'
        event:
          "down":
            - service: homeassistant.toggle
              entity_id: light.corban_s_office_lamp

      - obj: "p1b113" # Key Light - Left
        properties:
          "val": '{{ 1 if is_state("light.key_light_air_1", "on") else 0 }}'
        event:
          "down":
            - service: homeassistant.toggle
              entity_id: light.key_light_air_1

      - obj: "p1b114" # Video Light - Right
        properties:
          "val": '{{ 1 if is_state("light.corban_s_office_lamp_bottom", "on") else 0 }}'
        event:
          "down":
            - service: homeassistant.toggle
              entity_id: light.corban_s_office_lamp_bottom

      # - obj: "p1b115" # Camera Preset 1
      #   event:
      #     "down":
      #       - service: button.press
      #         entity_id: button.ptz_preset_1

      # - obj: "p1b116" # Camera Preset 2
      #   event:
      #     "down":
      #       - service: button.press
      #         entity_id: button.ptz_preset_2

      - obj: "p1b118" # Fan, with temperature labels on it
        properties:
          "val": '{{ 1 if is_state("fan.office_fan", "on") else 0 }}'
        event:
          "down":
            - service: homeassistant.toggle
              entity_id: fan.office_fan
      - obj: "p1b108"
        properties:
          "text": >-
            {{ "\uE50F" | e }} {{ states("sensor.office_temperature") | round(1) }}°
      - obj: "p1b198"
        properties:
          "text": >-
            {{ "\uE590" | e }} {{ states("sensor.openweathermap_temperature") | round(1) }}°

script:
  reload_openhasp:
    alias: "Reload openHASP"
    sequence:
      # - service: openhasp.clear_page
      #   target:
      #     entity_id: openhasp.office_plate
      - service: homeassistant.reload_config_entry
        data:
          entry_id: 062b4ea304da0c553c602f0d6a8fe840

automation:
  - alias: Office Plate - Set screen based on occupancy
    id: ac6c94f9-d216-4e4f-adb0-95dbdc8e78d7
    trigger:
      - platform: state
        entity_id: binary_sensor.office_mini_motion_presence
    condition:
      - alias: "Home Mode"
        condition: state
        entity_id: input_select.home_mode
        state: "Home"
    action:
      - choose:
          - conditions: "{{ trigger.to_state.state == 'on' }}"
            sequence:
              - service: mqtt.publish
                data:
                  topic: hasp/office_plate/command/p0b99.hidden
                  payload: "1"
              - service: mqtt.publish
                data:
                  topic: hasp/office_plate/command/p0b99.delete
                  payload: ""
              - service: light.turn_on
                entity_id: light.office_plate_backlight
          - conditions: "{{ trigger.to_state.state == 'off' }}"
            sequence:
              - service: light.turn_off
                entity_id: light.office_plate_backlight
              - service: mqtt.publish
                data:
                  topic: hasp/office_plate/command/jsonl
                  payload: '{"page":0,"id":99,"obj":"obj","x":0,"y":0,"w":320,"h":240,"radius":0,"hidden":0,"bg_grad_dir":0,"bg_color":"black","border_color":"black"}'

  - alias: Office Plate - Run anti-burn in at night
    id: 9bf8f7cc-185a-4568-8c84-a68c470d0a9d
    trigger:
      - platform: time
        at: "01:20:00"
      - platform: time
        at: "02:20:00"
      - platform: time
        at: "03:20:00"
      - platform: time
        at: "04:20:00"
    condition:
      not:
        - alias: "Not home (sleep, away, vacation)"
          condition: state
          entity_id: input_select.home_mode
          state: "Home"
    action:
      - service: mqtt.publish
        data:
          topic: hasp/office_plate/command/antiburn
          payload: "1"
