# Add a simple scraper sensor for the number of packages waiting in our package lockers for the members of the household.
# See https://github.com/corbanmailloux/home-assistant-configuration/tree/master/custom_components/package_concierge

sensor:
  - platform: package_concierge
    name: Packages for Corban
    username: !secret package_concierge_corban_username
    password: !secret package_concierge_corban_password
  - platform: package_concierge
    name: Packages for Maggie
    username: !secret package_concierge_maggie_username
    password: !secret package_concierge_maggie_password

automation:
  - alias: Update package sensors when the door opens
    id: 2a77a2b9-e64d-4a5a-b41d-69524c6a1db2
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door
        to: "on"
    action:
      - service: script.update_package_sensors

script:
  update_package_sensors:
    alias: "Update Package Sensors"
    sequence:
      - service: homeassistant.update_entity
        data:
          entity_id:
            - sensor.packages_for_corban
            - sensor.packages_for_maggie
