# Add a simple scraper sensor for the number of packages waiting in our package lockers for the members of the household.
# See https://github.com/corbanmailloux/home-assistant-configuration/tree/master/custom_components/package_concierge

sensor:
  - platform: package_concierge
    name: package_concierge_corban
    username: !secret package_concierge_corban_username
    password: !secret package_concierge_corban_password
  - platform: package_concierge
    name: package_concierge_maggie
    username: !secret package_concierge_maggie_username
    password: !secret package_concierge_maggie_password
