# Package for Party Mode
# See also:
#  - packages/exit_sign.yaml: "Exit Sign Button - Toggle Party Mode"

input_boolean:
  party_mode:
    name: Party Mode
    initial: off
    icon: mdi:bomb


automation:
  - alias: "Party Mode - On"
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_boolean.party_mode
        to: "on"
    action:
      - service: script.turn_on
        entity_id: script.party_mode

  - alias: "Party Mode - Off"
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_boolean.party_mode
        to: "off"
    action:
      - service: script.turn_on
        entity_id: script.party_mode_end


script:
  # Kick off party mode!
  party_mode:
    sequence:
      - service: script.turn_on
        entity_id:
          - script.fade_backlight
          - script.blink_exit_sign
          - script.toggle_lamps

  # End party mode and reset
  party_mode_end:
    sequence:
      - service: script.turn_off
        entity_id:
          - script.party_mode
          - script.fade_backlight
          - script.fade_backlight_loop
          - script.blink_exit_sign
          - script.blink_exit_sign_loop
          - script.toggle_lamps
          - script.toggle_lamps_loop
      # Reset the lights
      - service: light.turn_on # Reset the brightness
        data:
          entity_id:
            - light.living_room_tv_backlight
            - light.exit_sign
          brightness: 255
      - service: homeassistant.turn_off
        entity_id:
          - light.living_room_tv_backlight
          - light.exit_sign
      - service: homeassistant.turn_on
        entity_id:
          - group.living_room_lights

  # TV Backlight Party Mode
  fade_backlight:
    sequence:
      - service: light.turn_on
        data:
          entity_id: light.living_room_tv_backlight
          rgb_color: [255, 0, 0]
          brightness: 255
          transition: 2
      - delay: 00:00:02
      - service: light.turn_on
        data:
          entity_id: light.living_room_tv_backlight
          rgb_color: [0, 255, 0]
          transition: 2
      - delay: 00:00:02
      - service: light.turn_on
        data:
          entity_id: light.living_room_tv_backlight
          rgb_color: [0, 0, 255]
          transition: 2
      - service: script.turn_on
        entity_id: script.fade_backlight_loop

  fade_backlight_loop:
    sequence:
      - delay: 00:00:02
      - service: script.turn_on
        entity_id: script.fade_backlight

  # Exit Sign Party Mode
  blink_exit_sign:
    sequence:
      - service: light.turn_on
        data:
          entity_id: light.exit_sign
          brightness: 255
          transition: 1
      - delay: 00:00:01
      - service: light.turn_on
        data:
          entity_id: light.exit_sign
          brightness: 1 # Effectively off
          transition: 1
      - service: script.turn_on
        entity_id: script.blink_exit_sign_loop

  blink_exit_sign_loop:
    sequence:
      - delay: 00:00:01
      - service: script.turn_on
        entity_id: script.blink_exit_sign

  # Toggle the living room lamps
  toggle_lamps:
    sequence:
      - service: switch.turn_on
        entity_id:
          - switch.living_room_corner
          - switch.living_room_lamp_near_tv
      - service: switch.turn_off
        entity_id:
          - switch.living_room_window
          - switch.living_room_couch
      - delay: 00:00:02
      - service: switch.turn_off
        entity_id:
          - switch.living_room_corner
          - switch.living_room_lamp_near_tv
      - service: switch.turn_on
        entity_id:
          - switch.living_room_window
          - switch.living_room_couch
      - service: script.turn_on
        entity_id: script.toggle_lamps_loop

  toggle_lamps_loop:
    sequence:
      - delay: 00:00:02
      - service: script.turn_on
        entity_id: script.toggle_lamps


homeassistant:
  customize:
    input_boolean.party_mode:
      emulated_hue: true
      emulated_hue_name: "Party mode"
