# When the front door is opened, if a phone isn't already marked as home, trigger a location update.
# This is helpful because occasionally the Home Assistant iOS app will update the location to
# just outside the home radius, but then coming inside doesn't count as a significant location change.
# This leaves the device stuck as "not home" until manually refreshed.

automation:
  - alias: Door opened - Trigger phone location updates
    id: 85f0013d-587a-444c-a7c9-9b427a99d335
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door
        to: "on"
      - platform: state
        entity_id:
          - cover.left_garage_door
          - cover.right_garage_door
        to: "opening"
    action:
      - choose:
          - alias: "If Maggie isn't home, trigger an update."
            conditions:
              - condition: state
                entity_id: binary_sensor.maggie_person_home
                state: "off"
            sequence:
              - service: script.request_maggie_location_update
      - choose:
          - alias: "If Corban isn't home, trigger an update."
            conditions:
              - condition: state
                entity_id: binary_sensor.corban_person_home
                state: "off"
            sequence:
              - service: script.request_corban_location_update

script:
  request_maggie_location_update:
    alias: "Request a location update from Maggie's phone"
    sequence:
      - service: notify.maggie
        data:
          message: "request_location_update"

  request_corban_location_update:
    alias: "Request a location update from Corban's phone"
    sequence:
      - service: notify.corban
        data:
          message: "request_location_update"
