automation:
  - alias: "Set Corban's Phone Location - Webhook"
    trigger:
      - platform: webhook
        webhook_id: !secret edith_wifi_location_webhook
    action:
      - service: mqtt.publish
        data_template:
          topic: !secret edith_wifi_mqtt_topic
          retain: true
          payload: '{{ trigger.json.location }}'
  - alias: "Set Maggie's Phone Location - Webhook"
    trigger:
      - platform: webhook
        webhook_id: !secret jackie_wifi_location_webhook
    action:
      - service: mqtt.publish
        data_template:
          topic: !secret jackie_wifi_mqtt_topic
          retain: true
          payload: '{{ trigger.json.location }}'
