automation:
  - alias: "Set Corban's Phone Location - Webhook"
    trigger:
      - platform: webhook
        webhook_id: !secret edith_wifi_location_webhook
    action:
      - service: mqtt.publish
        data_template:
          topic: !secret edith_wifi_mqtt_topic
          retain: true
          payload: '{{ trigger.json.location }}'
  - alias: "Set Maggie's Phone Location - Webhook"
    trigger:
      - platform: webhook
        webhook_id: !secret jackie_wifi_location_webhook
    action:
      - service: mqtt.publish
        data_template:
          topic: !secret jackie_wifi_mqtt_topic
          retain: true
          payload: '{{ trigger.json.location }}'

group:
  corban_home:
    name: Corban
    icon: mdi:home-account
    entities:
      - device_tracker.google_maps_110168280884137709870
      - device_tracker.edith_wifi
  maggie_home:
    name: Maggie
    icon: mdi:home-account
    entities:
      - device_tracker.google_maps_106112096418399445974
      - device_tracker.jackie_wifi

binary_sensor:
  - platform: template
    sensors:
      corban_home_gps:
        friendly_name: "Corban Home - GPS"
        device_class: presence
        value_template: >-
          {{ is_state('device_tracker.google_maps_110168280884137709870', 'home') }}
      corban_home_wifi:
        friendly_name: "Corban Home - WiFi"
        device_class: presence
        value_template: >-
          {{ is_state('device_tracker.edith_wifi', 'home') }}
      corban_home:
        friendly_name: "Corban Home"
        device_class: presence
        value_template: >-
          {{ is_state('binary_sensor.corban_home_wifi', 'on') or is_state('binary_sensor.corban_home_gps', 'on') }}
      maggie_home_gps:
        friendly_name: "Maggie Home - GPS"
        device_class: presence
        value_template: >-
          {{ is_state('device_tracker.google_maps_106112096418399445974', 'home') }}
      maggie_home_wifi:
        friendly_name: "Maggie Home - WiFi"
        device_class: presence
        value_template: >-
          {{ is_state('device_tracker.jackie_wifi', 'home') }}
      maggie_home:
        friendly_name: "Maggie Home"
        device_class: presence
        value_template: >-
          {{ is_state('binary_sensor.maggie_home_wifi', 'on') or is_state('binary_sensor.maggie_home_gps', 'on') }}

sensor:
  - platform: template
    sensors:
      corban_phone_battery:
        friendly_name: "Corban's Phone Battery"
        device_class: battery
        unit_of_measurement: '%'
        entity_id: 'device_tracker.google_maps_110168280884137709870'
        icon_template: >-
          {%- set tracker_name = 'device_tracker.google_maps_110168280884137709870' -%}

          {%- set battery_level = state_attr(tracker_name, 'battery_level') -%}
          {%- set battery_charging = state_attr(tracker_name, 'battery_charging') -%}

          {%- if battery_level is none -%}
            mdi:battery-unknown
          {%- else -%}
            {%- set icon_suffix = ['-outline', '-10', '-20', '-30', '-40', '-50', '-60', '-70', '-80', '-90', ''] -%}
            {%- set charge = (battery_level | float / 10) | round -%}
            mdi:battery{%- if battery_charging -%}-charging{%- endif -%}{{ icon_suffix[charge] }}
          {%- endif -%}
        value_template: >-
          {{ state_attr('device_tracker.google_maps_110168280884137709870', 'battery_level') }}
      maggie_phone_battery:
        friendly_name: "Maggie's Phone Battery"
        device_class: battery
        unit_of_measurement: '%'
        entity_id: 'device_tracker.google_maps_106112096418399445974'
        icon_template: >-
          {%- set tracker_name = 'device_tracker.google_maps_106112096418399445974' -%}

          {%- set battery_level = state_attr(tracker_name, 'battery_level') -%}
          {%- set battery_charging = state_attr(tracker_name, 'battery_charging') -%}

          {%- if battery_level is none -%}
            mdi:battery-unknown
          {%- else -%}
            {%- set icon_suffix = ['-outline', '-10', '-20', '-30', '-40', '-50', '-60', '-70', '-80', '-90', ''] -%}
            {%- set charge = (battery_level | float / 10) | round -%}
            mdi:battery{%- if battery_charging -%}-charging{%- endif -%}{{ icon_suffix[charge] }}
          {%- endif -%}
        value_template: >-
          {{ state_attr('device_tracker.google_maps_106112096418399445974', 'battery_level') }}
