automation:
  - alias: "Set Corban's Phone Location - Webhook"
    trigger:
      - platform: webhook
        webhook_id: !secret edith_wifi_location_webhook
    action:
      - service: mqtt.publish
        data_template:
          topic: !secret edith_wifi_mqtt_topic
          retain: true
          payload: "{{ trigger.json.location }}"
  - alias: "Set Maggie's Phone Location - Webhook"
    trigger:
      - platform: webhook
        webhook_id: !secret jackie_wifi_location_webhook
    action:
      - service: mqtt.publish
        data_template:
          topic: !secret jackie_wifi_mqtt_topic
          retain: true
          payload: "{{ trigger.json.location }}"

binary_sensor:
  - platform: template
    sensors:
      # Used for the UI
      corban_person_home:
        friendly_name: "Corban Home"
        device_class: presence
        value_template: >-
          {{ is_state('person.corban', 'home') }}
      maggie_person_home:
        friendly_name: "Maggie Home"
        device_class: presence
        value_template: >-
          {{ is_state('person.maggie', 'home') }}

      corban_home_google:
        friendly_name: "Corban Home - GPS"
        device_class: presence
        value_template: >-
          {{ is_state('device_tracker.google_maps_110168280884137709870', 'home') }}
      maggie_home_google:
        friendly_name: "Maggie Home - GPS"
        device_class: presence
        value_template: >-
          {{ is_state('device_tracker.google_maps_106112096418399445974', 'home') }}

sensor:
  - platform: template
    sensors:
      corban_location_icon:
        friendly_name: Corban's Location
        entity_id: person.corban
        icon_template: >-
          {% set state = states('person.corban') %}

          {% if state == "home" %}
            mdi:home
          {% elif state == "BKB" %}
            mdi:dumbbell
          {% elif state == "CHT" %}
            mdi:laptop
          {% elif state == "RE" %}
            mdi:flask-outline
          {% else %}
            mdi:account-outline
          {% endif %}
        value_template: >-
          {{ states('person.corban') }}

      maggie_location_icon:
        friendly_name: Maggie's Location
        entity_id: person.maggie
        icon_template: >-
          {% set state = states('person.maggie') %}

          {% if state == "home" %}
            mdi:home
          {% elif state == "BKB" %}
            mdi:dumbbell
          {% elif state == "CHT" %}
            mdi:laptop
          {% elif state == "RE" %}
            mdi:flask-outline
          {% else %}
            mdi:account-outline
          {% endif %}
        value_template: >-
          {{ states('person.maggie') }}
