scene:
  - id: "1636344043604"
    name: Training
    entities:
      light.corner_lamp:
        brightness: 255
        state: "on"
      light.corban_s_office_ceiling_light:
        brightness: 255
        state: "on"
      light.office_lamp:
        brightness: 255
        state: "on"
      light.office_lamp_bottom:
        brightness: 255
        state: "on"
      light.kitchen_counter_lights:
        state: "on"
    icon: mdi:trophy-outline
  - id: "3b6fa32e-5670-4c39-a48f-b41b1ddcabd1"
    name: Training - No Guest Room
    entities:
      light.corner_lamp:
        brightness: 255
        state: "on"
      # light.corban_s_office_ceiling_light:
      #   brightness: 255
      #   state: "on"
      light.office_lamp:
        brightness: 255
        state: "on"
      light.office_lamp_bottom:
        brightness: 255
        state: "on"
      light.kitchen_counter_lights:
        state: "on"
    icon: mdi:trophy-outline

input_boolean:
  training_mode:
    name: Training
    icon: mdi:trophy-outline

automation:
  - alias: Training Mode Start
    id: 0306466a-8dab-4d80-b814-d0b5a7d97f31
    trigger:
      - platform: state
        entity_id: input_boolean.training_mode
        to: "on"
    action:
      - if:
          - alias: "Guest Mode On"
            condition: state
            entity_id: input_boolean.guest_mode
            state: "on"
        then:
          - alias: "Create scene with all impacted lights except guest room"
            service: scene.create
            data:
              scene_id: state_before_training
              snapshot_entities:
                - light.corner_lamp
                # - light.corban_s_office_ceiling_light
                - light.office_lamp
                - light.office_lamp_bottom
                - light.kitchen_counter_lights
          - service: scene.turn_on
            target:
              entity_id: scene.training_no_guest_room
        else:
          - alias: "Create scene with all impacted lights"
            service: scene.create
            data:
              scene_id: state_before_training
              snapshot_entities:
                - light.corner_lamp
                - light.corban_s_office_ceiling_light
                - light.office_lamp
                - light.office_lamp_bottom
                - light.kitchen_counter_lights
          - service: scene.turn_on
            target:
              entity_id: scene.training

  - alias: Training Mode Stop
    id: 6c0d187b-c08f-4e96-a602-1dd87e972df6
    trigger:
      - platform: state
        entity_id: input_boolean.training_mode
        to: "off"
    action:
      - service: scene.turn_on
        target:
          entity_id: scene.state_before_training
      - alias: "Clear notification"
        service: notify.corban
        data:
          message: "clear_notification"
          data:
            tag: "training_mode_left_on"

  - alias: Training Mode Left On Notification
    id: 1a38b478-549d-4d84-9a00-8c1ce37bddea
    trigger:
      - platform: state
        entity_id: input_boolean.training_mode
        to: "on"
        for:
          minutes: 15
    action:
      - alias: "Notify Corban"
        service: notify.corban
        data:
          title: "Training Mode Reminder"
          message: "Training mode is still on. Turn off?"
          data:
            tag: "training_mode_left_on"
            actions:
              - action: "TRAINING_TURN_OFF"
                title: "Turn off."
                activationMode: "background"
                authenticationRequired: false # Don't require unlocking the device
                destructive: false
                behavior: "default"

  - alias: Training Mode Left On - Notification Action
    id: 40261cea-1c15-4dfc-b795-ce11a932e394
    trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: "TRAINING_TURN_OFF"
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.training_mode
