scene:
  - id: "1636344043604"
    name: Training
    entities:
      light.tv_lamp:
        brightness: 255
        state: "on"
      light.corban_s_office_ceiling_light:
        brightness: 255
        state: "on"
      light.office_lamp:
        brightness: 255
        state: "on"
    icon: mdi:trophy-outline

input_boolean:
  training_mode:
    name: Training
    icon: mdi:trophy-outline

automation:
  - alias: Training Mode Start
    id: 0306466a-8dab-4d80-b814-d0b5a7d97f31
    trigger:
      - platform: state
        entity_id: input_boolean.training_mode
        to: "on"
    action:
      - service: scene.create
        data:
          scene_id: state_before_training
          snapshot_entities:
            - light.tv_lamp
            - light.corban_s_office_ceiling_light
            - light.office_lamp
      - service: scene.turn_on
        target:
          entity_id: scene.training

  - alias: Training Mode Stop
    id: 6c0d187b-c08f-4e96-a602-1dd87e972df6
    trigger:
      - platform: state
        entity_id: input_boolean.training_mode
        to: "off"
    action:
      - service: scene.turn_on
        target:
          entity_id: scene.state_before_training

# TODO: This might need a way to automatically turn back off if a light is manually adjusted.
# Otherwise, the next time I toggle it, it will actually reset to the previous time's lighting.