script:
  maggie_travel_time_send:
    description: "Notify Corban that Maggie's Almost Home"
    fields:
      dismiss_notification:
        description: "true to dismiss the notification"
        example: "true"
    sequence:
      - if:
          - "{{ dismiss_notification == true }}"
        then:
          - action: notify.corban
            data:
              message: clear_notification
              data:
                tag: "maggie_home_warning"
        else:
          - action: notify.corban
            data:
              title: "Maggie's Almost Home"
              message: "She's less than 10 minutes away." # TODO: Could I have this notification silently updated every couple minutes to show the current time?
              data:
                tag: "maggie_home_warning"
                push:
                  sound: "US-EN-Alexa-Wife-Is-Arriving.wav"

automation:
  - alias: Notify Corban when Maggie is almost home
    id: 5277f05f-3f90-4eb7-8ba2-973a54482623
    triggers:
      - trigger: numeric_state
        entity_id: sensor.maggie_to_home_travel_time
        below: 11
    conditions:
      - condition: state
        entity_id: person.corban
        state: "home"
      - condition: state
        entity_id: person.maggie
        state: "not_home" # Only run if Maggie isn't home or another named zone.
      - condition: state
        entity_id: timer.maggie_home_notification_cooldown
        state: idle
      - condition: time # From 7AM - 9PM
        after: "07:00:00"
        before: "21:00:00"
      - condition: state
        entity_id: input_select.home_mode
        state: "Home"
    actions:
      - alias: "Notify Corban"
        action: script.maggie_travel_time_send
        data:
          dismiss_notification: false
      - action: timer.start
        entity_id: timer.maggie_home_notification_cooldown
        data:
          duration: "00:10:00" # 10 minute cooldown before retriggering.

  - id: 380345d6-b3ab-4cc1-908d-741051bb8ccf
    alias: Dismiss the notification after Maggie arrives
    triggers:
      - trigger: state
        entity_id: person.maggie
        to: "home"
        for:
          minutes: 1
    actions:
      - alias: "Dismiss notification"
        action: script.maggie_travel_time_send
        data:
          dismiss_notification: true

timer:
  maggie_home_notification_cooldown:

homeassistant:
  customize:
    sensor.maggie_to_home_travel_time:
      icon: mdi:map-marker-distance
