sensor:
  - platform: waze_travel_time
    name: 'Maggie to Home Travel Time'
    origin: device_tracker.google_maps_106112096418399445974
    destination: zone.home
    region: 'US'

group:
  maggie_travel_time:
    name: "Maggie Travel Time"
    control: hidden
    entities:
      - sensor.maggie_to_home_travel_time
      - script.maggie_travel_time_speak

script:
  maggie_travel_time_speak:
    sequence:
      - delay:
          seconds: 5
      - service: tts.google_say
        entity_id: media_player.everything
        data_template:
          message: >-
            {%- set minutes = states('sensor.maggie_to_home_travel_time') -%}
            Maggie is {{ minutes }} minute{% if minutes != 1 %}s{% endif %} away.

homeassistant:
  customize:
    sensor.maggie_to_home_travel_time:
      icon: mdi:map-marker-distance
    script.maggie_travel_time_speak:
      friendly_name: Announce Maggie's Travel Time
      icon: mdi:voice
