script:
  maggie_travel_time_send:
    alias: "Notify Corban that Maggie's Almost Home"
    sequence:
      - service: notify.corban
        data:
          title: "Maggie's Almost Home"
          message: "She's less than 10 minutes away." # TODO: Could I have this notification silently updated every couple minutes to show the current time?
          data:
            push:
              sound: "US-EN-Alexa-Wife-Is-Arriving.wav"

automation:
  - alias: Notify Corban when Maggie is almost home
    id: 5277f05f-3f90-4eb7-8ba2-973a54482623
    trigger:
      - platform: numeric_state
        entity_id: sensor.maggie_to_home_travel_time
        below: 11
    condition:
      - condition: state
        entity_id: person.corban
        state: "home"
      - condition: state
        entity_id: person.maggie
        state: "not_home" # Only run if Maggie isn't home. Prevents some false triggers.
      - condition: state
        entity_id: timer.maggie_home_notification_cooldown
        state: idle
      - condition: time # From 7AM - 9PM
        after: "07:00:00"
        before: "21:00:00"
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "off"
    action:
      - service: script.turn_on
        entity_id: script.maggie_travel_time_send
      - service: timer.start
        entity_id: timer.maggie_home_notification_cooldown
        data:
          duration: "00:10:00" # 10 minute cooldown before retriggering.

timer:
  maggie_home_notification_cooldown:

homeassistant:
  customize:
    sensor.maggie_to_home_travel_time:
      icon: mdi:map-marker-distance
