sensor:
  - platform: waze_travel_time
    name: "Maggie to Home Travel Time"
    origin: device_tracker.google_maps_106112096418399445974 # TODO: Swap for HASS Companion-based device tracker?
    destination: zone.home
    region: "US"

script:
  maggie_travel_time_speak:
    alias: "Announce Maggie's Travel Time"
    icon: mdi:voice
    sequence:
      - delay:
          seconds: 5
      # - service: tts.google_cloud_say
      #   entity_id: media_player.living_room_speaker # media_player.everything
      #   data_template:
      #     message: >-
      #       {%- set minutes = states('sensor.maggie_to_home_travel_time') -%}
      #       Maggie is {{ minutes }} minute{% if minutes != 1 %}s{% endif %} away.
      - service: notify.corban
        data:
          title: "Maggie's Almost Home"
          message: "She's less than 10 minutes away." # TODO: Could I have this notification silently updated every couple minutes to show the current time?
          data:
            push:
              sound: "US-EN-Alexa-Wife-Is-Arriving.wav"

automation:
  - alias: Notify Corban when Maggie is almost home
    trigger:
      - platform: numeric_state
        entity_id: sensor.maggie_to_home_travel_time
        below: 11
    condition:
      - condition: state
        entity_id: person.corban
        state: "home"
      - condition: state
        entity_id: person.maggie
        state: "not_home" # Only run if Maggie isn't home. Prevents some false triggers.
      - condition: state
        entity_id: timer.maggie_home_notification_cooldown
        state: idle
      - condition: time # From 7AM - 9PM
        after: "07:00:00"
        before: "21:00:00"
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "off"
    action:
      - service: script.turn_on
        entity_id: script.maggie_travel_time_speak
      - service: timer.start
        entity_id: timer.maggie_home_notification_cooldown
        data:
          duration: "00:10:00" # 10 minute cooldown before retriggering.

timer:
  maggie_home_notification_cooldown:

homeassistant:
  customize:
    sensor.maggie_to_home_travel_time:
      icon: mdi:map-marker-distance
