input_boolean:
  vacation_mode:
    name: Vacation Mode
    icon: mdi:airplane
  vacation_mode_light_schedule:
    name: Automatic Light Schedule
    icon: mdi:av-timer

automation:
  ## After we've both been away for 24 hours, remind Corban to turn on vacation mode.
  - alias: Remind to enable vacation mode
    id: fecb932d-1057-4dcd-86ef-02aa781ad1cb
    trigger:
      - platform: state
        entity_id: group.adults
        to: "not_home"
        for: "24:00:00" # 1 day
    condition:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "off"
    action:
      - service: notify.corban
        data:
          title: "Are you on vacation?"
          message: "Would you like to turn on vacation mode?"
          data:
            tag: "vacation_mode_enable"
            actions:
              - action: "VACATION_MODE_ENABLE"
                title: "Yes, turn on."
                activationMode: "background"
                authenticationRequired: false # Don't require unlocking the device
                destructive: false
                behavior: "default"

  - alias: Turn on vacation mode notification clicked
    id: 4d882b21-3b3e-4623-a56a-a0613e116f2d
    trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: "VACATION_MODE_ENABLE"
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.vacation_mode

  ## Disable vacation mode
  - alias: Remind us to turn off vacation mode when we get home
    id: 6ef4ff8e-8071-40b8-a733-dc82174b4cdc
    trigger:
      - platform: state
        entity_id: group.adults
        to: "home"
    condition:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "on"
    action:
      - service: notify.adult_ios_phones
        data:
          title: "Welcome back!"
          message: "Turn off vacation mode?"
          data:
            tag: "vacation_mode_disable"
            actions:
              - action: "VACATION_MODE_DISABLE"
                title: "Yes, turn off."
                activationMode: "background"
                authenticationRequired: false # Don't require unlocking the device
                destructive: false
                behavior: "default"

  - alias: Turn off vacation mode notification clicked
    id: 89fa50e0-26af-422b-b527-fae14c20da8b
    trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: "VACATION_MODE_DISABLE"
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.vacation_mode
      - service: notify.adult_ios_phones
        data:
          message: clear_notification
          data:
            tag: "vacation_mode_disable"

  ## Schedule
  - alias: Schedule - Enable/Disable Automations
    id: f09c1102-a64e-469c-bc7b-1ef5e0a9ef90
    trigger:
      - platform: state
        entity_id: input_boolean.vacation_mode_light_schedule
    action:
      - choose:
          - conditions: "{{ trigger.to_state.state == 'on' }}"
            sequence:
              - service: homeassistant.turn_on
                entity_id: group.vacation_schedule_automations
          - conditions: "{{ trigger.to_state.state == 'off' }}"
            sequence:
              - service: homeassistant.turn_off
                entity_id: group.vacation_schedule_automations

  - alias: Schedule - Disable When Vacation Mode is Disabled
    id: 8adc1a54-a9de-43f6-bc08-9037b230e574
    trigger:
      - platform: state
        entity_id: input_boolean.vacation_mode
        to: "off"
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.vacation_mode_light_schedule

  - alias: Schedule - 1 - Some Lights On
    id: 15766a62-8506-4300-b76a-7beac8dbe97f
    trigger:
      - platform: time
        at: "18:03:00" # 6:03 PM
    condition:
      - condition: state
        entity_id: input_boolean.vacation_mode_light_schedule
        state: "on"
    action:
      - service: light.turn_on
        data:
          entity_id: light.tv_lamp
          brightness_pct: 80
  - alias: Schedule - 2 - Dim for movie
    id: 629411da-48de-4ffe-9e17-7d32370f2b8d
    trigger:
      - platform: time
        at: "19:26:00" # 7:26 PM
    condition:
      - condition: state
        entity_id: input_boolean.vacation_mode_light_schedule
        state: "on"
    action:
      - service: light.turn_on
        data:
          entity_id: light.tv_lamp
          brightness_pct: 40
  - alias: Schedule - 3 - Maggs to bed
    id: 7b57bfde-dbbc-43d4-86f5-6b15ec94d44e
    trigger:
      - platform: time
        at: "21:49:00" # 9:49 PM
    condition:
      - condition: state
        entity_id: input_boolean.vacation_mode_light_schedule
        state: "on"
    action:
      - service: light.turn_on
        data:
          entity_id: light.bedroom_lamp
          brightness_pct: 40
  - alias: Schedule - 4 - Maggs sleep
    id: a5428791-727a-4e3d-a137-5eae0db3a9f8
    trigger:
      - platform: time
        at: "22:15:00" # 10:15 PM
    condition:
      - condition: state
        entity_id: input_boolean.vacation_mode_light_schedule
        state: "on"
    action:
      - service: light.turn_off
        data:
          entity_id: light.bedroom_lamp
  - alias: Schedule - 5 - Everything off
    id: 29494677-5ec8-407d-a5a9-adda62a9eb39
    trigger:
      - platform: time
        at: "23:05:00" # 11:05 PM
    condition:
      - condition: state
        entity_id: input_boolean.vacation_mode_light_schedule
        state: "on"
    action:
      - service: light.turn_off
        data:
          entity_id: light.tv_lamp

group:
  vacation_schedule_automations:
    name: Scheduled Light Automations
    entities:
      - automation.schedule_1_some_lights_on
      - automation.schedule_2_dim_for_movie
      - automation.schedule_3_maggs_to_bed
      - automation.schedule_4_maggs_sleep
      - automation.schedule_5_everything_off
