automation:
  ## After we've both been away for 24 hours, remind Corban to turn on vacation mode.
  - alias: Remind to enable vacation mode
    id: fecb932d-1057-4dcd-86ef-02aa781ad1cb
    trigger:
      - platform: state
        entity_id: group.adults
        to: "not_home"
        for: "24:00:00" # 1 day
    condition:
      - condition: state
        entity_id: input_select.home_mode
        state:
          - "Home"
          - "Away"
    action:
      - service: notify.corban
        data:
          title: "Are you on vacation?"
          message: "Would you like to turn on vacation mode?"
          data:
            tag: "vacation_mode_enable"
            actions:
              - action: "VACATION_MODE_ENABLE"
                title: "Yes, turn on."
                activationMode: "background"
                authenticationRequired: false # Don't require unlocking the device
                destructive: false
                behavior: "default"

  - alias: Turn on vacation mode notification clicked
    id: 4d882b21-3b3e-4623-a56a-a0613e116f2d
    trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: "VACATION_MODE_ENABLE"
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.home_mode
          option: "Vacation"

  ## Disable vacation mode
  - alias: Remind us to turn off vacation mode when we get home
    id: 6ef4ff8e-8071-40b8-a733-dc82174b4cdc
    trigger:
      - platform: state
        entity_id: group.adults
        to: "home"
    condition:
      - condition: state
        entity_id: input_select.home_mode
        state: "Vacation"
    action:
      - service: notify.adult_ios_phones
        data:
          title: "Welcome back!"
          message: "Turn off vacation mode?"
          data:
            tag: "vacation_mode_disable"
            actions:
              - action: "VACATION_MODE_DISABLE"
                title: "Yes, turn off."
                activationMode: "background"
                authenticationRequired: false # Don't require unlocking the device
                destructive: false
                behavior: "default"

  - alias: Turn off vacation mode notification clicked
    id: 89fa50e0-26af-422b-b527-fae14c20da8b
    trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: "VACATION_MODE_DISABLE"
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.home_mode
          option: "Home"
      - service: notify.adult_ios_phones
        data:
          message: clear_notification
          data:
            tag: "vacation_mode_disable"

  - alias: Notify when door opened while on vacation
    id: e7e99aed-348c-4fb8-b607-df0b902f1387
    trigger:
      - platform: state
        entity_id: group.exterior_doors # See packages/bedtime_check_up.yaml
        to: "on"
    condition:
      - condition: state
        entity_id: input_select.home_mode
        state: "Vacation"
      - condition: state
        entity_id: input_boolean.cat_sitter_mode
        state: "off" # If on, this is handled by the cat sitter mode.
    action:
      - service: notify.corban
        data:
          title: "Warning: Door Opened"
          message: >-
            Exterior door(s) open: {{ expand("group.exterior_doors") | selectattr('state','eq','on') | map(attribute='name') | list | join(", ") }}
          data:
            tag: "vacation_alarm"
            actions:
              - action: "VACATION_ALARM"
                title: "Trigger Alarm"
                activationMode: "background"
                authenticationRequired: false
                destructive: true
                behavior: "default"
              - action: "VACATION_MODE_DISABLE" # Reusing the one from above.
                title: "Disable Vacation Mode"
                activationMode: "background"
                authenticationRequired: false
                destructive: false
                behavior: "default"

  - alias: Vacation Alarm Notification Action
    id: fb1b06e3-4897-4d16-98bf-a66cef5f414d
    trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: "VACATION_ALARM"
    action:
      - service: tts.cloud_say
        entity_id: media_player.kitchen_homepod
        data_template:
          message: Intruder. The owner has been notified.
      - delay:
          seconds: 15
      - service: tts.cloud_say
        entity_id: media_player.kitchen_homepod
        data_template:
          message: Intruder. The owner has been notified.
