# Automatically trigger the vacuum when no one is home, at most once a day.

# Note: This is also in `vacuum_reminder.yaml`, but currently disabled. If we re-enable that, merge.
# input_datetime:
#   last_vacuum_run:
#     name: Last Vacuum Run
#     has_date: true
#     has_time: false

automation:
  - alias: Trigger vacuum when no one is home for 5 minutes
    id: b789d523-89bf-4bd6-884d-6ad7a4e63b06
    trigger:
      - platform: state
        entity_id: input_select.home_mode
        from: "Home"
        to: "Away"
        for:
          minutes: 5
    condition:
      - alias: "Vacuum didn't run already today"
        condition: template
        value_template: >
          {{ states('input_datetime.last_vacuum_run') < (now().timestamp()) | timestamp_custom('%Y-%m-%d') }}
      - alias: "Vacuum is docked"
        condition: state
        entity_id: vacuum.valetudo_eve
        state: "docked"
    action:
      - alias: "Make sure no rooms are selected"
        service: homeassistant.turn_off
        target:
          entity_id: group.vacuum_rooms
      - alias: "Start cleaning"
        service: script.vacuum_clean_segments
      - alias: Wait for room clean to complete, or for someone to get home
        wait_for_trigger:
          - platform: state
            entity_id: vacuum.valetudo_eve
            to: "returning"
            id: "complete"
          - platform: state
            entity_id: input_select.home_mode
            to: "Home"
            id: "someone_home"
        timeout:
          minutes: 45
      - choose:
          # Timeout: Notify Corban
          - conditions: >-
              {{ wait.trigger == None }}
            sequence:
              - service: script.vacuum_alert_timeout

          # Someone got home during the clean: Return to base.
          - conditions: >-
              {{ wait.trigger.id == "someone_home" }}
            sequence:
              - service: vacuum.return_to_base
                target:
                  entity_id: vacuum.valetudo_eve

          # Cleaning finished normally: Update timestamp
          - conditions: >-
              {{ wait.trigger.id == "complete" }}
            sequence:
              - service: input_datetime.set_datetime
                target:
                  entity_id: input_datetime.last_vacuum_run
                data:
                  timestamp: "{{ now().timestamp() }}"

script:
  # Duplicated in `vacuum_reminder.yaml`, but commented out.
  vacuum_alert_timeout:
    alias: "Vacuum Helper: Notify Corban of a timeout"
    sequence:
      - service: notify.corban
        data:
          title: "Cleaning Error"
          message: "Vacuum didn't complete before timeout."
          data:
            group: "run_vacuum"

  vacuum_skip_today:
    alias: Skip today's automatic run of the vacuum
    sequence:
      - service: input_datetime.set_datetime
        target:
          entity_id: input_datetime.last_vacuum_run
        data:
          timestamp: "{{ now().timestamp() }}"
