# Creates the camera entity used in the custom Lovelace card.
camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    country: us
    # scan_interval: 60
    auto_update: false
    draw: ["all"]
    attributes:
      - calibration_points
    map_transformation:
      trim:
        top: 22
        bottom: 21
        left: 25
        right: 28

# Approximate Room Coordinates:
# Kitchen: [[18389,24967,20750,29782]]
# Cat Bath: [[18210,30896,22044,32724]]
# Office: [[22713,29826,26725,33883]]
# Living Room: [[20750,25056,27349,29648], [20750,29559,22178,30896]]
# Bedroom: [[20739,21010,26718,25004]]
# Master Bath: [[18140,20968,20697,24285]]

automation:
  - alias: Update vacuum map schedule each minute when undocked
    trigger:
      - platform: time_pattern
        minutes: "/1" # Trigger each minute
    condition:
      - condition: template
        value_template: "{{ not is_state('vacuum.xiaomi_vacuum_cleaner', 'docked') }}"
    action:
      - service: homeassistant.update_entity
        data:
          entity_id: camera.xiaomi_cloud_map_extractor

  - alias: Update vacuum map schedule each hour when docked
    trigger:
      - platform: time_pattern
        hours: "/1" # Trigger each hour
    condition:
      - condition: template
        value_template: "{{ is_state('vacuum.xiaomi_vacuum_cleaner', 'docked') }}"
    action:
      - service: homeassistant.update_entity
        data:
          entity_id: camera.xiaomi_cloud_map_extractor

  - alias: Remind Corban to run the vacuum
    trigger:
      - platform: time
        at: "11:00:00"
    condition:
      - alias: "Weekdays"
        condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - alias: "Maggie's not home"
        condition: state
        entity_id: binary_sensor.maggie_person_home
        state: "off"
      - alias: "Home Occupied"
        condition: state
        entity_id: input_boolean.home_occupied
        state: "on"
      - alias: "Not in Vacation Mode"
        condition: state
        entity_id: input_boolean.vacation_mode
        state: "off"
    action:
      - service: notify.corban
        data:
          title: "Time to Run Eve?"
          message: "Choose cleaning mode:"
          data:
            push:
              category: "run_vacuum" # Adds the action buttons.
            apns_headers:
              "apns-collapse-id": "run-vacuum"

  - alias: Run vacuum full clean from notification
    trigger:
      - platform: event
        event_type: ios.notification_action_fired
        event_data:
          categoryName: RUN_VACUUM
          actionName: FULL_CLEAN
    action:
      - alias: "Clean First Rooms"
        service: xiaomi_miio.vacuum_clean_zone
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          zone:
            - [22713, 29870, 26725, 33883] # Office
            - [18110, 30896, 22178, 32724] # Guest Bathroom
            - [18389, 24967, 20750, 29782] # Kitchen
            - [20739, 21010, 26718, 25004] # Bedroom
          repeats: 1
      - service: script.vacuum_wait_and_alert # Moved to shared logic.

  - alias: Run vacuum partial clean from notification
    trigger:
      - platform: event
        event_type: ios.notification_action_fired
        event_data:
          categoryName: RUN_VACUUM
          actionName: NO_OFFICE_CLEAN
    action:
      - alias: "Clean First Rooms"
        service: xiaomi_miio.vacuum_clean_zone
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          zone:
            - [18110, 30896, 22178, 32724] # Guest Bathroom
            - [18389, 24967, 20750, 29782] # Kitchen
            - [20739, 21010, 26718, 25004] # Bedroom
          repeats: 1
      - service: script.vacuum_wait_and_alert # Moved to shared logic.

  - alias: Resume Vacuum Cleaning From Notification
    trigger:
      - platform: event
        event_type: ios.notification_action_fired
        event_data:
          categoryName: RUN_VACUUM_CONT
          actionName: RESUME_CLEAN
    action:
      - alias: "Finish Clean"
        service: xiaomi_miio.vacuum_clean_zone
        data:
          entity_id: vacuum.xiaomi_vacuum_cleaner
          zone:
            - [18140, 20968, 20739, 24285] # Master Bathroom
            - [20751, 29870, 22178, 30896] # Living Room - Ext
            - [20750, 25004, 27349, 29870] # Living Room - Main
          repeats: 1
      - delay:
          seconds: 30
      - wait_template: "{{ is_state('vacuum.xiaomi_vacuum_cleaner', 'docked') }}"
        timeout:
          minutes: 60
      - choose:
          - conditions: "{{ not wait.completed }}"
            sequence:
              - service: notify.corban
                data:
                  title: "Cleaning Error"
                  message: "Vacuum didn't return to dock before timeout."
                  data:
                    apns_headers:
                      "apns-collapse-id": "run-vacuum"
        default:
          - service: notify.corban
            data:
              title: "Vacuum Done"
              message: "Remember to empty the bin."
              data:
                apns_headers:
                  "apns-collapse-id": "run-vacuum"

script:
  vacuum_wait_and_alert:
    alias: "Vacuum Helper: Wait for completion and send notification."
    sequence:
      - delay:
          seconds: 30
      - wait_template: "{{ is_state('vacuum.xiaomi_vacuum_cleaner', 'docked') }}"
        timeout:
          minutes: 60
      - choose:
          - conditions: "{{ not wait.completed }}"
            sequence:
              - service: notify.corban
                data:
                  title: "Cleaning Error"
                  message: "Vacuum didn't return to dock before timeout."
                  data:
                    apns_headers:
                      "apns-collapse-id": "run-vacuum"
        default:
          - service: notify.corban
            data:
              title: "Empty Eve's Bin"
              message: "Confirm when the bin has been emptied."
              data:
                push:
                  category: "run_vacuum_cont" # Adds the action buttons.
                apns_headers:
                  "apns-collapse-id": "run-vacuum"

ios:
  push:
    categories:
      - name: Daily Vacuum Reminder
        identifier: "run_vacuum"
        actions:
          - identifier: "FULL_CLEAN"
            title: "Full Clean"
            activationMode: "background"
            authenticationRequired: false # Don't require unlocking the device
            destructive: false
            behavior: "default"
          - identifier: "NO_OFFICE_CLEAN"
            title: "Skip the Office"
            activationMode: "background"
            authenticationRequired: false # Don't require unlocking the device
            destructive: false
            behavior: "default"
      - name: Daily Vacuum Reminder - Follow Up
        identifier: "run_vacuum_cont"
        actions:
          - identifier: "RESUME_CLEAN"
            title: "Resume Cleaning"
            activationMode: "background"
            authenticationRequired: false # Don't require unlocking the device
            destructive: false
            behavior: "default"
