# Package for the wake on LAN setup

switch:
  - platform: wake_on_lan
    name: "Obama"
    mac_address: !secret obama_mac
    host: !secret obama_host
    turn_off:
      service: rest_command.sleep_obama

rest_command:
  sleep_obama:
    url: !secret obama_sleep_url
  shutdown_obama:
    url: !secret obama_shutdown_url

homeassistant:
  customize:
    switch.obama:
      icon: mdi:desktop-tower
