# For the central living room wall-mounted tablet.
# These are helpers used to populate the main dashboard and control some dynamic cards.

template:
  - binary_sensor:
      - name: "Wall Display: Show Kitchen Media Card"
        unique_id: 8447646c-fbf8-4200-9e87-26a6b0ea2104
        delay_off:
          minutes: 30
        state: >-
          {{ is_state('media_player.kitchen_2', 'playing') }}
        icon: mdi:music-circle-outline

      - name: Corban On a Call
        state: >-
          {{
            is_state('binary_sensor.cmaillouxtjq31_audio_input_in_use', 'on')
            or is_state('binary_sensor.cmaillouxtjq31_camera_in_use', 'on')
          }}
        icon: >-
          {% set camera_on = is_state('binary_sensor.cmaillouxtjq31_camera_in_use', 'on') %}
          {% if camera_on %}
            mdi:video
          {% else %}
            mdi:video-off
          {% endif %}

input_boolean:
  wall_display_show_map:
    name: Show Map on Wall Display
    icon: mdi:map-clock

automation:
  - alias: Show map when Maggie's away from home
    id: 229ee037-4e8d-43bc-a5ab-acd4f19bb2a0
    triggers:
      - trigger: state
        entity_id: person.maggie
        to: "not_home"
        for: "00:01:00" # Debounce for a minute
    actions:
      - action: input_boolean.turn_on
        data:
          entity_id: input_boolean.wall_display_show_map

  - alias: Hide map when Maggie gets home or to work
    id: df202fb6-6230-4c51-bcc5-18572973fbba
    triggers:
      - trigger: state
        entity_id: person.maggie
        to:
          - "home"
          - "L3Harris"
          - "Clay Studio"
        for: "00:01:00"
    actions:
      - action: input_boolean.turn_off
        data:
          entity_id: input_boolean.wall_display_show_map

  # See also `package/home_away_mode.yaml`.
  - alias: Turn on the wall display in the morning # if someone is home
    id: ec56904d-4cc0-4966-9b98-8c790bf6e76d
    triggers:
      - trigger: time
        at: "06:01:00"
    conditions:
      - condition: state
        entity_id: input_select.home_mode
        state: "Home"
    actions:
      - action: light.turn_on
        data:
          entity_id: light.tablet_wall_display_screen
