# For the central living room wall-mounted tablet.
# These are helpers used to populate the main dashboard and control some dynamic cards.

camera:
  - platform: generic
    name: Join Our WiFi
    still_image_url: !secret wifi_qr_code_url

input_boolean:
  wall_display_show_map:
    name: Show Map on Wall Display

  put_trash_out_display:
    name: Display Trash Notification

automation:
  - alias: Show map when Maggie's on her way home
    trigger:
      - platform: state
        entity_id: person.maggie
        from: "RE"
        to: "not_home"
        for: "00:01:00" # Debounce for a minute
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.wall_display_show_map

  - alias: Hide map when Maggie gets home
    trigger:
      - platform: state
        entity_id: person.maggie
        from: "not_home"
        to: "home"
        for: "00:03:00" # Allow a couple minute window
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.wall_display_show_map

  - alias: Update Trash Sensor
    trigger:
      - platform: time_pattern
        minutes: 1 # Every hour at *:01
    action:
      - service: homeassistant.update_entity
        entity_id: binary_sensor.put_trash_out

  - alias: Update trash input_boolean to match template sensor
    trigger:
      - platform: state
        entity_id: binary_sensor.put_trash_out
    action:
      - choose:
        - conditions:
            - condition: state
              entity_id: binary_sensor.put_trash_out
              state: "on"
          sequence:
            - service: input_boolean.turn_on
              data:
                entity_id: input_boolean.put_trash_out_display
        - conditions:
          - condition: state
            entity_id: binary_sensor.put_trash_out
            state: "off"
          sequence:
            - service: input_boolean.turn_off
              data:
                entity_id: input_boolean.put_trash_out_display

  # See also `package/home_away_mode.yaml`.
  - alias: Turn on the wall display in the morning # if someone is home
    trigger:
      - platform: time
        at: "06:00:00"
    condition:
      - condition: state
        entity_id: input_boolean.home_occupied
        state: "on"
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "off"
    action:
      - service: light.turn_on
        data:
          entity_id: light.tablet_wall_display_screen

binary_sensor:
  - platform: template
    sensors:
      put_trash_out:
        friendly_name: Time to put the trash out
        icon_template: "mdi:delete-sweep"
        value_template: >-
          {% set time = now() %}

          {% if 0 <= time.weekday() <= 3 or time.weekday() == 6 %}
            {# Monday - Thursday, Sunday: 5-7PM #}
            {% if time.hour < 17 %}
              False
            {% elif 17 <= time.hour <= 18 %}
              True
            {% else %}
              False {# Too late #}
            {% endif %}
          {% else %}
            False
          {% endif %}
        device_class: problem

  - platform: template
    sensors:
      corban_on_a_call:
        friendly_name: Corban's On a Call
        icon_template: >-
          {% set camera_on = is_state('binary_sensor.corban_s_vmware_mbp_camera_in_use', 'on') %}

          {% if camera_on %}
            mdi:video
          {% else %}
            mdi:video-off
          {% endif %}
        value_template: >-
          {{
            is_state('binary_sensor.corban_s_vmware_mbp_microphone_in_use', 'on')
            or is_state('binary_sensor.corban_s_vmware_mbp_camera_in_use', 'on')
          }}
