# New wall display elements. (The old wall display will be removed after this one is deployed.)

input_boolean:
  wall_display_show_map:
    name: Show Map on Wall Display
  wall_display_show_to_do_list:
    name: Show To Do List on Wall Display
  wall_display_show_cat_food_times:
    name: Show Cat Food Times on Wall Display

automation:
  - alias: Show map when Maggie's on her way home
    trigger:
      - platform: state
        entity_id: person.maggie
        from: "re"
        to: "not_home"
        for: "00:01:00" # Debounce for a minute
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: wall_display_show_map

  - alias: Hide map when Maggie gets home
    trigger:
      - platform: state
        entity_id: person.maggie
        from: "not_home"
        to: "home"
        for: "00:03:00" # Allow a couple minute window
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: wall_display_show_map
