# New wall display, made with a Samsung Galaxy Tab A7 tablet and using Fully Kiosk browser for control.

# Great structure from https://kleypot.com/fully-kiosk-rest-api-integration-in-home-assistant/
light:
  - platform: template
    lights:
      tablet_wall_display_screen:
        friendly_name: Wall Display Screen
        value_template: '{{ state_attr("sensor.tablet_wall_display_device_info", "screenOn") }}'
        level_template: '{{ state_attr("sensor.tablet_wall_display_device_info", "screenBrightness") }}'
        turn_on:
          service: rest_command.tablet_wall_display_command
          data:
            cmd: screenOn
        turn_off:
          service: rest_command.tablet_wall_display_command
          data:
            cmd: screenOff
        set_level:
          service: rest_command.tablet_wall_display_command
          data_template:
            cmd: setStringSetting
            key: screenBrightness
            value: "{{ brightness }}"

sensor:
  - platform: rest
    name: Tablet Wall Display Device Info
    resource: !secret tablet_wall_display_get_device_info_url
    json_attributes:
      - screenBrightness
      - screenOn
      - plugged
    value_template: "OK"
    scan_interval: 10 # seconds

rest_command:
  tablet_wall_display_command:
    url: !secret tablet_wall_display_command_url

script:
  tablet_wall_display_reload:
    alias: "Reload the Wall Display"
    icon: "mdi:refresh"
    sequence:
      - service: rest_command.tablet_wall_display_command
        data:
          cmd: loadStartUrl

  tablet_wall_display_restart:
    alias: "Restart the Wall Display"
    icon: "mdi:power"
    sequence:
      - service: rest_command.tablet_wall_display_command
        data:
          cmd: rebootDevice

automation:
  - alias: Notify if the wall display comes unplugged
    id: 6885c896-0a99-4cbe-bbf5-16fc703f1c32
    trigger:
      - platform: state
        entity_id: sensor.tablet_wall_display_device_info
        attribute: plugged
        to: false
        for: "00:00:30"
    action:
      - service: notify.corban
        data:
          title: "Wall Display Unplugged"
          message: "The wall display has been unplugged for at least 30 seconds."
