# New wall display, made with a Samsung Galaxy Tab A7 tablet and using Fully Kiosk browser for control.

# Great structure from https://kleypot.com/fully-kiosk-rest-api-integration-in-home-assistant/
template:
  - light:
      - name: Wall Display Screen
        turn_on:
          - action: rest_command.tablet_wall_display_command
            data:
              cmd: screenOn
        turn_off:
          - action: rest_command.tablet_wall_display_command
            data:
              cmd: screenOff
        set_level:
          - action: rest_command.tablet_wall_display_command
            data_template:
              cmd: setStringSetting
              key: screenBrightness
              value: "{{ brightness }}"
        default_entity_id: light.tablet_wall_display_screen
        level: '{{ state_attr("sensor.tablet_wall_display_device_info", "screenBrightness")}}'
        state: '{{ state_attr("sensor.tablet_wall_display_device_info", "screenOn") }}'

sensor:
  - platform: rest
    name: Tablet Wall Display Device Info
    resource: !secret tablet_wall_display_get_device_info_url
    json_attributes:
      - screenBrightness
      - screenOn
      - plugged
    value_template: "OK"
    scan_interval: 10 # seconds

rest_command:
  tablet_wall_display_command:
    url: !secret tablet_wall_display_command_url

script:
  tablet_wall_display_reload:
    alias: "Reload the Wall Display"
    icon: "mdi:refresh"
    sequence:
      - action: rest_command.tablet_wall_display_command
        data:
          cmd: loadStartUrl

  tablet_wall_display_restart:
    alias: "Restart the Wall Display"
    icon: "mdi:power"
    sequence:
      - action: rest_command.tablet_wall_display_command
        data:
          cmd: rebootDevice

automation:
  - alias: Notify if the wall display comes unplugged
    id: 6885c896-0a99-4cbe-bbf5-16fc703f1c32
    triggers:
      - trigger: state
        entity_id: sensor.tablet_wall_display_device_info
        attribute: plugged
        from: true
        to: false
        for: "00:00:30"
    actions:
      - action: notify.corban
        data:
          title: "Wall Display Unplugged"
          message: "The wall display has been unplugged for at least 30 seconds."
