light:
  - platform: walldisplay
    host: !secret wall_display_ip

automation:
  # See also `package/home_away_mode.yaml`.
  - alias: Turn on the wall display in the morning # if someone is home
    trigger:
      - platform: time
        at: "06:30:00"
    condition:
      - condition: state
        entity_id: input_boolean.home_occupied
        state: "on"
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "off"
    action:
      - service: light.turn_on
        data:
          entity_id: light.wall_display_screen

homeassistant:
  customize:
    light.wall_display_light:
      icon: mdi:tablet
    light.wall_display_screen:
      icon: mdi:monitor
