# The washer is plugged into a power-monitoring smart plug (Linksio).
# It's flashed with Tasmota, and `PowerOnState 4` means that it's always on.

# TODO/Ideas:
# - The average washer cycle here is ~58 minutes. When starting, set a countdown timer on a wall display for an estimated completion.

template:
  - binary_sensor:
      - name: "Washing Machine Running"
        unique_id: 5b770b3c-326a-49ca-87ee-fa3de53fdeff
        device_class: running
        delay_off:
          minutes: 6
        state: >-
          {{ states('sensor.washing_machine_power_draw') | float(default=0) > 3 }}
        icon: >
          {% if is_state("binary_sensor.washing_machine_running", "on") %}
            mdi:washing-machine
          {% else %}
            mdi:washing-machine-off
          {% endif %}

      - name: "Dryer Running"
        unique_id: a23ea7c7-bf17-4115-86ee-c9db0a54e359
        device_class: running
        delay_on:
          minutes: 7 # Avoid accidental triggers from bumping the machine.
        delay_off:
          minutes: 5
        state: >-
          {{ is_state('binary_sensor.vibration_sensor_vibration', 'on') }}
        icon: >-
          {% if is_state('binary_sensor.dryer_running', 'on') %}
            mdi:tumble-dryer
          {% else %}
            mdi:tumble-dryer-off
          {% endif %}

automation:
  - id: e3edfa1f-a705-4394-bedb-945151332a3c
    alias: Notify when washing machine finishes
    trigger:
      - platform: state
        entity_id: binary_sensor.washing_machine_running
        from: "on"
        to: "off"
    action:
      - alias: "Notify both adults"
        service: notify.adult_phones
        data:
          title: "Laundry Reminder"
          message: "Washing machine done."
          data:
            tag: "laundry_reminder_washer"

  - id: b7bfbfd8-569c-4ca2-9eae-f1bd4ba3a539
    alias: Notify when dryer finishes
    trigger:
      - platform: state
        entity_id: binary_sensor.dryer_running
        from: "on"
        to: "off"
    action:
      - alias: "Notify both adults"
        service: notify.adult_phones
        data:
          title: "Laundry Reminder"
          message: "Dryer done."
          data:
            tag: "laundry_reminder_dryer"

  - id: ededc678-7213-41e3-85bd-dba525236d56
    alias: Notify Corban when dryer starts - temporary for testing
    trigger:
      - platform: state
        entity_id: binary_sensor.dryer_running
        from: "off"
        to: "on"
    action:
      - service: notify.corban
        data:
          title: "Laundry Reminder - Debug"
          message: "Dryer starting."
          data:
            tag: "laundry_reminder_dryer"
