automation:
  - id: 9605bd48-55b1-4d21-a54d-25847b6d453d
    alias: Water Leak Detected - Send Critical Notifications
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_sink_water_leak_sensor_water_sensor
        to: "on"
        id: "under the kitchen sink"
      - platform: state
        entity_id: binary_sensor.water_heater_water_leak_sensor_water_sensor
        to: "on"
        id: "near the water heater"
      - platform: state
        entity_id: binary_sensor.water_softener_water_leak_sensor_water_sensor
        to: "on"
        id: "near the water softener"
      - platform: state
        entity_id: binary_sensor.washing_machine_water_leak_sensor_water_sensor
        to: "on"
        id: "near the washing machine"
      - platform: state
        entity_id: binary_sensor.master_bathroom_sink_water_leak_sensor_water_sensor
        to: "on"
        id: "under the master bathroom sink"
      - platform: state
        entity_id: binary_sensor.guest_bathroom_sink_water_leak_sensor_water_sensor
        to: "on"
        id: "under the guest bathroom sink"
      - platform: state
        entity_id: binary_sensor.first_floor_bathroom_water_leak_sensor_water_sensor
        to: "on"
        id: "under the first floor bathroom sink"
    action:
      - alias: "Notify Everyone with a Critical Notification"
        service: notify.adult_ios_phones
        data:
          title: "Water Leak Detected at Home"
          message: >-
            Water detected {{ trigger.id }}.
          data:
            # tag: "water_leak_alert" # Don't tag so they don't get grouped.
            push:
              sound:
                # name: "default"
                critical: 1 # Push through mute and Focus
                # volume: 1.0
