# Package for the Yi Camera
# Uses https://github.com/fritz-smh/yi-hack

camera:
  - platform: ffmpeg
    name: yi
    input: !secret yi_camera_sd
    extra_arguments: "-pred 1"


weblink:
  entities:
    - name: Yi Recordings
      url: !secret yi_camera_recordings_url
      icon: mdi:record-rec


sensor:
  - platform: scrape
    name: Yi Most Recent Recording
    resource: http://10.0.0.250/motion
    select: "body"


binary_sensor:
  - platform: template
    sensors:
      yi_motion:
        value_template: '{{ states("sensor.yi_most_recent_recording") | length > 0 }}'
        friendly_name: 'Yi Motion Detected'
        device_class: motion


group:
  yi_camera:
    name: Yi Camera
    control: hidden
    entities:
      - camera.yi
      - weblink.yi_recordings
      - sensor.yi_most_recent_recording
      - binary_sensor.yi_motion
